group:
  cameras:
    name: Cameras
    view: yes
    icon: mdi:cctv
    entities:
      - switch.modect
      - group.cameras_living_room
      - group.cameras_misc
      - group.cameras_office
      - group.cameras_terrace
      - group.cameras_front_door
      - camera.ph1

# vim: set filetype=yaml et sw=2 ts=2 :
