panel_iframe:
  zoneminder:
    title: 'Zoneminder'
    url: 'https://zm.home.comreset.io/zm/index.php'
    icon: 'mdi:cctv'

  grafana:
    title: 'Grafana'
    url: 'https://graphs.home.comreset.io'
    icon: 'mdi:finance'

  nodered:
    title: 'Node-RED'
    url: 'https://nodered.home.comreset.io'
    icon: 'mdi:sitemap'

