group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.info
      - group.shortcuts
      - group.weather_shortcut
      - group.light_groups
      - media_player.cast_home_group
      - covers.all_covers
      - group.all_covers

  info:
    name: Info
    control: hidden
    view: no
    entities:
      # - device_tracker.op3t_arp
      # - device_tracker.op3t_ping
      # - device_tracker.g4p_arp
      # - device_tracker.g4p_zanzito
      - group.main_mobile_devices
      - sensor.g4p_find
      # - group.pschmitt_location
      - sensor.ip_location_short
      - sensor.exchange_rate_1_btc

  shortcuts:
    name: Shortcuts
    control: hidden
    view: no
    entities:
      - alarm_control_panel.ha_alarm_mqtt
      - alarm_control_panel.arlomio
      - script.buzz_door_open
      - binary_sensor.door_window_sensor_front_door
      - binary_sensor.motion_sensor_front_door
      - lock.front_door
      - script.all_off


homeassistant:
  customize:
    group.info:
      order: 1
    group.shortcuts:
      order: 2
    group.living_room:
      order: 1
    group.kitchen:
      order: 2
    group.terrace:
      order: 3
    group.office:
      order: 4
    group.bedroom:
      order: 5
    group.misc:
      order: 5
    group.media_players:
      order: 6
    group.cctv:
      order: 7

# vim: set filetype=yaml et sw=2 ts=2 :
