group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.info
      - group.shortcuts
      - group.weather_shortcut
      - group.main_lights
      - media_player.cast_home_group
      # Covers
      - cover.all_covers
      - cover.bedroom
      - cover.kitchen
      - cover.living_room_main
      - cover.living_room

  info:
    name: Info
    control: hidden
    view: no
    entities:
      - device_tracker.google_maps_111748235994603810778
      - device_tracker.google_maps_105543397094537443482
      - group.main_mobile_devices
      - sensor.g4p_find3
      - sensor.ip_location_short
      - sensor.exchange_rate_1_btc
      - sensor.weather_indoor
      - sensor.smappee_home_active_power
      - sensor.smappee_local_active_power

  shortcuts:
    name: Shortcuts
    control: hidden
    view: no
    entities:
      - alarm_control_panel.ha_alarm_mqtt
      - alarm_control_panel.arlomio
      - script.buzz_door_open
      - binary_sensor.door_window_sensor_front_door
      - binary_sensor.motion_sensor_front_door
      - lock.front_door
      - script.cover_privacy
      - script.cover_movie_smoke_break
      - script.all_off


homeassistant:
  customize:
    group.info:
      order: 1
    group.shortcuts:
      order: 2
    group.living_room:
      order: 1
    group.kitchen:
      order: 2
    group.terrace:
      order: 3
    group.office:
      order: 4
    group.bedroom:
      order: 5
    group.misc:
      order: 5
    group.media_players:
      order: 6
    group.cctv:
      order: 7
    group.batteries:
      order: 98

# vim: set filetype=yaml et sw=2 ts=2 :
