group:
  bedroom:
    name: Bedroom
    view: no
    icon: mdi:hotel
    entities:
      - light.bedroom
      - scene.bedtime
      - script.all_off
      - cover.bedroom_table
      - cover.bedroom_door

  appliances:
    name: Appliances
    view: no
    icon: mdi:robot
    control: hidden
    entities:
      - binary_sensor.washing_machine
      - switch.wemo_insight__washing_machine
      - vacuum.nimbus
      - group.fridge
      - group.3d_printer

  misc:
    name: Misc
    view: yes
    icon: mdi:square-inc
    entities:
      - light.bedroom
      - light.toilet
      - light.bathroom
      - group.appliances
      - group.3d_printer

  office:
    name: Office
    view: yes
    icon: mdi:book-open
    entities:
      - light.office_light
      - light.yeelight_office
      - light.3d_printer_led
      - switch.wemo_insight__nasteanas
      - switch.office_tv
      - camera.hassistant
      - media_player.office_speaker
      - media_player.office_tv
      - group.office_windows

  office_lights:
    name: All Office Lights
    view: no
    icon: mdi:lightbulb
    entities:
      - light.office_light
      - light.yeelight_office

  office_windows:
    name: Office Windows
    view: no
    entities:
      - binary_sensor.door_window_sensor_office_window_large
      - binary_sensor.door_window_sensor_office_window_small
      - cover.office

  living_room:
    name: Living Room
    view: yes
    icon: mdi:sofa
    entities:
      - group.living_room_media_player_scripts
      - switch.wall_socket
      - camera.c1
      - group.living_room_media_players
      - group.living_room_windows
      - group.living_room_lights

  living_room_lights:
    name: Living Room Lights
    view: no
    entities:
      - light.living_room_tv_light
      - light.living_room_table_light
      - light.gateway_light_34ce008d7aba
      - light.front_door
      - light.terrace
      - scene.living_room_normal
      - scene.living_room_dim

  living_room_windows:
    name: Living Room Windows
    view: no
    control: hidden
    entities:
      - binary_sensor.door_window_sensor_terrace_door
      - binary_sensor.door_window_sensor_living_room_window
      - cover.living_room_door
      - cover.living_room_table
      - cover.living_room_tv


  living_room_media_players:
    name: Media Players
    view: no
    entities:
      - media_player.tv
      - media_player.living_room_speaker

  living_room_media_player_scripts:
    name: TV Activities
    control: hidden
    view: no
    entities:
      - input_select.tv_activity
      - sensor.harmony_hub
      - script.amp_toggle
      - script.tv_activity_dolphin_emu
      - script.tv_activity_kodi
      - script.tv_activity_ps3
      - script.tv_activity_shield_tv
      - script.tv_activity_watch_tv
      - script.wake_nvidia_shield
      - script.harmony_power_off
      - script.turn_off_media_players

  terrace:
    name: Terrace
    view: yes
    icon: mdi:tree
    entities:
      - group.weather_outdoor
      - group.all_plants
      - binary_sensor.plant_data_outdated
      - script.refresh_plant_data
      - camera.winpi
      - camera.weather
      - camera.centre_pompidou
      - camera.centre_congres
      - light.terrace_light
      - script.smoke_break
      - group.terrace_doors
      - cover.living_room_door
      - cover.bedroom_door
      - input_datetime.smoke_break_duration

  kitchen:
    name: Kitchen
    view: yes
    icon: mdi:pot-mix
    entities:
      - camera.c2
      - light.kitchen_light
      - group.fridge
      - group.kitchen_window

  kitchen_window:
    name: Kitchen Window
    view: no
    entities:
      - cover.kitchen
      - binary_sensor.door_window_sensor_kitchen_window

# vim: set filetype=yaml et sw=2 ts=2 :
