input_boolean:
  dnd:
    name: DND Mode
    icon: mdi:volume-off

  vacation:
    name: Vacation Mode
    icon: mdi:airplane-takeoff

  ac_off_the_window:
    name: "AC hanging off the window"
    icon: mdi:ice-cream


group:
  settings:
    name: Settings
    view: yes
    icon: mdi:settings
    entities:
      - input_boolean.dnd
      - input_boolean.vacation
      - input_boolean.sleepover
      - input_boolean.motion_light_front_door
      - input_boolean.motion_light_office
      - input_boolean.motion_light_living_room
      - input_boolean.motion_light_terrace
      - input_datetime.bedtime
      - input_datetime.roomba_autostart_time
      - input_number.battery_alert_threshold_max
      - input_number.smoke_break_duration


automation:
  - alias: "Disable DND mode at 07:00"
    initial_state: true
    trigger:
      - platform: time
        at: '07:00:00'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.dnd


homeassistant:
  customize:
    input_number.battery_alert_threshold_max:
      friendly_name: "Battery alert level"

# vim: set filetype=yaml et sw=2 ts=2 :
