input_boolean:
  dnd:
    name: DND Mode
    icon: mdi:volume-off

  vacation:
    name: Vacation Mode
    icon: mdi:airplane-takeoff


group:
  settings:
    name: Settings
    view: yes
    icon: mdi:pencil
    entities:
      - input_boolean.dnd
      - input_boolean.vacation
      - input_boolean.sleepover
      - input_datetime.bedtime
      - input_datetime.roomba_autostart_time
      - input_number.battery_alert_threshold_max
      - input_number.smoke_break_duration


homeassistant:
  customize:
    input_number.battery_alert_threshold_max:
      friendly_name: "Battery alert level"

# vim: set filetype=yaml et sw=2 ts=2 :
