group:
  surveillance:
    name: Surveillance
    view: yes
    icon: mdi:blur-radial
    entities:
      - group.windows
      - group.motion_sensors

  motion_sensors:
    name: Motion Sensors
    view: no
    icon: mdi:run
    entities:
      - binary_sensor.bathroom_presence
      - binary_sensor.hallway_presence
      - binary_sensor.kitchen_presence
      - binary_sensor.motion_sensor_front_door
      - binary_sensor.motion_sensor_living_room
      - binary_sensor.motion_sensor_office
      - binary_sensor.motion_sensor_terrace
      - binary_sensor.toilet_presence
