appdaemon:
  disable_apps: 1
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: !secret ha_url
      ha_key: !secret ha_key

hadashboard:
  dash_url: !secret dash_url
