media_player:
  - platform: cast
    host: chromecast-audio.lan
    name: BlindCast

  - platform: cast
    host: chromecast.lan
    name: BrightCast

  - platform: cast
    host: audiocast.lan
    name: Sony SRS-Z7

# vim: set filetype=yaml et sw=2 ts=2 :
