lock:
  - platform: nello
    username: !secret nello_username
    password: !secret nello_password


automation:
  - alias: Notify when the door bell has been rung
    trigger:
      - platform: event
        event_type: nello_bell_ring
        event_data:
          short_id: e414cae5
    action:
      - service: notify.html5
        data:
          message: 'Nello: The door bell rung.'


script:
  buzz_door_open:
    alias: Buzz door open
    sequence:
      - service: lock.unlock
        data:
          entity_id: lock.nello_e414cae5


homeassistant:
  customize:
    lock.nello_e414cae5:
      friendly_name: Nello Home

# vim: set filetype=yaml et sw=2 ts=2 :
