language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant
script:
  - hass -c config --script check_config
before_install:
  - mv config/.travis/secrets.yaml config/secrets.yaml
  - mv config/.travis/trusted_networks.yaml config/trusted_networks.yaml
  - rm config/home-assistant.log
