language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant
script:
  - hass -c config --script check_config
before_install:
  - mv config/hass/.travis/secrets.yaml config/hass/secrets.yaml
  - mv config/hass/.travis/trusted_networks.yaml config/hass/trusted_networks.yaml
  - rm config/hass/home-assistant.log
