  - alias: Train reminder
    trigger:
      - platform: time
        hours: 16
        minutes: 23
        seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.moto_g4play
        state: work
    action:
      service: notify.pushover
      data:
        message: 'Time to leave for your train'

  # - alias: 'Bruh your phone is dying'
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: sensor.nexus_5x_battery
  #       below: 30
  #   action:
  #     service: notify.pushover
  #     data:
  #       message: 'Bruh your phone is dying. Charge it!'

  - alias: 'Media player paused/stopped'
    trigger:
      - platform: state
        entity_id: media_player.kodishield
        from: 'playing'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      service: scene.turn_on
      entity_id: scene.living_room_normal

  - alias: 'Media player playing'
    trigger:
      - platform: state
        entity_id: media_player.kodishield
        to: 'playing'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      service: scene.turn_on
      entity_id: scene.living_room_dim

  - alias: Z3C Battery saver
    trigger:
      - platform: numeric_state
        entity_id: sensor.z3c_battery
        below: 25
    action:
      service: homeassistant.turn_off
      entity_id: switch.z3c_cam

  - alias: Z3C Camera enabler
    trigger:
      - platform: numeric_state
        entity_id: sensor.z3c_battery
        above: 80
    action:
      service: homeassistant.turn_on
      entity_id: switch.z3c_cam

  - alias: Notify when HA starts
    trigger:
      - platform: event
        event_type: homeassistant_start
    action:
      service: notify.pushover
      data:
        message: "Home Assistant has (re)started"

  - alias: Update notifications
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.pushover
      data_template:
        message: "Home Assistant {{ states.updater.updater.state }} is now available."

  # Alarm section

  - alias: Arm alarm when erribody is away (and HASS starts)
    trigger:
      - platform: event
        event_type: homeassistant_start
    condition:
      - condition: state
        entity_id: group.tracked_devices
        state: not_home
    action:
      - service: script.alarm_arm_away

  - alias: Arm alarm when erribody is away
    trigger:
      - platform: state
        entity_id: group.tracked_devices
        state: not_home
    action:
      - service: script.alarm_arm_away

  - alias: Hue Motion Detector triggered
    trigger:
      - platform: state
        entity_id: sensor.toilet_presence
        state: "True"
      - platform: state
        entity_id: sensor.floor_presence
        state: "True"
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
      - service: notify.get_to_me
        data_template:
          message: >
            {{ trigger.to_state.attributes.friendly_name }}
            Motion has been detected

  - alias: Trigger an alert when zoneminder picks up a new event
    trigger:
      - platform: state
        entity_id: sensor.c1_events
      - platform: state
        entity_id: sensor.c2_events
      - platform: state
        entity_id: sensor.octopi_events
      - platform: state
        entity_id: sensor.z3c_events
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: armed_away
        - condition: template
          value_template: >
            {% if trigger.from_state.state == 'unknown' %}
              false
            {% else %}
              {{ trigger.from_state.state | int < trigger.to_state.state | int }}
            {% endif %}
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
      - service: notify.get_to_me
        data_template:
          message: >
            ALERT: {{ trigger.to_state.attributes.friendly_name }} has detected motion

  - alias: Notify when a new platform has been discovered
    trigger:
      - platform: event
        event_type: platform
    action:
      service: notify.smsr
      data_template:
        message: "Home Assistant has discovered a new device: {{ discovered }}"
        target: me

  - alias: Notify when new network device has been discovered
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      service: notify.smsr
      data_template:
        message: "A new device has connected to your LAN: {{ host_name }}"
        target: me

  - alias: Away armed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      - service: script.alarm_armed_away

  - alias: Alarm disarmed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
    action:
      - service: script.alarm_disarmed

  - alias: Alarm has been triggered
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        state: triggered
    # condition:
    #     - condition: state
    #       entity_id: alarm_control_panel.ha_alarm
    #       state: not_disarmed
    action:
      - service: script.alarm_triggered

  # End of Alarm section

  - alias: React to my homecoming
    trigger:
      - platform: state
        entity_id: device_tracker.moto_g4play
        from: not_home
        # from: away
        to: home
    action:
      - service: script.im_home

  - alias: Talk to my wife when she gets home
    trigger:
      - platform: state
        entity_id: device_tracker.her_phone
        from: away
        to: home
    action:
      - service: script.she_is_home

  # Amazon Dash section
  - alias: Amazon Dash Button (Kleenex) pressed
    trigger:
      - platform: event
        event_type: dash_button_kleenex_pressed
    action:
      - service: script.dash_button_kleenex_pressed

  - alias: Amazon Dash Button (Durex) pressed
    trigger:
      - platform: event
        event_type: dash_button_durex_pressed
    action:
      - service: script.dash_button_durex_pressed
  # End of Amazon Dash section

  # Z-Wave section

  # - alias: Z-Wave network is complete
  #   trigger:
  #     platform: event
  #     event_type: zwave.network_complete
  #   action:
  #     - service: notify.pushover
  #       data:
  #         message: "Z-Wave network is complete"
  #
  # - alias: Z-Wave network is ready
  #   trigger:
  #     platform: event
  #     event_type: zwave.network_ready
  #   action:
  #     - service: notify.pushover
  #       data:
  #         message: "Z-Wave network is ready"
  #
  # - alias: Z-Wave network is starting
  #   trigger:
  #     platform: event
  #     event_type: zwave.network_start
  #   action:
  #     - service: notify.pushover
  #       data:
  #         message: "Z-Wave network is starting"
  #
  # - alias: Z-Wave network is stopping
  #   trigger:
  #     platform: event
  #     event_type: zwave.network_stop
  #   action:
  #     - service: notify.pushover
  #       data:
  #         message: "Z-Wave network is stopping"

  - alias: Z-Wave soft reset at 02:30
    trigger:
      platform: time
      after: '02:30:00'
    action:
      service: zwave.soft_reset

  - alias: Z-Wave network heal at 02:35
    trigger:
      platform: time
      after: '02:35:00'
    action:
      service: zwave.heal_network

  # End of Z-Wave section

# vim: set filetype=yaml et sw=2 ts=2 :
