homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  base_url: !secret base_url
  server_port: 8123
  api_password: !secret http_password
  ssl_certificate: !secret ssl_crt_path
  ssl_key: !secret ssl_key_path
  ip_ban_enabled: False
  login_attempts_threshold: 5
  trusted_networks: !include trusted_networks.yaml

conversation:
discovery:
frontend:
history:
logbook:
updater:

logger:
  default: info
  logs:
    homeassistant.components: info
    homeassistant.components.automation: debug
    homeassistant.components.apiai: debug
    requests.packages.urllib3.connectionpool: critical

automation: !include_dir_merge_list automations
apiai: !include apiai.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named groups
ifttt: !include ifttt.yaml
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
pilight: !include pilight.yaml
remote: !include remote.yaml
script: !include_dir_merge_named scripts
sensor: !include sensor.yaml
shell_command: !include shell_command.yaml
sun:
switch: !include switch.yaml
tts: !include tts.yaml
zone: !include zone.yaml
zoneminder: !include zoneminder.yaml

# vim: set filetype=yaml et sw=2 ts=2 :
