version: '3'

services:
  hass:
    image: homeassistant/home-assistant:latest
    container_name: hass
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    restart: always
    depends_on:
      - database
    network_mode: host
    cap_add:
      - NET_ADMIN  # Required for adding new routes
    extra_hosts:
      - "hass-db:172.92.92.92"
    volumes:
      - ./certs:/certs:ro
      - ./config/hass:/config
      - ./data/log:/log
      - ./scripts:/scripts:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pschmitt/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    devices:
      - /dev/zwave:/dev/ttyACM0
    healthcheck:
      test: "curl -Lf http://localhost:8123"

  caddy:
    image: mkozak/caddy-full:latest
    container_name: hass-caddy
    restart: always
    network_mode: host
    ports:
      # - 80:80/tcp
      - 443:443/tcp
    environment:
      - CADDYPATH=/caddy
    volumes:
      - ./data/caddy/certs:/caddy
      - ./config/caddy:/config:ro
    entrypoint: /usr/local/bin/caddy
    command: --conf /config/Caddyfile
    healthcheck:
      test: "curl -kLf https://localhost:443"

  database:
    image: postgres:9
    container_name: hass-db
    restart: always
    networks:
      database:
        ipv4_address: 172.92.92.92
    env_file:
      - postgres.env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    healthcheck:
      test: "su postgres -c pg_isready"

  influxdb:
    image: influxdb
    container_name: hass-influxdb
    networks:
      database:
        ipv4_address: 172.92.92.93
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    env_file:
      - influxdb.env

  grafana:
    image: grafana/grafana
    container_name: hass-grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000/tcp
    networks:
      database:
        ipv4_address: 172.92.92.94
    env_file:
      - grafana.env

  mqtt-proxy:
    image: pschmitt/stunnel
    container_name: mqtt-proxy
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./config/stunnel:/config:ro

  appdaemon:
    image: acockburn/appdaemon
    restart: always
    ports:
      - 5050:5050
    volumes:
      - ./config/appdaemon:/conf


networks:
  database:
    driver: bridge
    ipam:
      config:
        - subnet: 172.92.92.0/24

# vim: set ft=yaml et ts=2 sw=2 :
