version: '3'

services:
  hass:
    image: homeassistant/home-assistant:latest
    container_name: hass
    restart: unless-stopped
    depends_on:
      - database
    network_mode: host
    cap_add:
      - NET_ADMIN  # Required for adding new routes
    extra_hosts:
      - "hass-db:172.92.92.92"
    volumes:
      - ./certs:/certs:ro
      - ./config/hass:/config
      - ./data/log:/log
      - ./scripts:/scripts:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pschmitt/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    devices:
      - /dev/zwave:/dev/ttyACM0
    healthcheck:
      test: "curl -Lf http://localhost:8123"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.backend=home-assistant"
      - "traefik.docker.network=host"
      - "traefik.frontend.rule=Host:home.comreset.io"
      - "traefik.port=8123"

  database:
    image: postgres:9
    container_name: hass-db
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 172.92.92.92
    env_file:
      - postgres.env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    healthcheck:
      test: "su postgres -c pg_isready"

  influxdb:
    image: influxdb
    container_name: hass-influxdb
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 172.92.92.93
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    env_file:
      - influxdb.env

  grafana:
    image: grafana/grafana
    container_name: hass-grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000/tcp
    networks:
      backend:
        ipv4_address: 172.92.92.94
    env_file:
      - grafana.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:graphs.home.comreset.io"
      - "traefik.port=3000"

  mqtt-proxy:
    image: pschmitt/stunnel
    container_name: mqtt-proxy
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./config/stunnel:/config:ro

  appdaemon:
    image: acockburn/appdaemon
    restart: unless-stopped
    ports:
      - 5050:5050
    volumes:
      - ./config/appdaemon:/conf


networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.92.92.0/24

# vim: set ft=yaml et ts=2 sw=2 :
