binary_sensor:
  - platform: ping
    name: chromecast
    host: chromecast.lan


switch:
  - platform: pilight
    switches:
      Pilight Guest Room TV:
        on_code:
          protocol: pollin
          systemcode: 1
          unitcode: 1
          'on': 1
        off_code:
          protocol: pollin
          systemcode: 1
          unitcode: 1
          'off': 1

  - platform: template
    switches:
      guest_room_tv:
        friendly_name: "Guest Room TV"
        # value_template: "{{ is_state('switch.pilight_guest_room_tv', 'on') }}"
        value_template: "{{ is_state('binary_sensor.chromecast', 'on') }}"
        turn_on:
          # Turn on socket 1/3
          - service: switch.turn_on
            data:
              entity_id: switch.pilight_guest_room_tv
          # Turn on socket 2/3
          - service: switch.turn_on
            data:
              entity_id: switch.pilight_guest_room_tv
          # Turn on socket 3/3
          - service: switch.turn_on
            data:
              entity_id: switch.pilight_guest_room_tv
        turn_off:
          # Turn off socket 1/3
          - service: switch.turn_off
            data:
              entity_id: switch.pilight_guest_room_tv
          # Turn off socket 2/3
          - service: switch.turn_off
            data:
              entity_id: switch.pilight_guest_room_tv
          # Turn off socket 3/3
          - service: switch.turn_off
            data:
              entity_id: switch.pilight_guest_room_tv


script:
  turn_on_guest_room_tv:
    alias: "Turn on the guest room TV"
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.guest_room_tv

  turn_off_guest_room_tv:
    alias: "Turn off the guest room TV"
    sequence:
      - service: switch.turn_off
        data:
          entity_id: switch.guest_room_tv

  toggle_guest_room_tv:
    alias: "Toggle the guest room TV"
    sequence:
      service: switch.toggle
      data:
        entity_id: switch.guest_room_tv

# vim: set filetype=yaml et sw=2 ts=2 :
