binary_sensor:
  - platform: ping
    name: Sony PS3
    host: sony-ps3.lan

script:
  turn_on_sony_ps3:
    alias: "Turn on Sony PS3"
    sequence:
      - service: script.harmony_turn_on_sony_ps3

  turn_off_sony_ps3:
    alias: "Turn off Sony PS3"
    sequence:
      - condition: state
        entity_id: binary_sensor.sony_ps3
        to: 'on'
      - service: script.harmony_turn_off_sony_ps3

# vim: set filetype=yaml et sw=2 ts=2 :
