battery_check:
  module: batterywatcher
  class: BatteryWatcher
  threshold: 20
  # ignored_entities:
  #   - sensor.humidity_freezer
  #   - sensor.humidity_fridge
  #   - sensor.pressure_fridge
  #   - sensor.pressure_freezer


# vim: set ft=yaml et ts=2 sw=2 :
