group:
  kitchen:
    name: Kitchen
    view: yes
    icon: mdi:pot-mix
    entities:
      - camera.c2
      - light.kitchen_light
      - group.fridge
      - group.kitchen_window

  kitchen_window:
    name: Kitchen Window
    view: no
    entities:
      - cover.kitchen
      - binary_sensor.door_window_sensor_kitchen_window

# vim: set filetype=yaml et sw=2 ts=2 :
