group:
  living_room:
    name: Living Room
    view: yes
    icon: mdi:sofa
    entities:
      - group.living_room_media_player_scripts
      - switch.wall_socket
      - camera.c1
      - group.living_room_media_players
      - group.living_room_windows
      - group.living_room_lights

  living_room_lights:
    name: Living Room Lights
    view: no
    entities:
      - light.living_room_tv_light
      - light.living_room_table_light
      - light.gateway_light_34ce008d7aba
      - light.front_door
      - light.terrace
      - scene.living_room_normal
      - scene.living_room_dim

  living_room_windows:
    name: Living Room Windows
    view: no
    control: hidden
    entities:
      - binary_sensor.door_window_sensor_terrace_door
      - binary_sensor.door_window_sensor_living_room_window
      - cover.living_room_door
      - cover.living_room_table
      - cover.living_room_tv


  living_room_media_players:
    name: Media Players
    view: no
    entities:
      - media_player.tv
      - media_player.living_room_speaker

  living_room_media_player_scripts:
    name: TV Activities
    control: hidden
    view: no
    entities:
      - input_select.tv_activity
      - sensor.harmony_hub
      - script.amp_toggle
      - script.tv_activity_dolphin_emu
      - script.tv_activity_kodi
      - script.tv_activity_ps3
      - script.tv_activity_shield_tv
      - script.tv_activity_watch_tv
      - script.wake_nvidia_shield
      - script.harmony_power_off
      - script.turn_off_media_players

# vim: set filetype=yaml et sw=2 ts=2 :
