group:
  office:
    name: Office
    view: yes
    icon: mdi:anvil
    entities:
      - light.office
      - light.hue_office
      - light.yeelight_office
      - light.3d_printer_led
      - camera.hassistant
      - media_player.office_speaker
      - media_player.office_tv
      - group.office_windows
      - group.office_misc
      - group.office_sensors

  office_windows:
    name: Office Windows
    view: no
    entities:
      - binary_sensor.door_window_sensor_office_window_large
      - binary_sensor.door_window_sensor_office_window_small
      - cover.office

  office_misc:
    name: Misc.
    view: no
    entities:
      - switch.office_tv
      - sensor.power_consumption_nasteanas

  office_sensors:
    name: Office Sensors
    view: no
    entities:
      - binary_sensor.motion_sensor_office
      - sensor.motion_sensor_illumination_office

# vim: set filetype=yaml et sw=2 ts=2 :
