group:
  terrace:
    name: Terrace
    view: yes
    icon: mdi:tree
    entities:
      - group.weather_outdoor
      - group.all_plants
      - binary_sensor.plant_data_outdated
      - script.refresh_plant_data
      - camera.winpi
      - camera.weather
      - camera.centre_pompidou
      - camera.centre_congres
      - light.hue_terrace
      - script.smoke_break
      - group.terrace_doors
      - cover.living_room_door
      - cover.bedroom_door
      - input_datetime.smoke_break_duration
      - group.terrace_sensors

  terrace_sensors:
    name: Terrace Sensors
    view: no
    entities:
      - binary_sensor.plant_data_outdated
      - sensor.temperature_terrace
      - sensor.pressure_terrace
      - sensor.humidity_terrace
      - binary_sensor.motion_sensor_terrace
      - sensor.motion_sensor_illumination_terrace

# vim: set filetype=yaml et sw=2 ts=2 :
