switch:
  platform: template
  switches:
    modect:
      friendly_name: Motion Detection
      value_template: "{{ is_state('group.modect', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.modect
      turn_off:
        service: homeassistant.turn_off
        entity_id: group.modect


shell_command:
  cam_snap: /scripts/hass.sh snap {{ cam }} /tmp/snap_{{ cam }}.jpg
  snap_upload: !secret snap_upload
  snap_ldelete: "rm -f /tmp/snap_*.jpg"
  snap_rdelete: !secret snap_rdelete


script:
  snap_delete:
    alias: Delete snapshot
    sequence:
      - delay:
          minutes: 2
      - service: shell_command.snap_ldelete
      - service: shell_command.snap_rdelete

  snap_send:
    alias: Send a CCTV picture
    sequence:
      # Disable ev. deletion job
      - service: script.turn_off
        data:
          entity_id: script.snap_delete
      - service: camera.snapshot
        data_template:
          entity_id: "camera.{{ cam }}"
          filename: "/tmp/snap_{{ cam }}.jpg"
      - service_template: "script.snap_{{ cam }}"
      - service: shell_command.snap_upload
        data_template:
          cam: "{{ cam }}"
      - service: shell_command.fb_send_image
        data:
          filename: '/tmp/snap_{{ cam }}.jpg'
          target: !secret fb_my_phone_number
          token: !secret fb_page_token
      - service: notify.facebook
        data_template:
          target: !secret fb_my_phone_number
          message: Camera image
          data:
            attachment:
              type: image
              payload:
                url: !secret snap_public_url
      - service: script.snap_delete
        data_template:
          cam: "{{ cam }}"


group:
  cameras:
    name: Cameras
    view: yes
    icon: mdi:camera
    entities:
      - switch.modect
      - group.cameras_living_room
      - group.cameras_misc
      - group.cameras_office
      - group.cameras_terrace
      - group.cameras_front_door

  cameras_front_door:
    name: Front door cameras
    view: no
    entities:
      - camera.front_door
      - camera.doorpi

  cameras_terrace:
    name: Terrace Cameras
    view: no
    entities:
      - camera.terrace

  cameras_living_room:
    name: Living Room Cameras
    view: no
    entities:
      - camera.c1

  cameras_office:
    name: Office Cameras
    view: no
    entities:
      - camera.hassistant

  cameras_misc:
    name: Other Cameras
    view: no
    entities:
      - camera.c2
      - camera.winpi
      - camera.doorpi
      - camera.front_door
      - camera.hallway

  cctv:
    name: CCTV
    view: no
    icon: mdi:camera-enhance
    entities:
      - binary_sensor.bathroom_presence
      - binary_sensor.hallway_presence
      - binary_sensor.kitchen_presence
      - binary_sensor.toilet_presence
      - group.c1
      - group.c2
      - group.raspicam_doorpi
      - group.raspicam_hassistant
      - group.raspicam_winpi
      - group.modect

  modect:
    name: Motion detection
    entities:
      - binary_sensor.bathroom_presence
      - binary_sensor.hallway_presence
      - binary_sensor.kitchen_presence
      - binary_sensor.toilet_presence
      - switch.foscam_c1_state
      - switch.foscam_c2_state
      - switch.doorpi_state
      - switch.hassistant_state
      - switch.winpi_state
      - switch.foscam_c1_modect
      - switch.foscam_c2_modect
      - switch.foscam_c1_sodect
      - switch.foscam_c2_sodect


homeassistant:
  customize:
    # Switches
    switch.modect:
      icon: mdi:camera-enhance

# vim: set filetype=yaml et sw=2 ts=2 :
