camera:
  - platform: generic
    name: Weather
    still_image_url: https://www.yr.no/place/France/Lorraine/Metz/meteogram.svg
    content_type: 'image/svg+xml'

  - platform: generic
    name: centre_pompidou
    still_image_url: "http://metz.fr/pages/webcams/images/amphitheatre.jpg?{{ as_timestamp(now()) * 1000 }}"
    headers:
      referer: "http://metz.fr/pages/webcams/quartier_amphitheatre.php"

  - platform: generic
    name: centre_congres
    still_image_url: http://www.monsuividechantier.com/image_live.php?cam=61b090972bd1a396a83a8202aecbf793&1513176422947

# vim: set filetype=yaml et sw=2 ts=2 :
