alarm_control_panel:
  platform: manual
  code: !secret alarm_code
  pending_time: 0
  trigger_time: 20
  delay_time: 30
  disarm_after_trigger: false


automation:
  - alias: Arm alarm when we are away
    initial_state: true
    trigger:
      - platform: state
        entity_id: group.main_mobile_devices
        to: not_home
        for:
          minutes: 3
    action:
      - service: script.alarm_arm_away

  - alias: Door/Window sensor triggered
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_window_sensor_158d00016572aa
          - binary_sensor.door_window_sensor_158d00016d7083
          - binary_sensor.door_window_sensor_158d0001a1eb5b
          - binary_sensor.door_window_sensor_158d0001a1ec56
          - binary_sensor.door_window_sensor_158d0001de639e
          - binary_sensor.door_window_sensor_158d0001de7941
          - binary_sensor.door_window_sensor_158d0001de8c01
          - binary_sensor.door_window_sensor_158d0001de8caa
          - binary_sensor.door_window_sensor_158d0001de8cb8
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
      - service: notify.get_to_me
        data_template:
          message: >
            {{ trigger.to_state.attributes.friendly_name }}
            has been opened

  - alias: Motion Detector triggered
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.toilet_presence
          - binary_sensor.hallway_presence
          - binary_sensor.kitchen_presence
          - binary_sensor.bathroom_presence
          - binary_sensor.motion_sensor_158d000224f5b8
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
      - service: notify.get_to_me
        data_template:
          message: >
            {{ trigger.to_state.attributes.friendly_name }}:
            Motion has been detected

  - alias: Trigger an alert when zoneminder picks up a new event
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.c1_events
      - platform: state
        entity_id: sensor.c2_events
      - platform: state
        entity_id: sensor.doorpi_events
      - platform: state
        entity_id: sensor.winpi_events
      - platform: state
        entity_id: sensor.hassistant_events
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: armed_away
        - condition: template
          value_template: >
            {% if trigger.from_state.state == 'unknown' %}
              false
            {% else %}
              {{ trigger.from_state.state | int < trigger.to_state.state | int }}
            {% endif %}
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
      - service: notify.get_to_me
        data_template:
          message: >
            ALERT: Camera {{ trigger.to_state.attributes.friendly_name | replace("Events", "", 1) }} has detected motion

  - alias: Notify when a new platform has been discovered
    initial_state: true
    trigger:
      - platform: event
        event_type: platform
    action:
      service: notify.smsr
      data_template:
        message: "Home Assistant has discovered a new device (platform): {{ service }}.{{ discovered }}"
        target: me

  - alias: Away armed
    initial_state: true
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: armed_away
    action:
      - service: script.alarm_armed_away

  - alias: Alarm disarmed
    initial_state: true
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: disarmed
    action:
      - service: script.alarm_disarmed

  - alias: Alarm has been triggered
    initial_state: true
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: triggered
    # condition:
    #     - condition: state
    #       entity_id: alarm_control_panel.ha_alarm
    #       state: not_disarmed
    action:
      - service: script.alarm_triggered

  - alias: Someone is home and the alarm is on
    initial_state: true
    trigger:
      - platform: state
        entity_id: group.main_mobile_devices
        to: home
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      - service: notify.html5
        data_template:
          message: "{% if trigger.entity_id == 'group.pschmitt_location' %}You are{% else %}Marine is{% endif %} home and the alarm is on."
          data:
            tag: "homecoming-alarm-on"
            actions:
              - action: disable_alarm
                # mdi:bell-off
                icon: https://materialdesignicons.com/api/download/69686D8F-75FE-4091-9061-88DB64D95C01/000000/1/FFFFFF/0/48
                title: Disable alarm
              - action: alarm-homeinvasion
                # mdi:stethoscope
                icon: https://materialdesignicons.com/api/download/641202BA-294A-4A0F-851D-FB83FEC9D7EE/000000/1/FFFFFF/0/48
                title: Kidnappers are here

  - alias: Alarm disarm requested
    initial_state: true
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: disable_alarm
    action:
      - service: script.alarm_disarm

  - alias: Kidnapping mode requested
    initial_state: true
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: alarm-homeinvasion
    action:
      - service: script.call_for_help


script:
  alarm_disarm:
    alias: 'Disable alarm'
    sequence:
      - service: alarm_control_panel.alarm_disarm
        data:
          code: !secret alarm_code

  call_for_help:
    alias: 'Call for help'
    sequence:
      - service: notify.html5
        data:
          message: "The police is on its way"

  alarm_arm_away:
    alias: 'Activate away alarm'
    sequence:
      - service: notify.smsr
        data:
          message: "Home Assistant: Everybody left. Arming away."
          target: me
      - service: alarm_control_panel.alarm_arm_away
        data:
          code: !secret alarm_code
      - service: script.lock_door

  alarm_armed_away:
    alias: 'Away alarm activated'
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: group.modect
      - service: notify.smsr
        data:
          message: "Home Assistant: Alarm armed (away)"
          target: me

  alarm_disarmed:
    alias: 'Alarm disarmed'
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id: group.modect
      - service: notify.smsr
        data:
          message: "Home Assistant: Alarm disarmed"
          target: me

  alarm_triggered:
    alias: 'Alarm triggered'
    sequence:
      - service: script.tts_say
        data:
          message: "Alarm triggered"
          language: "en"
      - event: LOGBOOK_ENTRY
        event_data:
          name: Alarm
          message: has been triggered
          domain: alarm

  alarm_arm_if_away:
    alias: 'Arm alarm if we are away'
    sequence:
      - condition: state
        entity_id: group.main_mobile_devices
        state: 'not_home'
      - service: script.alarm_arm_away

  alarm_disarm_if_home:
    alias: 'Disarm alarm if we are home'
    sequence:
      - condition: state
        entity_id: group.main_mobile_devices
        state: 'home'
      - service: script.alarm_disarm
      - service: script.alarm_disarmed


homeassistant:
  customize:
    script.alarm_disarmed:
      icon: mdi:lock-open
    script.alarm_arm_away:
      icon: mdi:lock
    script.alarm_armed_away:
      icon: mdi:lock-plus
    script.alarm_triggered:
      icon: mdi:alert-circle

# vim: set filetype=yaml et sw=2 ts=2 :
