xiaomi_aqara:
  interface: !secret lan_ipv4_addr
  gateways:
    - mac: !secret mi_gw_mac
      key: !secret mi_gw_api_key


light:
  - platform: yeelight
    devices:
      "yeelight-office.lan":
        name: YeeLight Office


sensor:
  - platform: template
    sensors:
      aqara_front_door_battery:
        friendly_name: "Aqara Front Door Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d00016d7083.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_fridge_door_battery:
        friendly_name: "Aqara Fridge Door Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001a1eb5b.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_terrace_door_battery:
        friendly_name: "Aqara Terrace Door Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001a1ec56.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_terrace_door_bedroom_battery:
        friendly_name: "Aqara Terrace Door (Bedroom) Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d00016572aa.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_bedroom_window_battery:
        friendly_name: "Aqara Bedroom Window Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001de639e.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_living_room_window_battery:
        friendly_name: "Aqara Living Room Window Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001de8cb8.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_office_window_small_battery:
        friendly_name: "Aqara Office Window (Small) Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001de8caa.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_office_window_large_battery:
        friendly_name: "Aqara Office Window (Large) Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001de7941.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_kitchen_window_battery:
        friendly_name: "Aqara Kitchen Window Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001de8c01.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_fridge_temp_battery:
        friendly_name: "Aqara Fridge Temperature Sensor Battery"
        value_template: '{{ states.sensor.temperature_158d0001d6f4da.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_freezer_temp_battery:
        friendly_name: "Aqara Freezer Temperature Sensor Battery"
        value_template: '{{ states.sensor.temperature_158d0001d6f4e5.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_water_leak_bathroom_battery:
        friendly_name: "Aqara Bathroom Water Leak Sensor Battery"
        value_template: '{{ states.binary_sensor.water_leak_sensor_158d0001d7668e.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_water_leak_kitchen_battery:
        friendly_name: "Aqara Kitchen Water Leak Sensor Battery"
        value_template: '{{ states.binary_sensor.water_leak_sensor_158d0001df1cc3.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_front_door_motion_sensor_battery:
        friendly_name: "Aqara Front Door Motion Sensor Battery"
        value_template: '{{ states.binary_sensor.motion_sensor_158d000224f5b8.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_button_battery:
        friendly_name: "Aqara button battery"
        value_template: '{{ states.binary_sensor.switch_158d0002132e08.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_wall_switch_office_battery:
        friendly_name: "Aqara wall switch office battery"
        value_template: '{{ states.binary_sensor.wall_switch_both_158d0001e0f920.attributes.battery_level }}'
        unit_of_measurement: '%'


group:
  fridge:
    name: Fridge
    view: no
    icon: mdi:fridge
    entities:
      - binary_sensor.door_window_sensor_158d0001a1eb5b
      - sensor.temperature_158d0001d6f4da
      - sensor.temperature_158d0001d6f4e5
      - sensor.humidity_158d0001d6f4da
      - sensor.humidity_158d0001d6f4e5
      - sensor.pressure_158d0001d6f4da
      - sensor.pressure_158d0001d6f4e5

  terrace_doors:
    name: Terrace Doors
    view: no
    icon: mdi:door
    entities:
      - binary_sensor.door_window_sensor_158d0001a1ec56
      - binary_sensor.door_window_sensor_158d00016572aa

  windows:
    name: Windows
    view: no
    icon: mdi:glassdoor
    entities:
      - binary_sensor.door_window_sensor_158d00016572aa
      - binary_sensor.door_window_sensor_158d00016d7083
      - binary_sensor.door_window_sensor_158d0001a1ec56
      - binary_sensor.door_window_sensor_158d0001de639e
      - binary_sensor.door_window_sensor_158d0001de7941
      - binary_sensor.door_window_sensor_158d0001de8c01
      - binary_sensor.door_window_sensor_158d0001de8caa
      - binary_sensor.door_window_sensor_158d0001de8cb8

  aqara_buttons:
    name: Aqara buttons
    view: no
    icon: mdi:button
    entities:
      - binary_sensor.wall_switch_both_158d0001e0f920
      - binary_sensor.switch_158d0002132e08


automation:
  - alias: Turn on the terrace light when door opened during nighttime
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a1ec56
        to: 'on'
    condition:
      condition: sun
      after: sunset
      before_offset: "-1:00:00"
    action:
      - service: script.smoke_break
      - service: cover.open_cover
        data:
          entity_id: cover.living_room_door

  - alias: Alert when the fridge has been open for 2 min
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a1eb5b
        to: 'on'
        for:
          minutes: 2
    action:
      - service: notify.html5
        data:
          message: "The fridge has been opened for at least 2 minutes"
          data:
            tag: 'fridge-open'

  - alias: Alert when fridge temperature is above 15C
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_158d0001d6f4da
        above: 15
    action:
      - service: notify.html5
        data_template:
          message: 'The fridge temperature is at {{ trigger.to_state.state }}C!'
          data:
            tag: 'fridge-temp-high'

  - alias: Alert when freezer temperature is above -10C
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_158d0001d6f4e5
        above: -10
    action:
      - service: notify.html5
        data_template:
          message: 'The freezer temperature is at {{ trigger.to_state.state }}C!'
          data:
            tag: 'freezer-temp-high'

  - alias: Alert when water leak detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: >-
          binary_sensor.water_leak_sensor_158d0001d7668e,
          binary_sensor.water_leak_sensor_158d0001df1cc3
        to: 'on'
    action:
      - service: notify.html5
        data_template:
          message: 'Water leak detected at {{ trigger.to_state.attributes.friendly_name }}!'
          data:
            tag: 'water-leak-{{ trigger.to_state.entity_id }}'

  - alias: React to single button press on aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d0001e0f920
        click_type: single
    action:
      - service: light.toggle
        entity_id: light.yeelight_office

  - alias: React to single (right) button press on aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d0001e0f920
        click_type: single
    action:
      - service: light.toggle
        entity_id: light.office

  - alias: React to single (both) button press on aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_both_158d0001e0f920
        click_type: both
    action:
      - service: light.turn_off
        entity_id: light.office, light.yeelight_office
      - service: cover.close_cover
        entity_id: cover.office

  - alias: React to single button press on aqara button
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0002132e08
        click_type: single
    action:
      service: script.bedtime

  - alias: React to double button press on aqara button
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0002132e08
        click_type: double
    action:
      service: script.all_off
      # - service: notify.html5
      #   data:
      #     message: 'Mi button DOUBLE pressed'

  - alias: Turn on front door light when motion is detected on the front door
    initial_state: True
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d000224f5b8
      to: 'on'
    action:
      service: light.turn_on
      entity_id: light.front_door
      data:
        brightness: 150
        color_name: white


homeassistant:
  customize:
    light.gateway_light_34ce008d7aba:
      friendly_name: Mi Gateway Light
    sensor.illumination_34ce008d7aba:
      friendly_name: Mi Gateway Light Level
    binary_sensor.door_window_sensor_158d0001a1eb5b:
      friendly_name: Fridge Door
      device_class: door
    binary_sensor.door_window_sensor_158d0001a1ec56:
      friendly_name: Terrace Door
      device_class: door
    binary_sensor.door_window_sensor_158d0001de8c01:
      friendly_name: Kitchen Window
      device_class: window
    binary_sensor.door_window_sensor_158d0001de7941:
      friendly_name: "Office Window (large)"
      device_class: window
    binary_sensor.door_window_sensor_158d0001de8caa:
      friendly_name: "Office Window (small)"
      device_class: window
    binary_sensor.door_window_sensor_158d0001de639e:
      friendly_name: "Bedroom Window"
      device_class: window
    binary_sensor.door_window_sensor_158d00016572aa:
      friendly_name: "Terrace Door (Bedroom)"
      device_class: door
    binary_sensor.door_window_sensor_158d00016d7083:
      friendly_name: "Front Door"
      device_class: door
    binary_sensor.water_leak_sensor_158d0001d7668e:
      friendly_name: "Bathroom Sink"
    binary_sensor.water_leak_sensor_158d0001df1cc3:
      friendly_name: "Kitchen Sink"
    binary_sensor.door_window_sensor_158d0001de8cb8:
      friendly_name: "Living Room Window"
      device_class: window
    binary_sensor.motion_sensor_158d000224f5b8:
      friendly_name: "Front door motion sensor"
      # device_class: motion
    sensor.humidity_158d0001d6f4da:
      friendly_name: Fridge Humidity
      icon: water-percent
    sensor.pressure_158d0001d6f4da:
      friendly_name: Fridge Pressure
      icon: mdi:arrow-collapse-all
    sensor.temperature_158d0001d6f4da:
      friendly_name: Fridge Temperature
    sensor.humidity_158d0001d6f4e5:
      friendly_name: Freezer Humidity
      icon: mdi:water-percent
    sensor.pressure_158d0001d6f4e5:
      friendly_name: Freezer Pressure
      icon: mdi:arrow-collapse-all
    sensor.temperature_158d0001d6f4e5:
      friendly_name: Freezer Temperature

# vim: set filetype=yaml et sw=2 ts=2 :
