xiaomi_aqara:
  interface: !secret lan_ipv4_addr
  gateways:
    - mac: !secret mi_gw_mac
      key: !secret mi_gw_api_key


light:
  - platform: yeelight
    devices:
      "yeelight-office.lan":
        name: YeeLight Office


sensor:
  - platform: template
    sensors:
      aqara_front_door_battery:
        friendly_name: "Aqara Front Door Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_front_door.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_fridge_door_battery:
        friendly_name: "Aqara Fridge Door Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_fridge_door.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_terrace_door_battery:
        friendly_name: "Aqara Terrace Door Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_terrace_door.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_terrace_door_bedroom_battery:
        friendly_name: "Aqara Terrace Door (Bedroom) Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_bedroom_terrace_door.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_bedroom_window_battery:
        friendly_name: "Aqara Bedroom Window Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_bedroom_window.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_living_room_window_battery:
        friendly_name: "Aqara Living Room Window Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_living_room_window.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_office_window_small_battery:
        friendly_name: "Aqara Office Window (Small) Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_office_window_small.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_office_window_large_battery:
        friendly_name: "Aqara Office Window (Large) Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_office_window_large.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_kitchen_window_battery:
        friendly_name: "Aqara Kitchen Window Sensor Battery"
        value_template: '{{ states.binary_sensor.door_window_sensor_kitchen_window.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_fridge_temp_battery:
        friendly_name: "Aqara Fridge Temperature Sensor Battery"
        value_template: '{{ states.sensor.temperature_fridge.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_freezer_temp_battery:
        friendly_name: "Aqara Freezer Temperature Sensor Battery"
        value_template: '{{ states.sensor.temperature_freezer.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_water_leak_bathroom_battery:
        friendly_name: "Aqara Bathroom Water Leak Sensor Battery"
        value_template: '{{ states.binary_sensor.water_leak_sensor_bathroom.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_water_leak_kitchen_battery:
        friendly_name: "Aqara Kitchen Water Leak Sensor Battery"
        value_template: '{{ states.binary_sensor.water_leak_sensor_kitchen.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_front_door_motion_sensor_battery:
        friendly_name: "Aqara Front Door Motion Sensor Battery"
        value_template: '{{ states.binary_sensor.motion_sensor_front_door.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_button_battery:
        friendly_name: "Aqara button battery"
        value_template: '{{ states.binary_sensor.switch_158d0002132e08.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_wall_switch_office_battery:
        friendly_name: "Aqara wall switch office battery"
        value_template: '{{ states.binary_sensor.wall_switch_both_158d0001e0f920.attributes.battery_level }}'
        unit_of_measurement: '%'
      aqara_wall_switch_bedroom_battery:
        friendly_name: "Aqara wall switch bedroom battery"
        value_template: '{{ states.binary_sensor.wall_switch_both_158d00016404f4.attributes.battery_level }}'
        unit_of_measurement: '%'


group:
  fridge:
    name: Fridge
    view: no
    icon: mdi:fridge
    control: hidden
    entities:
      - binary_sensor.door_window_sensor_fridge_door
      - sensor.temperature_fridge
      - sensor.temperature_freezer
      - sensor.humidity_fridge
      - sensor.humidity_freezer
      - sensor.pressure_fridge
      - sensor.pressure_freezer

  terrace_doors:
    name: Terrace Doors
    view: no
    icon: mdi:door
    entities:
      - binary_sensor.door_window_sensor_terrace_door
      - binary_sensor.door_window_sensor_bedroom_terrace_door

  windows:
    name: Windows
    view: no
    icon: mdi:glassdoor
    entities:
      - binary_sensor.door_window_sensor_bedroom_terrace_door
      - binary_sensor.door_window_sensor_front_door
      - binary_sensor.door_window_sensor_terrace_door
      - binary_sensor.door_window_sensor_bedroom_window
      - binary_sensor.door_window_sensor_office_window_large
      - binary_sensor.door_window_sensor_kitchen_window
      - binary_sensor.door_window_sensor_office_window_small
      - binary_sensor.door_window_sensor_living_room_window

  aqara_buttons:
    name: Aqara buttons
    view: no
    icon: mdi:button
    entities:
      - binary_sensor.wall_switch_both_158d0001e0f920
      - binary_sensor.switch_158d0002132e08


automation:
  - alias: Turn on the terrace light when door opened during nighttime
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_terrace_door
        to: 'on'
    condition:
      condition: sun
      after: sunset
      before_offset: "-1:00:00"
    action:
      - service: script.smoke_break
      - service: cover.open_cover
        data:
          entity_id: cover.living_room_door

  - alias: Alert when the fridge has been open for 2 min
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_fridge_door
        to: 'on'
        for:
          minutes: 2
    action:
      - service: notify.html5
        data:
          message: "The fridge has been opened for at least 2 minutes"
          data:
            tag: 'fridge-open'

  - alias: Alert when fridge temperature is above 15C
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_fridge
        above: 15
    action:
      - service: notify.html5
        data_template:
          message: 'The fridge temperature is at {{ trigger.to_state.state }}C!'
          data:
            tag: 'fridge-temp-high'

  - alias: Alert when freezer temperature is above -10C
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_freezer
        above: -10
    action:
      - service: notify.html5
        data_template:
          message: 'The freezer temperature is at {{ trigger.to_state.state }}C!'
          data:
            tag: 'freezer-temp-high'

  - alias: Alert when water leak detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: >-
          binary_sensor.water_leak_sensor_bathroom,
          binary_sensor.water_leak_sensor_kitchen
        to: 'on'
    action:
      - service: notify.html5
        data_template:
          message: 'Water leak detected at {{ trigger.to_state.attributes.friendly_name }}!'
          data:
            tag: 'water-leak-{{ trigger.to_state.entity_id }}'

  - alias: React to single button press on office aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d0001e0f920
        click_type: single
    action:
      - service: light.toggle
        entity_id: light.yeelight_office

  - alias: React to single (right) button press on office aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d0001e0f920
        click_type: single
    action:
      - service: light.toggle
        entity_id: light.office

  - alias: React to single (both) button press on office aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_both_158d0001e0f920
        click_type: both
    action:
      - service: light.turn_off
        entity_id: light.office, light.yeelight_office
      - service: cover.close_cover
        entity_id: cover.office

  - alias: React to single button press on bedroom aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00016404f4
        click_type: single
    action:
      - service: notify.zanzito_tts
        data:
          message: "left"
      - service: script.bedtime

  - alias: React to single (right) button press on bedroom aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d00016404f4
        click_type: single
    action:
      - service: notify.zanzito_tts
        data:
          message: "right"
      # - service: script.all_off
      # - service: script.lock_door

  - alias: React to single (both) button press on bedroom aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_both_158d00016404f4
        click_type: both
    action:
      - service: notify.zanzito_tts
        data:
          message: "both"
      - service: script.all_off
      - service: script.lock_door

  - alias: React to single button press on aqara button
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0002132e08
        click_type: single
    action:
      service: script.bedtime

  - alias: React to double button press on aqara button
    initial_state: true
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0002132e08
        click_type: double
    action:
      service: script.all_off
      # - service: notify.html5
      #   data:
      #     message: 'Mi button DOUBLE pressed'

  - alias: Turn on front door light when motion is detected on the front door
    initial_state: True
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_front_door
      to: 'on'
    action:
      service: light.turn_on
      entity_id: light.front_door
      data:
        brightness: 150
        color_name: white


homeassistant:
  customize:
    light.gateway_light_34ce008d7aba:
      friendly_name: Mi Gateway Light
    sensor.illumination_34ce008d7aba:
      friendly_name: Mi Gateway Light Level
    binary_sensor.door_window_sensor_fridge_door:
      friendly_name: Fridge Door
      device_class: door
    binary_sensor.door_window_sensor_terrace_door:
      friendly_name: Terrace Door
      device_class: door
    binary_sensor.door_window_sensor_kitchen_window:
      friendly_name: Kitchen Window
      device_class: window
    binary_sensor.door_window_sensor_office_window_large:
      friendly_name: "Office Window (large)"
      device_class: window
    binary_sensor.door_window_sensor_office_window_small:
      friendly_name: "Office Window (small)"
      device_class: window
    binary_sensor.door_window_sensor_bedroom_window:
      friendly_name: "Bedroom Window"
      device_class: window
    binary_sensor.door_window_sensor_bedroom_terrace_door:
      friendly_name: "Terrace Door (Bedroom)"
      device_class: door
    binary_sensor.door_window_sensor_front_door:
      friendly_name: "Front Door"
      device_class: door
    binary_sensor.water_leak_sensor_bathroom:
      friendly_name: "Bathroom Sink"
    binary_sensor.water_leak_sensor_kitchen:
      friendly_name: "Kitchen Sink"
    binary_sensor.door_window_sensor_living_room_window:
      friendly_name: "Living Room Window"
      device_class: window
    binary_sensor.motion_sensor_front_door:
      friendly_name: "Front door motion sensor"
      # device_class: motion
    binary_sensor.wall_switch_left_158d00016404f4:
      friendly_name: "Bedroom wall switch left"
    binary_sensor.wall_switch_right_158d00016404f4:
      friendly_name: "Bedroom wall switch right"
    binary_sensor.wall_switch_both_158d00016404f4:
      friendly_name: "Bedroom wall switch both"
    binary_sensor.wall_switch_left_158d0001e0f920:
      friendly_name: "Office wall switch left"
    binary_sensor.wall_switch_right_158d0001e0f920:
      friendly_name: "Office wall switch right"
    binary_sensor.wall_switch_both_158d0001e0f920:
      friendly_name: "Office wall switch both"
    sensor.humidity_fridge:
      friendly_name: Fridge Humidity
      icon: water-percent
    sensor.pressure_fridge:
      friendly_name: Fridge Pressure
      icon: mdi:arrow-collapse-all
    sensor.temperature_fridge:
      friendly_name: Fridge Temperature
    sensor.humidity_freezer:
      friendly_name: Freezer Humidity
      icon: mdi:water-percent
    sensor.pressure_freezer:
      friendly_name: Freezer Pressure
      icon: mdi:arrow-collapse-all
    sensor.temperature_freezer:
      friendly_name: Freezer Temperature

# vim: set filetype=yaml et sw=2 ts=2 :
