automation:
  - alias: "Low battery notifications"
    initial_state: true
    trigger:
      platform: event
      event_type: battery_low
    action:
      service: notify.html5
      data_template:
        message: >
          Battery low on device: {{ trigger.event.data.entity_id }}
          ({{ trigger.event.data.battery_level }})
        data:
          tag: "battery-low-{{ trigger.event.data.entity_id }}"

  - alias: "Battery okay notifications"
    initial_state: true
    trigger:
      platform: event
      event_type: battery_okay
    action:
      service: notify.html5
      data_template:
        message: "Battery okay on device: {{ trigger.event.data.entity_id }}"
        data:
          tag: "battery-okay-{{ trigger.event.data.entity_id }}"


# vim: set filetype=yaml et sw=2 ts=2 :
