camera:
  # - platform: zoneminder

  - platform: foscam
    name: C1
    ip: !secret foscam_c1_hostname
    username: !secret foscam_c1_username
    password: !secret foscam_c1_password

  - platform: foscam
    name: C2
    ip: !secret foscam_c2_hostname
    username: !secret foscam_c2_username
    password: !secret foscam_c2_password

  - platform: mjpeg
    name: doorpi
    mjpeg_url: http://doorpi.lan:8000/stream.mjpg
    authentication: basic
    username: !secret cam_doorpi_username
    password: !secret cam_doorpi_password

  - platform: mjpeg
    name: hassistant
    mjpeg_url: http://hassistant.lan:8000/stream.mjpg
    authentication: basic
    username: !secret cam_hassistant_username
    password: !secret cam_hassistant_password

  - platform: mjpeg
    name: winpi
    mjpeg_url: http://winpi.lan:8000/stream.mjpg
    authentication: basic
    username: !secret cam_winpi_username
    password: !secret cam_winpi_password


zoneminder:
  host: nasteanas.lan:10080
  path: /zm/
  ssl: false
  # username: !secret zm_username
  # password: !secret zm_password


sensor:
  - platform: zoneminder


switch:
  - platform: zoneminder
    command_on: Modect
    command_off: Monitor

  - platform: template
    switches:
      modect:
        friendly_name: Motion Detection
        value_template: "{{ is_state('group.modect', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: group.modect
        turn_off:
          service: homeassistant.turn_off
          entity_id: group.modect

  - platform: command_line
    switches:
      c1_ir:
        command_on: /scripts/foscam.sh c1 ir on
        command_off: /scripts/foscam.sh c1 ir off
        command_state: /scripts/foscam.sh c1 ir state
        friendly_name: "C1 Night Mode"
      c2_ir:
        command_on: /scripts/foscam.sh c2 ir on
        command_off: /scripts/foscam.sh c2 ir off
        command_state: /scripts/foscam.sh c2 ir state
        friendly_name: "C2 Night Mode"
      c1_modect:
        command_on: /scripts/foscam.sh c1 modect on
        command_off: /scripts/foscam.sh c1 modect off
        command_state: /scripts/foscam.sh c1 modect state
        friendly_name: "C1 Foscam Motion Detection"
      c2_modect:
        command_on: /scripts/foscam.sh c2 modect on
        command_off: /scripts/foscam.sh c2 modect off
        command_state: /scripts/foscam.sh c2 modect state
        friendly_name: "C2 Foscam Motion Detection"
      c1_sodect:
        command_on: /scripts/foscam.sh c1 sodect on
        command_off: /scripts/foscam.sh c1 sodect off
        command_state: /scripts/foscam.sh c1 sodect state
        friendly_name: "C1 Foscam Audio Detection"
      c2_sodect:
        command_on: /scripts/foscam.sh c2 sodect on
        command_off: /scripts/foscam.sh c2 sodect off
        command_state: /scripts/foscam.sh c2 sodect state
        friendly_name: "C2 Foscam Audio Detection"


shell_command:
  cam_snap: /scripts/hass.sh snap {{ cam }} /tmp/snap_{{ cam }}.jpg
  snap_upload: !secret snap_upload
  snap_ldelete: "rm -f /tmp/snap_*.jpg"
  snap_rdelete: !secret snap_rdelete


script:
  snap_c1:
    alias: Grab a picture from C1
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: c1

  snap_c2:
    alias: Grab a picture from C2
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: c2

  snap_doorpi:
    alias: Grab a picture from doorpi
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: doorpi

  snap_hassistant:
    alias: Grab a picture from hassistant
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: hassistant

  snap_winpi:
    alias: Grab a picture from winpi
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: winpi

  snap_delete:
    alias: Delete snapshot
    sequence:
      - delay:
          minutes: 2
      - service: shell_command.snap_ldelete
        data_template:
          cam: "{{ cam }}"
      - service: shell_command.snap_rdelete
        data_template:
          cam: "{{ cam }}"

  snap_send:
    alias: Send a CCTV picture
    sequence:
      # Disable ev. deletion job
      - service: script.turn_off
        data:
          entity_id: script.snap_delete
      - service_template: "script.snap_{{ cam }}"
      - service: shell_command.snap_upload
        data_template:
          cam: "{{ cam }}"
      - service: notify.facebook_me
        data_template:
          message: Camera image
          data:
            attachment:
              type: image
              payload:
                url: !secret snap_public_url
      - service: script.snap_delete
        data_template:
          cam: "{{ cam }}"


group:
  cameras:
    name: Cameras
    view: yes
    icon: mdi:camera
    entities:
      - switch.modect
      - group.cameras_living_room
      - group.cameras_misc
      - group.cameras_office

  cameras_living_room:
    name: Living Room Cameras
    view: no
    entities:
      - camera.c1

  cameras_office:
    name: Office Cameras
    view: no
    entities:
      - camera.doorpi
      - camera.hassistant

  cameras_misc:
    name: Other Cameras
    view: no
    entities:
      - camera.c2
      - camera.winpi

  cctv:
    name: CCTV
    view: no
    icon: mdi:camera-enhance
    entities:
      - binary_sensor.bathroom_presence
      - binary_sensor.hallway_presence
      - binary_sensor.kitchen_presence
      - binary_sensor.toilet_presence
      - group.c1
      - group.c2
      - group.raspicam_doorpi
      - group.raspicam_hassistant
      - group.raspicam_winpi
      - group.modect


  c1:
    name: Foscam C1
    control: hidden
    entities:
      - camera.c1
      - switch.c1_ir
      - switch.c1_modect
      - switch.c1_sodect
      - switch.foscam_c1_state
      - sensor.foscam_c1_events
      - sensor.c1_status

  c2:
    name: Foscam C2
    control: hidden
    entities:
      - camera.c2
      - switch.c2_ir
      - switch.c2_modect
      - switch.c2_sodect
      - switch.foscam_c2_state
      - sensor.foscam_c2_events
      - sensor.c2_status

  modect:
    name: Motion detection
    entities:
      - binary_sensor.bathroom_presence
      - binary_sensor.hallway_presence
      - binary_sensor.kitchen_presence
      - binary_sensor.toilet_presence
      - switch.foscam_c1_state
      - switch.foscam_c2_state
      - switch.doorpi_state
      - switch.hassistant_state
      - switch.winpi_state
      - switch.foscam_c1_modect
      - switch.foscam_c2_modect
      - switch.foscam_c1_sodect
      - switch.foscam_c2_sodect

  raspicam_doorpi:
    name: Raspberry Pi Camera (doorpi)
    control: hidden
    entities:
      - camera.doorpi
      - switch.doorpi_state
      - sensor.doorpi_status
      - sensor.doorpi_events

  raspicam_hassistant:
    name: Raspberry Pi Camera (hassistant)
    control: hidden
    entities:
      - camera.hassistant
      - switch.hassistant_state
      - sensor.hassistant_status
      - sensor.hassistant_events

  raspicam_winpi:
    name: Raspberry Pi Camera (winpi)
    control: hidden
    entities:
      - camera.winpi
      - switch.winpi_state
      - sensor.winpi_status
      - sensor.winpi_events


homeassistant:
  customize:
    # Switches
    switch.doorpi_state:
      google_assistant: false
    switch.foscam_c1_state:
      google_assistant: false
    switch.foscam_c2_state:
      google_assistant: false
    switch.hassistant_state:
      google_assistant: false
    switch.winpi_state:
      google_assistant: false
    switch.c1_ir:
      icon: mdi:weather-night
    switch.c2_ir:
      icon: mdi:weather-night
    switch.c1_modect:
      icon: mdi:run
    switch.c2_modect:
      icon: mdi:run
    switch.c1_sodect:
      icon: mdi:surround-sound
    switch.c2_sodect:
      icon: mdi:surround-sound
    switch.modect:
      icon: mdi:camera-enhance
      google_assistant: false
    # Scripts
    script.smoke_break:
      icon: mdi:smoking
    script.smoke_break_timer_off:
      hidden: true

# vim: set filetype=yaml et sw=2 ts=2 :
