cover:
  - platform: mqtt
    name: "Living Room Table"
    command_topic: "hassistant/states/cover/living_room_table/command"
    state_topic: "hassistant/states/cover/living_room_table/state"
    qos: 2

  - platform: mqtt
    name: "Living Room TV"
    command_topic: "hassistant/states/cover/living_room_tv/command"
    state_topic: "hassistant/states/cover/living_room_tv/state"
    qos: 2

  - platform: mqtt
    name: "Living Room Door"
    command_topic: "hassistant/states/cover/living_room_door/command"
    state_topic: "hassistant/states/cover/living_room_door/state"
    qos: 2

  - platform: mqtt
    name: "Kitchen"
    command_topic: "hassistant/states/cover/kitchen/command"
    state_topic: "hassistant/states/cover/kitchen/state"
    qos: 2

  - platform: mqtt
    name: "Bedroom"
    command_topic: "hassistant/states/cover/bedroom/command"
    state_topic: "hassistant/states/cover/bedroom/state"
    qos: 2

  - platform: mqtt
    name: "Bedroom door"
    command_topic: "hassistant/states/cover/bedroom_door/command"
    state_topic: "hassistant/states/cover/bedroom_door/state"
    qos: 2

  - platform: mqtt
    name: "Office"
    command_topic: "hassistant/states/cover/office/command"
    state_topic: "hassistant/states/cover/office/state"
    qos: 2


group:
  main_covers:
    name: Main Covers
    view: no
    entities:
      - group.bedroom_covers
      - cover.living_room_table
      - cover.living_room_tv
      - cover.kitchen
      - cover.office

  bedroom_covers:
    name: Bedroom Covers
    view: no
    entities:
      - cover.bedroom
      - cover.bedroom_door
      - cover.bedroom_tv

  living_room_covers:
    name: Living Room Covers
    view: no
    entities:
      - cover.living_room_table
      - cover.living_room_door
      - cover.living_room_tv

  auto_covers:
    name: Automated Covers
    view: no
    entities:
      - group.living_room_covers
      - cover.office
      - cover.kitchen


script:
  cover_winpi:
    sequence:
      - service: cover.close_cover
        entity_id: cover.living_room_table
      - delay: '00:00:25'
      - service: cover.open_cover
        entity_id: cover.living_room_table
      - delay: '00:00:05'
      - service: cover.stop_cover
        entity_id: cover.living_room_table

  cover_set_favorite_position:
    sequence:
      - service: cover.stop_cover
        data_template:
          entity_id: '{{ entity_id }}'
      - delay: '00:00:30'
      - service: cover.stop_cover
        data_template:
          entity_id: '{{ entity_id }}'


  open_all_covers:
    alias: 'Open all covers'
    sequence:
      - service: cover.open_cover
        entity_id: group.all_covers

  open_main_covers:
    alias: 'Open main covers'
    sequence:
      - service: cover.open_cover
        entity_id: group.main_covers

  open_living_room_covers:
    alias: 'Open living room covers'
    sequence:
      - service: cover.open_cover
        entity_id: group.living_room_covers

  open_bedroom_covers:
    alias: 'Open bedroom covers'
    sequence:
      - service: cover.open_cover
        entity_id: group.bedroom_covers

  open_auto_covers:
    alias: 'Open automated covers'
    sequence:
      - service: cover.open_cover
        entity_id: group.auto_covers

  close_all_covers:
    alias: 'Close all covers'
    sequence:
      - service: cover.close_cover
        entity_id: group.all_covers

  close_main_covers:
    alias: 'Close main covers'
    sequence:
      - service: cover.close_cover
        entity_id: group.main_covers

  close_living_room_covers:
    alias: 'Close living room covers'
    sequence:
      - service: cover.close_cover
        entity_id: group.living_room_covers

  close_bedroom_covers:
    alias: 'Open bedroom covers'
    sequence:
      - service: cover.close_cover
        entity_id: group.bedroom_covers

  close_auto_covers:
    alias: 'Open automated covers'
    sequence:
      - service: cover.close_cover
        entity_id: group.auto_covers


automation:
  - alias: Shut the covers when the sun sets
    initial_state: true
    trigger:
      platform: sun
      event: sunset
    action:
      - service: script.close_main_covers

  - alias: Open some covers 15min before sun rises
    initial_state: true
    trigger:
      platform: sun
      event: sunrise
      offset: "-00:15:00"
    # condition:
    #   condition: state
    #   entity_id: group.main_mobile_devices
    #   state: home
    action:
      - service: script.open_auto_covers

  - alias: Open bedroom covers at 10:00
    initial_state: true
    trigger:
      platform: time
      at: "10:00:00"
    # condition:
    #   condition: state
    #   entity_id: group.main_mobile_devices
    #   state: home
    action:
      - service: script.open_bedroom_covers


homeassistant:
  customize:
    group.all_covers:
      hidden: False

# vim: set filetype=yaml et sw=2 ts=2 :
