cover:
  - platform: template
    covers:
      all_covers:
        friendly_name: "All covers"
        open_cover:
          service: script.open_all_covers
        close_cover:
          service: script.close_all_covers
        stop_cover:
          service: script.stop_all_covers
        position_template: 50

  - platform: mqtt
    name: "Living Room Table"
    command_topic: "hassistant/states/cover/living_room_table/command"
    state_topic: "hassistant/states/cover/living_room_table/state"
    qos: 2

  - platform: mqtt
    name: "Living Room TV"
    command_topic: "hassistant/states/cover/living_room_tv/command"
    state_topic: "hassistant/states/cover/living_room_tv/state"
    qos: 2

  - platform: mqtt
    name: "Living Room Door"
    command_topic: "hassistant/states/cover/living_room_door/command"
    state_topic: "hassistant/states/cover/living_room_door/state"
    qos: 2

  - platform: mqtt
    name: "Kitchen"
    command_topic: "hassistant/states/cover/kitchen/command"
    state_topic: "hassistant/states/cover/kitchen/state"
    qos: 2

  - platform: mqtt
    name: "Bedroom window"
    command_topic: "hassistant/states/cover/bedroom/command"
    state_topic: "hassistant/states/cover/bedroom/state"
    qos: 2

  - platform: mqtt
    name: "Bedroom door"
    command_topic: "hassistant/states/cover/bedroom_door/command"
    state_topic: "hassistant/states/cover/bedroom_door/state"
    qos: 2

  - platform: mqtt
    name: "Office"
    command_topic: "hassistant/states/cover/office/command"
    state_topic: "hassistant/states/cover/office/state"
    qos: 2

  - platform: group
    name: Bedroom
    entities:
      - cover.bedroom_window
      - cover.bedroom_door

  - platform: group
    name: Living Room Main
    entities:
      - cover.living_room_table
      - cover.living_room_tv

  - platform: group
    name: Living Room
    entities:
      - cover.living_room_table
      - cover.living_room_door
      - cover.living_room_tv

  - platform: group
    name: Main Covers
    entities:
      - cover.bedroom
      # group.living_room_covers is voluntarily omitted here, since we do not
      # want to close the door's cover
      - cover.living_room_table
      - cover.living_room_tv
      - cover.kitchen
      - cover.office

  - platform: group
    name: Automated Covers
    entities:
      - cover.living_room
      - cover.office
      - cover.kitchen


script:
  cover_privacy:
    alias: Privacy Cover Mode
    sequence:
      - service: cover.close_cover
        entity_id: cover.living_room_main
      - delay: '00:00:22'
      - service: cover.open_cover
        entity_id: cover.living_room_main
      - delay: '00:00:06'
      - service: cover.stop_cover
        entity_id: cover.living_room_main

  cover_movie_smoke_break:
    alias: "Cover: Movie Smoke Break"
    sequence:
      - service: cover.stop_cover
        entity_id: cover.living_room_table
      - delay: '00:00:10'
      - service: cover.stop_cover
        entity_id: cover.living_room_table

  cover_winpi:
    sequence:
      - service: cover.close_cover
        entity_id: cover.living_room_table
      - delay: '00:00:25'
      - service: cover.open_cover
        entity_id: cover.living_room_table
      - delay: '00:00:05'
      - service: cover.stop_cover
        entity_id: cover.living_room_table

  cover_set_favorite_position:
    sequence:
      - service: cover.stop_cover
        data_template:
          entity_id: '{{ entity_id }}'
      - delay: '00:00:30'
      - service: cover.stop_cover
        data_template:
          entity_id: '{{ entity_id }}'


  open_all_covers:
    alias: 'Open all covers'
    sequence:
      - service: cover.open_cover
        entity_id: group.all_covers

  open_all_covers_if_sun_is_up:
    alias: 'Open all covers (only if the sun is up)'
    sequence:
      - condition: sun
        before: sunset
      - service: cover.open_cover
        entity_id: group.all_covers

  open_main_covers:
    alias: 'Open main covers'
    sequence:
      - service: cover.open_cover
        entity_id: cover.main_covers

  open_living_room_covers:
    alias: 'Open living room covers'
    sequence:
      - service: cover.open_cover
        entity_id: cover.living_room_covers

  open_bedroom_covers:
    alias: 'Open bedroom covers'
    sequence:
      - service: cover.open_cover
        entity_id: cover.bedroom

  open_auto_covers:
    alias: 'Open automated covers'
    sequence:
      - service: cover.open_cover
        entity_id: cover.automated_covers

  close_all_covers:
    alias: 'Close all covers'
    sequence:
      - service: cover.close_cover
        entity_id: group.all_covers

  close_main_covers:
    alias: 'Close main covers'
    sequence:
      - service: cover.close_cover
        entity_id: cover.main_covers

  close_living_room_covers:
    alias: 'Close living room covers'
    sequence:
      - service: cover.close_cover
        entity_id: cover.living_room_covers

  close_bedroom_covers:
    alias: 'Open bedroom covers'
    sequence:
      - service: cover.close_cover
        entity_id: cover.bedroom

  close_auto_covers:
    alias: 'Open automated covers'
    sequence:
      - service: cover.close_cover
        entity_id: cover.automated_covers

  stop_all_covers:
    alias: 'Stop all covers'
    sequence:
      - service: cover.stop_cover
        entity_id: group.all_covers


homeassistant:
  customize:
    group.all_covers:
      hidden: False
    script.cover_privacy:
      can_cancel: False
      icon: mdi:eye-off
    script.cover_movie_smoke_break:
      can_cancel: False
      icon: mdi:smoking

# vim: set filetype=yaml et sw=2 ts=2 :
