cover:
  - platform: mqtt
    name: "Living Room Table"
    command_topic: "hassistant/states/cover/living_room_table/command"
    state_topic: "hassistant/states/cover/living_room_table/state"

  - platform: mqtt
    name: "Living Room Door"
    command_topic: "hassistant/states/cover/living_room_door/command"
    state_topic: "hassistant/states/cover/living_room_door/state"

  - platform: mqtt
    name: "Kitchen"
    command_topic: "hassistant/states/cover/kitchen/command"
    state_topic: "hassistant/states/cover/kitchen/state"

  - platform: mqtt
    name: "Bedroom"
    command_topic: "hassistant/states/cover/bedroom/command"
    state_topic: "hassistant/states/cover/bedroom/state"

  - platform: mqtt
    name: "Bedroom door"
    command_topic: "hassistant/states/cover/bedroom_door/command"
    state_topic: "hassistant/states/cover/bedroom_door/state"

  - platform: mqtt
    name: "Office"
    command_topic: "hassistant/states/cover/office/command"
    state_topic: "hassistant/states/cover/office/state"

homeassistant:
  customize:
    group.all_covers:
      hidden: False
# vim: set filetype=yaml et sw=2 ts=2 :
