device_tracker:
  - platform: luci
    host: 10.7.0.1
    username: !secret owrt_username
    password: !secret owrt_password
    track_new_devices: false
    consider_home: 180

  - platform: mqtt_json
    devices:
      n5x_zanzito: zanzito/nexus5x/location


group:
  n5x:
    name: Nexus 5X
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.n5x_zanzito
      - device_tracker.n5x_arp


automation:
  - alias: Notify when new network device has been discovered
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.html5
        data_template:
          message: "A new device has been detected: {{ trigger.event }}"
      - service: notify.pushover
        data_template:
          message: "A new device has been detected: {{ trigger.event }}"

# vim: set filetype=yaml et sw=2 ts=2 :
