device_tracker:
  - platform: google_maps
    username: !secret google_maps_username
    password: !secret google_maps_password

  - platform: luci
    host: 10.7.0.1
    username: !secret owrt_username
    password: !secret owrt_password
    consider_home: 60
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false

  # - platform: ubus
  #   host: 10.7.0.3
  #   username: !secret turris_username
  #   password: !secret turris_password
  #   consider_home: 60
  #   new_device_defaults:
  #     track_new_devices: false
  #     hide_if_away: false

  - platform: ping
    count: 3
    hosts:
      op3t_ping: oneplus_3t.lan
      g4p_ping: g4p.lan
      macbook_ping: 10.7.0.231

  # - platform: nmap_tracker
  #   hosts: oneplus_3t.lan
  #   home_interval: 3

  # Zanzito devices
  - platform: mqtt_json
    devices:
      g4p_zanzito: zanzito/g4play/location

  # Remote luci devices
  - platform: mqtt
    devices:
      g4p_hassistant: hassistant/states/device_tracker/g4p/state
      op3t_hassistant: hassistant/states/device_tracker/op3t/state


group:
  main_mobile_devices:
    name: Main Devices
    view: no
    icon: mdi:cellphone-android
    entities:
      - group.pschmitt_location
      - group.mbiver_location

  pschmitt_location:
    name: "pschmitt location"
    view: no
    icon: mdi:cellphone-android
    entities:
      - group.g4p

  mbiver_location:
    name: "mbiver location"
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.google_maps_105543397094537443482
      - group.op3t
      # - group.macbook

  g4p:
    name: "g4p"
    view: no
    icon: mdi:cellphone-android
    entities:
      # - device_tracker.g4p_arp
      # - device_tracker.g4p_ping
      - device_tracker.g4p_hassistant
      - device_tracker.g4p_zanzito

  op3t:
    name: "op3t"
    view: no
    icon: mdi:cellphone-android
    entities:
      # - device_tracker.op3t_hassistant
      # - device_tracker.op3t_arp
      - device_tracker.op3t_ping

  macbook:
    name: "macbook"
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.macbook_arp
      - device_tracker.macbook_ping


sensor:
  - platform: rest
    name: g4p_find3
    resource: http://10.7.0.216:8003/api/v1/location_basic/comreset.io/g4p
    value_template: '{{ value_json.data.loc }}'
    method: GET
    scan_interval: 3


automation:
  - alias: Notify when new network device has been discovered
    initial_state: true
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.html5
        data_template:
          message: "A new device has been detected: {{ trigger.event }}"
      - service: notify.pushover
        data_template:
          message: "A new device has been detected: {{ trigger.event }}"


homeassistant:
  customize:
    device_tracker.g4p_zanzito:
      battery_friendly_name: Moto G4 Play

# vim: set filetype=yaml et sw=2 ts=2 :
