device_tracker:
  - platform: luci
    host: 10.7.0.1
    username: !secret owrt_username
    password: !secret owrt_password
    track_new_devices: false
    consider_home: 180

  - platform: mqtt_json
    devices:
      n5x_zanzito: zanzito/nexus5x/location
      g4p_zanzito: zanzito/g4play/location


group:
  pschmitt_location:
    name: "My location"
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.g4p_zanzito
      - device_tracker.g4p_arp
      # - device_tracker.n5x_zanzito
      # - device_tracker.n5x_arp

  main_mobile_devices:
    name: Main Devices
    view: no
    icon: mdi:cellphone-android
    entities:
      - device_tracker.g4p_zanzito
      - device_tracker.g4p_arp
      # - device_tracker.n5x_zanzito
      # - device_tracker.n5x_arp
      - device_tracker.her_phone


sensor:
  - platform: template
    sensors:
      g4p_battery:
        friendly_name: Moto G4 Play Battery
        value_template: ' {{ states.device_tracker.g4p_zanzito.attributes.battery }}'
        unit_of_measurement: '%'
      n5x_battery:
        friendly_name: Nexus 5X Battery
        value_template: ' {{ states.device_tracker.n5x_zanzito.attributes.battery }}'
        unit_of_measurement: '%'


automation:
  - alias: Notify when new network device has been discovered
    initial_state: true
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.html5
        data_template:
          message: "A new device has been detected: {{ trigger.event }}"
      - service: notify.pushover
        data_template:
          message: "A new device has been detected: {{ trigger.event }}"

# vim: set filetype=yaml et sw=2 ts=2 :
