binary_sensor:
  - platform: flic
    host: rastapi.lan
    port: 5551
    discovery: false

  - platform: flic
    host: hassio.lan
    port: 5551
    discovery: false


automation:
  - alias: Start a smoke break when the flic button is pressed and the outdoor light is off
    trigger:
      - platform: event
        event_type: flic_click
        event_data:
          button_name: !secret flic_button_white_1
          click_type: single
    condition:
      - condition: state
        entity_id: light.terrace_light
        state: 'off'
    action:
      - service: script.smoke_break

  - alias: Turn off the outdoor light if it is on
    trigger:
      - platform: event
        event_type: flic_click
        event_data:
          button_name: !secret flic_button_white_1
          click_type: single
    condition:
      - condition: state
        entity_id: light.terrace_light
        state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.terrace_light
      - service: script.turn_off
        data:
          entity_id: script.smoke_break_timer_off

  - alias: Flic B1: Toggle office stuff on flic press
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_black_1
        click_type: single
    action:
      - service: script.toggle_guest_room_tv
      - service: light.toggle
        data:
          entity_id: group.office_lights

  - alias: Flic B1: Turn on office stuff on double flic press
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_black_1
        click_type: double
    action:
      - service: script.turn_on_guest_room_tv
      - service: light.turn_on
        data:
          entity_id: group.office_lights

  - alias: Flic B1: Turn off office stuff on flic hold
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_black_1
        click_type: hold
    action:
      - service: script.turn_off_guest_room_tv
      - service: light.turn_off
        data:
          entity_id: group.office_lights

  - alias: Flic W2: Toggle office when flic button is pressed
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_white_2
        click_type: single
    action:
      - service: script.toggle_guest_room_tv
      - service: light.toggle
        data:
          entity_id: group.office_lights

  - alias: Flic W2: Turn on office when flic button is pressed
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_white_2
        click_type: double
    action:
      - service: script.turn_on_guest_room_tv
      - service: light.turn_on
        data:
          entity_id: group.office_lights

  - alias: Flic W2: Turn off office when flic button is pressed
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_white_2
        click_type: hold
    action:
      - service: script.turn_off_guest_room_tv
      - service: light.turn_off
        data:
          entity_id: group.office_lights

  - alias: Start bedtime script on single button press
    trigger:
      - platform: event
        event_type: flic_click
        event_data:
          button_name: !secret flic_button_black_2
          click_type: single
    action:
      - service: script.bedtime

  - alias: Turn off all on long button press
    trigger:
      - platform: event
        event_type: flic_click
        event_data:
          button_name: !secret flic_button_black_2
          click_type: hold
    action:
      - service: script.all_off
      - service: script.lock_door

homeassistant:
  customize:
    binary_sensor.flic_80e4da721df4:
      friendly_name: "Flic Button - Guest Room"
    binary_sensor.flic_80e4da720d46:
      friendly_name: "Flic Button - Bedroom"
    binary_sensor.flic_80e4da721d59:
      friendly_name: "Flic Button - Terrace"
    binary_sensor.flic_80e4da720d40:
      friendly_name: "Flic Button - Living Room"

# vim: set filetype=yaml et sw=2 ts=2 :
