input_boolean:
  dnd:
    name: DND Mode
    icon: mdi:volume-off


automation:
  - alias: HASS startup automation
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: shell_command.setup_routing
      - service: notify.html5
        data:
          message: "Home Assistant has (re)started"
          data:
            tag: "hass-restart"
            renotify: True
      - service: frontend.set_theme
        data:
          name: dark
      # Request zanzito update
      - service: mqtt.publish
        data:
          topic: zanzito/g4play/cmd/send_heartbeat
          qos: 0
          retain: 0
      - delay: 00:05:00
      - service: script.enable_annoying_automations

  - alias: Update notifications
    initial_state: true
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.html5
      data_template:
        message: "Home Assistant {{ states.updater.updater.state }} is now available."


sensor:
  - platform: min_max
    name: 'Home Temperature'
    type: mean
    entity_ids:
      - sensor.hue_bathroom_temperature
      - sensor.hue_hallway_temperature
      - sensor.hue_kitchen_temperature
      - sensor.hue_toilet_temperature
      - sensor.aloe_vera_temperature
      - sensor.basil_temperature
      - sensor.chive_temperature
      - sensor.ficus_temperature
      - sensor.mint_temperature


rest_command:
  ha_restart:
    method: get
    url: http://nasteanas.lan:8993/ha/restart


shell_command:
  setup_routing: !secret shell_cmd_setup_routing


script:
  ha_restart:
    alias: 'Restart HASS'
    sequence:
      - service: rest_command.ha_restart

  ha_reload_config:
    alias: 'Reload core config'
    sequence:
      - service: homeassistant.reload_core_config

  enable_annoying_automations:
    alias: 'Enable annoying automations'
    sequence:
      - service: automation.turn_on
        entity_id: automation.ask_to_buzz_door_open_when_approaching_home
      - service: automation.turn_on
        entity_id: automation.react_to_my_homecoming
      - service: automation.turn_on
        entity_id: automation.talk_to_my_wife_when_she_gets_home
      - service: automation.turn_on
        entity_id: automation.watching_teva
      - service: automation.turn_on
        entity_id: automation.playing_ps3


group:
  hass:
    name: hass
    view: yes
    icon: mdi:home-assistant
    entities:
      # - group.all
      - group.hass_infrastructure
      - group.all_devices
      - group.flic_buttons
      - group.media_players
      - group.all_scripts
      - group.all_lights
      - group.all_sensors
      - group.all_switches
      # - group.all_automations
      # - group.media_players
      - group.zwave
      - group.battery_devices
      - group.windows


homeassistant:
  customize:
    # Groups
    group.hass:
      order: 99
    # Entities belonging to HASS tab
    group.hass_infrastructure:
      order: 1
    group.zwave:
      order: 3
    group.all:
      hidden: false
    group.all_automations:
      hidden: false
      order: 99
    group.all_devices:
      order: 2
      hidden: false
    group.all_lights:
      hidden: false
      order: 2
    group.all_scripts:
      control: hidden
      order: 1
      hidden: false
    group.all_switches:
      control: hidden
      hidden: false
      order: 4
    # Scripts
    script.ha_reload_config:
      icon: mdi:refresh
    script.ha_restart:
      icon: mdi:power

# vim: set filetype=yaml et sw=2 ts=2 :
