automation:
  - alias: Notify when HA starts
    trigger:
      platform: homeassistant
      event: start
    action:
      service: notify.html5
      data:
        message: "Home Assistant has (re)started"
        data:
          tag: "hass-restart"
          renotify: True

  - alias: HASS startup automation
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: frontend.set_theme
        data:
          name: dark
      # Request zanzito update
      - service: mqtt.publish
        data:
          topic: zanzito/nexus5x/cmd/send_heartbeat
          qos: 0
          retain: 0
      - delay: 00:05:00
      - service: automation.turn_on
        entity_id: automation.react_to_my_homecoming
      - service: automation.turn_on
        entity_id: automation.talk_to_my_wife_when_she_gets_home
      - service: automation.turn_on
        entity_id: automation.watching_teva
      - service: automation.turn_on
        entity_id: automation.playing_ps3

  - alias: Update notifications
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.html5
      data_template:
        message: "Home Assistant {{ states.updater.updater.state }} is now available."


rest_command:
  ha_restart:
    method: get
    url: http://nasteanas.lan:8993/ha/restart


script:
  ha_restart:
    alias: 'Restart HASS'
    sequence:
      - service: rest_command.ha_restart

  ha_reload_config:
    alias: 'Reload core config'
    sequence:
      - service: homeassistant.reload_core_config


group:
  hass:
    name: hass
    view: yes
    icon: mdi:bug
    entities:
      # - group.all
      - group.hass_infrastructure
      - group.all_devices
      - group.media_players
      - group.all_scripts
      - group.all_lights
      - group.all_sensors
      - group.all_switches
      # - group.all_automations
      # - group.media_players
      - group.zwave


homeassistant:
  customize:
    # Groups
    group.hass:
      order: 99
    # Entities belonging to HASS tab
    group.hass_infrastructure:
      order: 1
    group.zwave:
      order: 3
    group.all:
      hidden: false
    group.all_automations:
      hidden: false
      order: 99
    group.all_devices:
      order: 2
      hidden: false
    group.all_lights:
      hidden: false
      order: 2
    group.all_scripts:
      control: hidden
      order: 1
      hidden: false
    group.all_switches:
      control: hidden
      hidden: false
      order: 4
    # Scripts
    script.ha_reload_config:
      icon: mdi:refresh
    script.ha_restart:
      icon: mdi:power

# vim: set filetype=yaml et sw=2 ts=2 :
