automation:
  - alias: React to my homecoming
    initial_state: false
    trigger:
      - platform: state
        entity_id: device_tracker.g4p_zanzito
        from: not_home
        to: home
    action:
      - service: script.im_home

  - alias: Talk to my wife when she gets home
    initial_state: false
    trigger:
      - platform: state
        entity_id: device_tracker.her_phone
        from: not_home
        to: home
    action:
      - service: script.she_is_home

  - alias: "Ask to buzz door open when approaching home"
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: proximity.home
        below: 100
    action:
      - service: notify.html5
        data:
          message: "You are approaching home. Wanna make me buzz you in?"
          data:
            tag: 'buzz-open-query'
            renotify: False
            actions:
              - action: buzz_open
                icon: https://materialdesignicons.com/api/download/icon/png/E357D5CD-7E42-463B-899A-7D7B038A3E31/48
                title: "Buzz Open"

  - alias: "HTML5 notification: Buzz open"
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: buzz_open
    action:
      - service: script.buzz_door_open_multiple


script:
  im_home:
    alias: 'I am home'
    sequence:
      - service: notifiy.html5
        data:
          message: "You've just entered the 'Home' zone"

  she_is_home:
    alias: 'She is home'
    sequence:
      - service: notify.pushover
        data:
          message: 'Mimine just came home'
      - service: tts.google_say
        entity_id: media_player.living_room_speaker
        data:
          message: 'Salut Mimine. Bienvenue à la maison'

  let_me_in:
    alias: 'Let me in!'
    sequence:
      - service: script.alarm_disarm
      - service: script.unlock_door
      - delay:
          minutes: 5
      - service: script.lock_door

# vim: set filetype=yaml et sw=2 ts=2 :
