light:
  - platform: hue
    host: philips-hue.lan
    allow_unreachable: true


automation:
  - alias: Turn on lights just before sunset
    initial_state: true
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    condition:
      condition: state
      entity_id: group.main_mobile_devices
      state: home
    action:
      - service: light.turn_on
        entity_id: light.living_room
        data:
          color_name: white
          brightness: 150
          transition: 10

  - alias: Turn off bedroom lights after 30 minutes
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.bedroom_light
        to: 'on'
        for:
          minutes: 30
    action:
      - service: light.turn_off
        entity_id: light.bedroom_light

  - alias: Hue Master Switch ON pressed
    initial_state: true
    trigger:
      - platform: event
        event_type: zhue_switch_master_button_INITIAL_PRESSED_4
      - platform: event
        event_type: zhue_switch_master_button_SHORT_RELEASED_4
    action:
      - service: script.hue_master_switch_off

  - alias: Hue Master Switch OFF pressed
    initial_state: true
    trigger:
      - platform: event
        event_type: zhue_switch_master_button_INITIAL_PRESSED_1
      - platform: event
        event_type: zhue_switch_master_button_SHORT_RELEASED_1
    action:
      - service: script.hue_master_switch_on
      - service: script.lock_n_go

  - alias: Hue Motion Sensor battery is low
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.hue_bathroom_battery, sensor.hue_hallway_battery, sensor.hue_hue_kitchen_battery, sensor.hue_toilet_battery
        below: 15
    action:
      - service: notify.html5
        data_template:
          message: "Hue motion sensor battery is low on {{ trigger.to_state.attributes.friendly_name }}"


group:
  light_groups:
    name: Lights
    view: no
    entities:
      - light.front_door
      - light.living_room
      - light.terrace
      - light.office
      - light.bedroom
      - light.toilet
      - light.bathroom
      - light.kitchen
      - light.hallway

  light_bulbs:
    name: Light bulbs
    view: no
    entities:
      - light.front_door_light
      - light.living_room_tv_light
      - light.living_room_table_light
      - light.terrace_light
      - light.office_light
      - light.bedroom_light
      - light.toilet_light
      - light.bathroom_light
      - light.kitchen_light
      - light.hallway_light


scene:
  - name: Living Room Normal
    entities:
      light.living_room:
        state: on
        transition: 3
        brightness: 150
        xy_color: [ 0.4448, 0.4066 ]

  - name: Living Room Dim
    entities:
      light.living_room:
        state: on
        transition: 3
        brightness: 75
        xy_color: [ 0.5926, 0.3814 ]
      light.entrance:
        state: off
        transition: 1
      light.terrace:
        state: off
        transition: 1
      light.kitchen:
        state: off
        transition: 1

  - name: Flash Living Room Lights
    entities:
      light.living_room:
        state: on
        flash: short

  - name: Flash Office Lights
    entities:
      light.office:
        state: on
        flash: short

  - name: Flash Lights
    entities:
      light.office:
        state: on
        flash: short
      light.living_room:
        state: on
        flash: short

  - name: Bedtime
    entities:
      light.terrace:
        state: off
      light.hallway:
        state: off
      light.toilet:
        state: off
      light.bathroom:
        state: off
      light.office:
        state: off
      light.bedroom:
        state: off


sensor:
  - platform: command_line
    name: 'Hue Toilet Battery'
    command: /scripts/zhue.sh battery toilet
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 3600

  - platform: command_line
    name: 'Hue Toilet Lux'
    command: /scripts/zhue.sh lux toilet
    value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
    unit_of_measurement: klx
    scan_interval: 600

  - platform: command_line
    name: 'Hue Toilet Temperature'
    command: /scripts/zhue.sh temperature toilet
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: 째C
    scan_interval: 600

  - platform: command_line
    name: 'Hue Hallway Battery'
    command: /scripts/zhue.sh battery hallway
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 3600

  - platform: command_line
    name: 'Hue Hallway Lux'
    command: /scripts/zhue.sh lux hallway
    value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
    unit_of_measurement: klx
    scan_interval: 600

  - platform: command_line
    name: 'Hue Hallway Temperature'
    command: /scripts/zhue.sh temperature hallway
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: 째C
    scan_interval: 600

  - platform: command_line
    name: 'Hue Kitchen Battery'
    command: /scripts/zhue.sh battery kitchen
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 3600

  - platform: command_line
    name: 'Hue Kitchen Lux'
    command: /scripts/zhue.sh lux kitchen
    value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
    unit_of_measurement: klx
    scan_interval: 600

  - platform: command_line
    name: 'Hue Kitchen Temperature'
    command: /scripts/zhue.sh temperature kitchen
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: 째C
    scan_interval: 600

  - platform: command_line
    name: 'Hue Bathroom Battery'
    command: /scripts/zhue.sh battery bathroom
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 3600

  - platform: command_line
    name: 'Hue Bathroom Lux'
    command: /scripts/zhue.sh lux bathroom
    value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
    unit_of_measurement: klx
    scan_interval: 600

  - platform: command_line
    name: 'Hue Bathroom Temperature'
    command: /scripts/zhue.sh temperature bathroom
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: 째C
    scan_interval: 600


binary_sensor:
  - platform: command_line
    name: 'Toilet Presence'
    device_class: motion
    command: /scripts/zhue.sh presence toilet
    value_template: '{{ value_json.state.presence }}'

  - platform: command_line
    name: 'Hallway Presence'
    device_class: motion
    command: /scripts/zhue.sh presence hallway
    value_template: '{{ value_json.state.presence }}'

  - platform: command_line
    name: 'Kitchen Presence'
    device_class: motion
    command: /scripts/zhue.sh presence kitchen
    value_template: '{{ value_json.state.presence }}'

  - platform: command_line
    name: 'Bathroom Presence'
    device_class: motion
    command: /scripts/zhue.sh presence bathroom
    value_template: '{{ value_json.state.presence }}'


script:
  hue_master_switch_on:
    alias: 'Hue Master Dimmer Switch ON pressed'
    sequence:
      - service: script.watch_tv

  hue_master_switch_off:
    alias: 'Hue Master Dimmer Switch OFF pressed'
    sequence:
      - service: script.all_off

  flash_office_lights:
    alias: Flash Office Lights
    sequence:
      - service: scene.turn_on
        entity_id: scene.flash_office_lights

  flash_living_room_lights:
    alias: Flash Living Room Lights
    sequence:
      - service: scene.turn_on
        entity_id: scene.flash_living_room_lights

  flash_lights:
    alias: Flash Lights
    sequence:
      - service: script.flash_living_room_lights
      - service: script.flash_office_lights

  smoke_break:
    alias: "Smoke break"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
          entity_id: script.smoke_break_timer_off
      - service_template: >
          light.{% if is_state('light.terrace', 'on') %}turn_off{% else %}turn_on{% endif %}
        data:
          entity_id: light.terrace
          color_name: white
          brightness: 217 # 85%
          # {% if is_state('light.terrace', 'on') %}
          # color_name: white
          # brightness: 217 # 85%
          # {% endif %}
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.smoke_break_timer_off

  smoke_break_timer_off:
    alias: "Smoke break: Turn off lamp after 5 minutes"
    sequence:
      - delay:
          minutes: 5
      - service: light.turn_off
        data:
          entity_id: light.terrace



homeassistant:
  customize:
    # Lights
    light.all_hue_lights:
      google_assistant: false
    light.bathroom:
      # icon: mdi:hot-tub
      icon: mdi:water-pump
      google_assistant: false
    light.bedroom:
      icon: mdi:hotel
      google_assistant: false
    light.front_door:
      icon: mdi:home-modern
      google_assistant: false
    light.hallway:
      icon: mdi:vector-square
      google_assistant: false
    light.kitchen:
      icon: mdi:pot-mix
      google_assistant: false
    light.living_room:
      icon: mdi:sofa
      google_assistant: false
    light.living_room_table_light:
      icon: mdi:food
    light.living_room_tv_light:
      icon: mdi:television
    light.office:
      icon: mdi:book-open
      google_assistant: false
    light.terrace:
      icon: mdi:tree
      google_assistant: false
    light.toilet:
      icon: mdi:human-male-female
      google_assistant: false
    # Hue sensors
    sensor.hallway_lux:
      icon: mdi:white-balance-sunny
    sensor.toilet_lux:
      icon: mdi:white-balance-sunny
    sensor.kitchen_lux:
      icon: mdi:white-balance-sunny
    sensor.bathroom_lux:
      icon: mdi:white-balance-sunny
    sensor.home_temperature:
      icon: mdi:temperature-celsius
    # Scenes
    scene.bedtime:
      icon: mdi:weather-night
      order: 1
    scene.living_room_normal:
      icon: mdi:brightness-1
    scene.living_room_dim:
      icon: mdi:brightness-2
    # Scripts
    script.hue_master_switch_on:
      icon: mdi:grid
    script.hue_master_switch_off:
      icon: mdi:grid-off
    script.flash_living_room_lights:
      icon: mdi:spotlight

# vim: set filetype=yaml et sw=2 ts=2 :
