xiaomi:
  interface: !secret lan_ipv4_addr
  gateways:
    - mac: !secret mi_gw_mac
      key: !secret mi_gw_api_key


sensor:
  - platform: template
    sensors:
      mi_fridge_door_battery:
        friendly_name: Mi Fridge Door Sensor Battery
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001a1eb5b.attributes.battery_level }}'
        unit_of_measurement: '%'
      mi_terrace_door_battery:
        friendly_name: Mi Terrace Door Sensor Battery
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001a1ec56.attributes.battery_level }}'
        unit_of_measurement: '%'
      mi_fridge_temp_battery:
        friendly_name: Mi Fridge Temperature Sensor Battery
        value_template: '{{ states.sensor.temperature_158d0001d6f4da.attributes.battery_level }}'
        unit_of_measurement: '%'
      mi_freezer_temp_battery:
        friendly_name: Mi Freezer Temperature Sensor Battery
        value_template: '{{ states.sensor.temperature_158d0001d6f4e5.attributes.battery_level }}'
        unit_of_measurement: '%'


group:
  fridge:
    name: Fridge
    view: no
    icon: mdi:fridge
    entities:
      - binary_sensor.door_window_sensor_158d0001a1eb5b
      - sensor.temperature_158d0001d6f4da
      - sensor.temperature_158d0001d6f4e5
      - sensor.humidity_158d0001d6f4da
      - sensor.humidity_158d0001d6f4e5
      - sensor.pressure_158d0001d6f4da
      - sensor.pressure_158d0001d6f4e5

  terrace_doors:
    name: Terrace Doors
    view: no
    icon: mdi:door
    entities:
      - binary_sensor.door_window_sensor_158d0001a1ec56


automation:
  - alias: Mi Sensor battery is low
    trigger:
      - platform: numeric_state
        entity_id: sensor.mi_fridge_door_battery, sensor.mi_terrace_door_battery, sensor.mi_fridge_door_battery, sensor.mi_freezer_temp_battery
        below: 15
    action:
      - service: notify.html5
        data_template:
          message: "Mi sensor battery is low on {{ trigger.to_state.attributes.friendly_name }}"
          tag: "mi-battery-low-{{ trigger.to_state.entity_id }}"

  - alias: Turn on the terrace light when door opened during night
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a1ec56
        to: 'on'
    condition:
      condition: sun
      after: sunset
      before_offset: "-1:00:00"
    action:
      - service: script.smoke_break

  - alias: Alert when the fridge has been open for 2 min
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a1eb5b
        to: 'on'
        for:
          minutes: 2
    action:
      - service: notify.html5
        data:
          message: "The fridge has been opened for at least 2 minutes"
          data:
            tag: 'fridge-open'

  - alias: Alert when fridge temperature is above 15C
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_158d0001d6f4da
        above: 15
    action:
      - service: notify.html5
        data_template:
          message: 'The fridge temperature is at {{ trigger.to_state.state }}C!'
          data:
            tag: 'fridge-temp-high'

  - alias: Alert when freezer temperature is above -10C
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_158d0001d6f4e5
        above: -10
    action:
      - service: notify.html5
        data_template:
          message: 'The freezer temperature is at {{ trigger.to_state.state }}C!'
          data:
            tag: 'freezer-temp-high'



homeassistant:
  customize:
    light.gateway_light_34ce008d7aba:
      friendly_name: Mi Gateway Light
    sensor.illumination_34ce008d7aba:
      friendly_name: Mi Gateway Light Level
    binary_sensor.door_window_sensor_158d0001a1eb5b:
      friendly_name: Fridge Door
    binary_sensor.door_window_sensor_158d0001a1ec56:
      friendly_name: Terrace Door
    sensor.humidity_158d0001d6f4da:
      friendly_name: Fridge Humidity
    sensor.pressure_158d0001d6f4da:
      friendly_name: Fridge Pressure
    sensor.temperature_158d0001d6f4da:
      friendly_name: Fridge Temperature
    sensor.humidity_158d0001d6f4e5:
      friendly_name: Freezer Humidity
    sensor.illumination_158d0001d6f4e5:
      friendly_name: Freezer Light Level
    sensor.pressure_158d0001d6f4e5:
      friendly_name: Freezer Pressure
    sensor.temperature_158d0001d6f4e5:
      friendly_name: Freezer Temperature

# vim: set filetype=yaml et sw=2 ts=2 :
