xiaomi:
  interface: !secret lan_ipv4_addr
  gateways:
    - mac: !secret mi_gw_mac
      key: !secret mi_gw_api_key


sensor:
  - platform: template
    sensors:
      mi_fridge_door_battery:
        friendly_name: Mi Fridge Door Sensor Battery
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001a1eb5b.attributes.battery_level }}'
        unit_of_measurement: '%'
      mi_terrace_door_battery:
        friendly_name: Mi Terrace Door Sensor Battery
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001a1ec56.attributes.battery_level }}'
        unit_of_measurement: '%'
      mi_fridge_temp_battery:
        friendly_name: Mi Fridge Temperature Sensor Battery
        value_template: '{{ states.sensor.temperature_158d0001d6f4da.attributes.battery_level }}'
        unit_of_measurement: '%'
      mi_freezer_temp_battery:
        friendly_name: Mi Freezer Temperature Sensor Battery
        value_template: '{{ states.sensor.temperature_158d0001d6f4e5.attributes.battery_level }}'
        unit_of_measurement: '%'


automation:
  - alias: Mi Sensor battery is low
    trigger:
      - platform: numeric_state
        entity_id: sensor.mi_fridge_door_battery, sensor.mi_terrace_door_battery, sensor.mi_fridge_door_battery, sensor.mi_freezer_temp_battery
        below: 15
    action:
      - service: notify.html5
        data_template:
          message: "Mi sensor battery is low on {{ trigger.to_state.attributes.friendly_name }}"

  - alias: Alert when fridge has been opened
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a1ec56
        to: 'on'
    action:
      - service: notify.html5
        data:
          message: "Terrace door opened"

  - alias: Alert when terrace door has been opened
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a1eb5b
        to: 'on'
    action:
      - service: notify.html5
        data:
          message: "Fridge door opened"


homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d0001a1eb5b:
      friendly_name: Fridge Door
    binary_sensor.door_window_sensor_158d0001a1ec56:
      friendly_name: Terrace Door
    light.gateway_light_34ce008d7aba:
      friendly_name: Xiaomi Gateway Light
    sensor.humidity_34ce008d7aba:
      friendly_name: Fridge Humidity
    sensor.illumination_34ce008d7aba:
      friendly_name: Fridge Light Level
    sensor.pressure_158d0001d6f4da:
      friendly_name: Fridge Pressure
    sensor.temperature_158d0001d6f4da:
      friendly_name: Fridge Temperature
    sensor.humidity_158d0001d6f4e5:
      friendly_name: Freezer Humidity
    sensor.illumination_158d0001d6f4e5:
      friendly_name: Freezer Light Level
    sensor.pressure_158d0001d6f4e5:
      friendly_name: Freezer Pressure
    sensor.temperature_158d0001d6f4e5:
      friendly_name: Freezer Temperature

# vim: set filetype=yaml et sw=2 ts=2 :
