shell_command:
  refresh_plant_data: !secret cmd_plantgateway


script:
  refresh_plant_data:
    alias: Refresh plant data
    sequence:
      - service: shell_command.refresh_plant_data


automation:
  - alias: Refresh plant data on start and every 30min
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        minutes: 30
    action:
      - service: script.refresh_plant_data

  - alias: Miflora battery is low
    trigger:
      - platform: numeric_state
        entity_id: sensor.lemon_battery, sensor.aloe_vera_battery, sensor.mint_battery, sensor.ficus_battery, sensor.chive_battery
        below: 15
    action:
      - service: notify.html5
        data_template:
          message: "Miflora battery is low on {{ trigger.to_state.attributes.friendly_name }}"


plant:
  Lemon Tree:
    sensors:
      moisture: sensor.lemon_moisture
      battery: sensor.lemon_battery
      temperature: sensor.lemon_temperature
      conductivity: sensor.lemon_conductivity
      brightness: sensor.lemon_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 15
    min_conductivity: 10
    min_temperature: 0
  Aloe Vera:
    sensors:
      moisture: sensor.aloe_vera_moisture
      battery: sensor.aloe_vera_battery
      temperature: sensor.aloe_vera_temperature
      conductivity: sensor.aloe_vera_conductivity
      brightness: sensor.aloe_vera_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 15
    min_conductivity: 10
    min_temperature: 12
  Basil:
    sensors:
      moisture: sensor.basil_moisture
      battery: sensor.basil_battery
      temperature: sensor.basil_temperature
      conductivity: sensor.basil_conductivity
      brightness: sensor.basil_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 15
    min_conductivity: 10
    min_temperature: 15
  Mint:
    sensors:
      moisture: sensor.mint_moisture
      battery: sensor.mint_battery
      temperature: sensor.mint_temperature
      conductivity: sensor.mint_conductivity
      brightness: sensor.mint_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 15
    min_conductivity: 10
    min_temperature: 15
  Ficus Microcarpa:
    sensors:
      moisture: sensor.ficus_moisture
      battery: sensor.ficus_battery
      temperature: sensor.ficus_temperature
      conductivity: sensor.ficus_conductivity
      brightness: sensor.ficus_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 15
    min_conductivity: 10
    min_temperature: 12
  Chive:
    sensors:
      moisture: sensor.chive_moisture
      battery: sensor.chive_battery
      temperature: sensor.chive_temperature
      conductivity: sensor.chive_conductivity
      brightness: sensor.chive_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 15
    min_conductivity: 10
    min_temperature: 15


sensor:
  - platform: mqtt
    name: lemon_moisture
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: lemon_battery
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: lemon_temperature
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: 'C'

  - platform: mqtt
    name: lemon_conductivity
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: lemon_brightness
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: lemon_last_updated
    state_topic: 'plants/mi/lemon/'
    value_template: '{{ value_json.timestamp }}'

  - platform: mqtt
    name: aloe_vera_moisture
    state_topic: 'plants/mi/aloe_vera/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: aloe_vera_battery
    state_topic: 'plants/mi/aloe_vera/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: aloe_vera_temperature
    state_topic: 'plants/mi/aloe_vera/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: 'C'

  - platform: mqtt
    name: aloe_vera_conductivity
    state_topic: 'plants/mi/aloe_vera/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: aloe_vera_brightness
    state_topic: 'plants/mi/aloe_vera/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: aloe_vera_last_updated
    state_topic: 'plants/mi/aloe_vera/'
    value_template: '{{ value_json.timestamp }}'

  - platform: mqtt
    name: basil_moisture
    state_topic: 'plants/mi/basil/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: basil_battery
    state_topic: 'plants/mi/basil/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: basil_temperature
    state_topic: 'plants/mi/basil/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: 'C'

  - platform: mqtt
    name: basil_conductivity
    state_topic: 'plants/mi/basil/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: basil_brightness
    state_topic: 'plants/mi/basil/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: mint_last_updated
    state_topic: 'plants/mi/mint/'
    value_template: '{{ value_json.timestamp }}'

  - platform: mqtt
    name: mint_moisture
    state_topic: 'plants/mi/mint/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: mint_battery
    state_topic: 'plants/mi/mint/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: mint_temperature
    state_topic: 'plants/mi/mint/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: 'C'

  - platform: mqtt
    name: mint_conductivity
    state_topic: 'plants/mi/mint/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: mint_brightness
    state_topic: 'plants/mi/mint/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: ficus_last_updated
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.timestamp }}'

  - platform: mqtt
    name: ficus_moisture
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: ficus_battery
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: ficus_temperature
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: 'C'

  - platform: mqtt
    name: ficus_conductivity
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: ficus_brightness
    state_topic: 'plants/mi/ficus/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: chive_moisture
    state_topic: 'plants/mi/chive/'
    value_template: '{{ value_json.moisture }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: chive_battery
    state_topic: 'plants/mi/chive/'
    value_template: '{{ value_json.battery }}'
    unit_of_measurement: '%'

  - platform: mqtt
    name: chive_temperature
    state_topic: 'plants/mi/chive/'
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: 'C'

  - platform: mqtt
    name: chive_conductivity
    state_topic: 'plants/mi/chive/'
    value_template: '{{ value_json.conductivity }}'
    unit_of_measurement: 'us/cm'

  - platform: mqtt
    name: chive_brightness
    state_topic: 'plants/mi/chive/'
    value_template: '{{ value_json.brightness }}'
    unit_of_measurement: 'lux'

  - platform: mqtt
    name: chive_last_updated
    state_topic: 'plants/mi/chive/'
    value_template: '{{ value_json.timestamp }}'


homeassistant:
  customize:
    group.all_plants:
      friendly_name: Plants
      hidden: false
    script.refresh_plant_data:
      icon: mdi:flower

# vim: set filetype=yaml et sw=2 ts=2 :
