lock:
  - platform: nello
    username: !secret nello_username
    password: !secret nello_password
    scan_interval: 15


automation:
  - alias: Notify when the door bell has been rung
    initial_state: true
    trigger:
      - platform: event
        event_type: nello_bell_ring
        event_data:
          short_id: e414cae5
          type: 'bell.ring.denied'
      - platform: event
        event_type: nello_bell_ring
        event_data:
          short_id: e414cae5
          type: 'door.open.one.tw'
      - platform: event
        event_type: nello_bell_ring
        event_data:
          short_id: e414cae5
          type: 'door.open.one.geoloc'
    action:
      - service: notify.zanzito_tts
        data:
          message: "Ding Dong"
      - service: script.tts_say
        data:
          message: "Ding Dong. Ding Dong. Ding Dong."
      - service: script.buzz_door_open

  - alias: "Buzz door open when ringing and I'm home"
    initial_state: true
    trigger:
      - platform: event
        event_type: nello_bell_ring
        event_data:
          short_id: e414cae5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.ph1_zanzito
          state: home
        - condition: state
          entity_id: device_tracker.ph1_arp
          state: not_home
    action:
      - service: notify.html5
        data:
          message: "You are outside. Let's buzz every 30s"
          data:
            tag: 'homecoming-buzz'
      - service: script.buzz_door_open_multiple


script:
  buzz_door_open:
    alias: Buzz door open
    sequence:
      - service: lock.unlock
        data:
          entity_id: lock.nello_e414cae5

  buzz_door_open_multiple:
    alias: Buzz door open repeatedly
    sequence:
      - service: script.buzz_door_open
      - delay: 00:00:02
      - service: script.buzz_door_open
      - delay: 00:00:02
      - service: script.buzz_door_open


homeassistant:
  customize:
    lock.nello_e414cae5:
      friendly_name: Nello Home
    # Scripts
    script.buzz_door_open:
      icon: mdi:lock-open

# vim: set filetype=yaml et sw=2 ts=2 :
