lock:
  - platform: nuki
    host: !secret nuki_bridge
    token: !secret nuki_token


binary_sensor:
  - platform: template
    sensors:
      nuki_battery_critical:
        friendly_name: Nuki Lock Critical Battery Level
        device_class: power
        value_template: '{{ states.lock.home.attributes.battery_critical }}'
        entity_id: lock.home


script:
  lock_door:
    alias: Lock door
    sequence:
      - service: lock.lock
        data:
          entity_id: lock.home

  unlock_door:
    alias: Unlock door
    sequence:
      - service: lock.unlock
        data:
          entity_id: lock.home

  lock_n_go:
    alias: Lock'n'go
    sequence:
      - service: lock.nuki_lock_n_go
        data:
          entity_id: lock.home


automation:
  - alias: Lock door after 15min
    initial_state: true
    trigger:
      platform: state
      entity_id: lock.home
      to: 'unlocked'
      for:
        minutes: 15
    action:
      - service: script.lock_door

  - alias: "HTML5 notification: Close door"
    initial_state: true
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: lock_door
    action:
      - service: script.lock_door


alert:
  door_open:
    name: "The door is unlocked. Want me to lock it?"
    entity_id: lock.home
    state: 'unlocked'
    repeat: 60
    can_acknowledge: True
    skip_first: True
    notifiers:
      - door_is_open

  nuki_battery_critical:
    name: "The Nuki lock is running out of batteries"
    done_message: "Nuki lock battery level: OK!"
    entity_id: binary_sensor.nuki_battery_critical
    state: 'on'
    repeat: 7200
    can_acknowledge: True
    skip_first: False
    notifiers:
      - html5


notify:
  - name: door_is_open
    platform: group
    services:
      - service: html5
        data:
          message: "The door is unlocked. Want me to lock it?"
          data:
            tag: 'lock-door-query'
            renotify: True
            actions:
              - action: lock_door
                icon: https://materialdesignicons.com/api/download/icon/png/D711AFDE-2B8D-4932-82AC-A04E7B2810AE/48
                title: "Lock it"


homeassistant:
  customize:
    # Scripts
    script.lock_n_go:
      icon: mdi:run-fast
    script.lock_door:
      icon: mdi:lock
    script.unlock_door:
      icon: mdi:lock-open-outline

# vim: set filetype=yaml et sw=2 ts=2 :
