pilight:
  host: hassistant.lan
  port: 5000
  # send_delay: 0.4


switch:
  - platform: pilight
    switches:
      Office TV:
        on_code:
          protocol: pollin
          systemcode: 1
          unitcode: 1
          'on': 1
        off_code:
          protocol: pollin
          systemcode: 1
          unitcode: 1
          'off': 1


script:
  turn_on_office_desk_light:
    sequence:
      - service: switch.turn_on
        entity_id: switch.office_desk_light

  turn_off_office_desk_light:
    sequence:
      - service: switch.turn_off
        entity_id: switch.office_desk_light


light:
  - platform: template
    lights:
      office_desk_light:
        friendly_name: "Office Light"
        value_template: '{{ is_state("switch.office_desk_light", "on") }}'
        turn_on:
          service: script.turn_on_office_desk_light
        turn_off:
          service: script.turn_off_office_desk_light
        entity_id: switch.office_desk_light


homeassistant:
  customize:
    switch.office_tv:
      icon: mdi:power-plug
    # Fix the friendly_name (Why isn't that working?)
    light.office_desk_light:
      friendly_name: Office Desk Light

# vim: set filetype=yaml et sw=2 ts=2 :
