pilight:
  host: hassistant.lan
  port: 5000
  # send_delay: 0.4


switch:
  - platform: pilight
    switches:
      # Office TV:
      #   on_code:
      #     protocol: pollin
      #     systemcode: 1
      #     unitcode: 1
      #     'on': 1
      #   off_code:
      #     protocol: pollin
      #     systemcode: 1
      #     unitcode: 1
      #     'off': 1
      3D Printer:
        on_code:
          protocol: pollin
          systemcode: 1
          unitcode: 2
          'on': 1
        off_code:
          protocol: pollin
          systemcode: 1
          unitcode: 2
          'off': 1


homeassistant:
  customize:
    switch.office_tv:
      icon: mdi:power-plug

# vim: set filetype=yaml et sw=2 ts=2 :
