automation:
  - alias: Train reminder
    initial_state: true
    trigger:
      - platform: time
        hours: 16
        minutes: 25
        seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.g4p_zanzito
        state: work
    action:
      service: script.train_reminder

  - alias: Train reminder postpone requested
    initial_state: true
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: postpone_train_reminder
    action:
      - delay: 01:00:00
      - service: script.train_reminder

  - alias: Time to go to bed
    initial_state: true
    trigger:
      - platform: time
        hours: 21
        minutes: 50
        seconds: 0
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.g4p_zanzito
          state: home
        - condition: time
          after: '21:00:00'
          weekday:
            - mon
            - tue
            - wed
            - thu
            - sun
    action:
      - service: script.bedtime_reminder

  # - alias: 'Bruh your phone is dying'
  #   initial_state: true
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: sensor.nexus_5x_battery
  #       below: 30
  #   action:
  #     service: notify.pushover
  #     data:


script:
  bedtime_reminder:
    sequence:
      - service: script.tts_say
        data:
          message: "C'est l'heure!"
      - service: notify.zanzito_tts
        data:
          message: "It's time!"
      - service: script.flash_lights

  train_reminder:
    sequence:
      service: notify.html5
      data:
        message: 'Time to leave for your train'
        data:
          tag: "train-reminder"
          actions:
            - action: postpone_train_reminder
              icon: https://materialdesignicons.com/api/download/28F85724-265B-4C24-9975-DDDF788A99E5/000000/1/FFFFFF/0/48
              title: Postpone

# vim: set filetype=yaml et sw=2 ts=2 :
