group:
  bedroom:
    name: Bedroom
    view: yes
    icon: mdi:hotel
    entities:
      - light.bedroom
      - scene.bedtime
      - script.all_off

  office:
    name: Office
    view: yes
    icon: mdi:server-network
    entities:
      - light.gateway_light_34ce008d7aba
      - light.guest_room
      - light.office_light
      - switch.wemo_insight__nasteanas
      - switch.guest_room_tv
      - camera.octopi
      - camera.rfpi
      - media_player.brightcast

  office_lights:
    name: Office Lights
    view: no
    icon: mdi:lightbulb
    entities:
      - light.gateway_light_34ce008d7aba
      - light.guest_room
      - light.office_light

  living_room:
    name: Living Room
    view: yes
    icon: mdi:sofa
    entities:
      - group.living_room_media_player_scripts
      - light.living_room_light_tv
      - light.living_room_light_table
      - light.front_door
      - light.terrace
      - scene.living_room_normal
      - scene.living_room_dim
      - switch.wall_socket
      - camera.c1
      - group.living_room_media_players

  living_room_media_players:
    name: Media Players
    view: no
    entities:
      - media_player.tv
      - media_player.sony_srszr7

  living_room_media_player_scripts:
    name: TV Activities
    control: hidden
    view: no
    entities:
      - input_select.tv_activity
      - sensor.harmony_hub
      - script.amp_toggle
      - script.tv_activity_dolphin_emu
      - script.tv_activity_kodi
      - script.tv_activity_ps3
      - script.tv_activity_shield_tv
      - script.tv_activity_watch_tv
      - script.wake_nvidia_shield
      - script.harmony_power_off
      - script.turn_off_media_players

  terrace:
    name: Terrace
    view: yes
    icon: mdi:tree
    entities:
      - group.weather_outdoor
      - group.all_plants
      - script.refresh_plant_data
      - camera.winpi
      - light.terrace
      - script.smoke_break
      - binary_sensor.door_window_sensor_158d0001a1ec56

  kitchen:
    name: Kitchen
    view: yes
    icon: mdi:food-fork-drink
    entities:
      - camera.c2
      - light.kitchen_light
      - group.fridge

# vim: set filetype=yaml et sw=2 ts=2 :
