vacuum:
  - platform: roomba
    name: Nimbus
    host: !secret roomba_hostname
    username: !secret roomba_username
    password: !secret roomba_password
    continuous: True


binary_sensor:
  - platform: template
    sensors:
      roomba_bin_full:
        friendly_name: Roomba Bin Full
        value_template: '{{ states.vacuum.nimbus.attributes.bin_full }}'
        entity_id: vacuum.nimbus


sensor:
  - platform: template
    sensors:
      nimbus_status:
        friendly_name: 'Nimbus Status'
        value_template: '{{ states.vacuum.nimbus.attributes.status }}'
        entity_id: vacuum.nimbus


alert:
  bin_full:
    name: "The bin is full"
    entity_id: binary_sensor.roomba_bin_full
    state: true
    repeat: 10
    can_acknowledge: True
    skip_first: False
    notifiers:
      - roomba_bin_full


automation:
  - alias: Schedule cleaning when nobody is home
    trigger:
      - platform: time
        at: '14:00:00'
    condition:
      - condition: state
        entity_id: group.main_mobile_devices
        state: not_home
    action:
      - service: vacuum.turn_on
        data:
          entity_id: vacuum.nimbus

  - alias: "Stop cleaning procedure if any of use comes home"
    trigger:
      - platform: state
        entity_id: device_tracker.n5x_zanzito
        to: home
      - platform: state
        entity_id: device_tracker.n5x_arp
        to: home
      - platform: state
        entity_id: device_tracker.her_phone
        to: home
    condition:
      - condition: state
        entity_id: vacuum.nimbus
        state: 'on'
    action:
      - service: vacuum.return_to_base
        data:
          entity_id: vacuum.nimbus

  - alias: "Notify when roomba is stuck and I'm coming home"
    trigger:
      - platform: state
        entity_id: device_tracker.n5x_zanzito
        to: home
    condition:
      - condition: template
        value_template: '{{ states.vacuum.nimbus.attributes.status != "Charging" }}'
    action:
      - service: notify.html5
        data_template:
          message: "Nimbus is {{ states.vacuum.nimbus.attributes.status }}. Go rescue him!"
          data:
            tag: "nimbus-rescue"

  - alias: "Notify when roomba finished a job"
    trigger:
      - platform: state
        entity_id: sensor.nimbus_status
        to: 'Charging'
    condition:
      condition: template
      value_template: '{{ trigger.from_state.state != "" }}'
    action:
      - service: notify.html5
        data_template:
          message: 'Nimbus returned to its base and is charging now. He probably finished a job. Previous: "{{ trigger.from_state.state }}"'
          data:
            tag: 'nimbus-finished-job'


notify:
  - name: roomba_bin_full
    platform: group
    services:
      - service: html5
        data:
          message: "Nimbus' bin is full"
          data:
            tag: 'bin-full'
            renotify: True

# vim: set filetype=yaml et sw=2 ts=2 :
