input_boolean:
  sleepover:
    name: Having friends sleeping on the couch
    icon: mdi:account-box-outline


automation:
  - alias: React to my homecoming
    initial_state: false
    trigger:
      - platform: state
        entity_id: device_tracker.g4p_zanzito
        from: not_home
        to: home
    action:
      - service: script.im_home

  - alias: Talk to my wife when she gets home
    initial_state: false
    trigger:
      - platform: state
        entity_id: device_tracker.her_phone
        from: not_home
        to: home
    action:
      - service: script.she_is_home

  - alias: "Ask to buzz door open when approaching home"
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: proximity.home
        below: 100
    action:
      - service: notify.html5
        data:
          message: "You are approaching home. Wanna make me buzz you in?"
          data:
            tag: 'buzz-open-query'
            renotify: False
            actions:
              - action: buzz_open
                icon: https://materialdesignicons.com/api/download/icon/png/E357D5CD-7E42-463B-899A-7D7B038A3E31/48
                title: "Buzz Open"

  - alias: "HTML5 notification: Buzz open"
    initial_state: true
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: buzz_open
    action:
      - service: script.buzz_door_open_multiple

  - alias: Turn on front door light when I get up in the morning
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.toilet_light, light.bathroom_light
        to: 'on'
    condition:
      condition: time
      after: '05:00:00'
      before: '07:00:00'
    action:
      - service: script.morning_front_door_light

  - alias: Having friends sleeping on the couch
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.sleepover
    action:
      - service_template: >
          {% if states.input_boolean.sleepover.state == 'on' %}
            automation.turn_off
          {% else %}
            automation.turn_on
          {% endif %}
        entity_id: automation.turn_on_front_door_light_when_i_get_up_in_the_morning


script:
  im_home:
    alias: 'I am home'
    sequence:
      - service: notifiy.html5
        data:
          message: "You've just entered the 'Home' zone"

  she_is_home:
    alias: 'She is home'
    sequence:
      - service: notify.pushover
        data:
          message: 'Mimine just came home'
      - service: tts.google_say
        entity_id: media_player.living_room_speaker
        data:
          message: 'Salut Mimine. Bienvenue à la maison'

  let_me_in:
    alias: 'Let me in!'
    sequence:
      - service: script.alarm_disarm
      - service: script.unlock_door
      - delay:
          minutes: 5
      - service: script.lock_door

  morning_front_door_light:
    alias: "Turn on front door light for 15min in the morning"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
          entity_id: script.morning_front_door_light_off
      - service: light.turn_on
        data:
          entity_id: light.front_door_light
          color_name: white
          brightness: 217 # 85%
      - service: switch.turn_on
        data:
          entity_id: switch.doorpi_screen
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.morning_front_door_light_off

  morning_front_door_light_off:
    alias: "Turn off the front door light after 15min in the morning"
    sequence:
      - delay:
          minutes: 15
      - service: light.turn_off
        data:
          entity_id: light.front_door_light

# vim: set filetype=yaml et sw=2 ts=2 :
