input_boolean:
  sleepover:
    name: Having friends sleeping on the couch
    icon: mdi:account-box-outline


automation:
  - alias: React to my homecoming
    initial_state: false
    trigger:
      - platform: state
        entity_id: device_tracker.g4p_zanzito
        from: not_home
        to: home
    action:
      - service: script.im_home

  - alias: We left
    initial_state: true
    trigger:
      - platform: state
        entity_id: group.main_mobile_devices
        to: not_home
    action:
      - service: notify.html5
        data:
          message: "You (all) left. Should I turn everything off?"
          data:
            tag: "all-left-query"

  - alias: Turn on lights before sunset
    initial_state: true
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    condition:
      condition: state
      entity_id: group.main_mobile_devices
      state: home
    action:
      - service: light.turn_on
        entity_id: light.living_room
        data:
          color_name: white
          brightness: 150
          transition: 10

  - alias: Open some covers 15min before sun rises
    initial_state: true
    trigger:
      platform: sun
      event: sunrise
      offset: "-00:15:00"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.sleepover
          state: 'off'
        - condition: state
          entity_id: group.main_mobile_devices
          state: home
    action:
      - service: script.open_auto_covers

  - alias: Open bedroom covers at 10:00
    initial_state: true
    trigger:
      platform: time
      at: "10:00:00"
    condition:
      condition: state
      entity_id: group.main_mobile_devices
      state: home
    action:
      - service: script.open_bedroom_covers

  - alias: Shut the covers when the sun sets
    initial_state: true
    trigger:
      platform: sun
      event: sunset
      offset: '+01:00:00'
    action:
      - service: script.close_main_covers

  - alias: Talk to my wife when she gets home
    initial_state: false
    trigger:
      - platform: state
        entity_id: device_tracker.op3t_arp
        from: not_home
        to: home
    action:
      - service: script.she_is_home

  - alias: "Ask to buzz door open when approaching home"
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: proximity.home
        below: 60
    action:
      - service: notify.html5
        data:
          message: "You are approaching home. Wanna make me buzz you in?"
          data:
            tag: 'buzz-open-query'
            renotify: true
            actions:
              - action: buzz_open
                icon: https://materialdesignicons.com/api/download/icon/png/E357D5CD-7E42-463B-899A-7D7B038A3E31/48
                title: "Buzz Open"

  - alias: "HTML5 notification: Buzz open"
    initial_state: true
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: buzz_open
    action:
      - service: script.buzz_door_open_multiple
      - service: script.unlock_door
      - service: script.turn_on_homecoming_lights
      - service: script.alarm_disarm
      - service: script.open_all_covers_if_sun_is_up
      - service: cover.open_cover
        entity_id: cover.living_room_door

  - alias: Turn on front door light when I get up in the morning
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.toilet_light, light.bathroom_light
        to: 'on'
    condition:
      condition: time
      after: '05:00:00'
      before: '07:00:00'
    action:
      - service: script.morning_front_door_light

  - alias: Having friends sleeping on the couch
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.sleepover
    action:
      - service_template: >
          {% if states.input_boolean.sleepover.state == 'on' %}
            automation.turn_off
          {% else %}
            automation.turn_on
          {% endif %}
        entity_id: automation.turn_on_front_door_light_when_i_get_up_in_the_morning


script:
  im_home:
    alias: 'I am home'
    sequence:
      - service: notify.html5
        data:
          message: "You've just entered the 'Home' zone"
          data:
            tag: "homed"

  she_is_home:
    alias: 'She is home'
    sequence:
      - service: notify.pushover
        data:
          message: 'Mimine just came home'
      - service: tts.google_say
        entity_id: media_player.living_room_speaker
        data:
          message: 'Salut Mimine. Bienvenue à la maison'

  let_me_in:
    alias: 'Let me in!'
    sequence:
      - service: script.alarm_disarm
      - service: script.unlock_door
      - service: cover.open_cover
        entity_id: cover.living_room_door
      - delay:
          minutes: 15
      - service: script.lock_door

  morning_front_door_light:
    alias: "Turn on front door light for 15min in the morning"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
          entity_id: script.morning_front_door_light_off
      - service: light.turn_on
        data:
          entity_id: light.front_door_light
          color_name: white
          brightness: 217 # 85%
      - service: switch.turn_on
        data:
          entity_id: switch.doorpi_screen
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.morning_front_door_light_off

  morning_front_door_light_off:
    alias: "Turn off the front door light after 15min in the morning"
    sequence:
      - delay:
          minutes: 15
      - service: light.turn_off
        data:
          entity_id: light.front_door_light

  homecoming_lights:
    alias: "Turn on homecoming lights if it is dark"
    sequence:
      - condition: sun
        after: sunset
        after_offset: '-00:45:00'
      # - condition: state
      #   entity_id: sun.sun
      #   state: 'below_horizon'
      - service: notify.html5
        data:
          message: "Turning on the homecoming light scene"
      - service: scene.turn_on
        entity_id: scene.homecoming_lights


scene:
  - name: Homecoming lights
    entities:
      light.front_door:
        state: on
        transition: 3
        brightness: 150
        xy_color: [ 0.4448, 0.4066 ]
      light.living_room:
        state: on
        transition: 3
        brightness: 150
        xy_color: [ 0.4448, 0.4066 ]

# vim: set filetype=yaml et sw=2 ts=2 :
