switch:
  - platform: mqtt
    name: "Sonoff Bathroom"
    availability_topic: "tele/sonoff/LWT"
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true


binary_sensor:
  - platform: ping
    name: sonoff_bathroom
    host: sonoff-4431.lan
    count: 2
    scan_interval: 15


light:
  - platform: template
    lights:
      bathroom_mirror:
        friendly_name: "Bathroom Mirror Light"
        value_template: >
          {% if is_state('binary_sensor.sonoff_bathroom', 'off') %}
            off
          {% else %}
            {{ states('switch.sonoff_bathroom') }}
          {% endif %}
        turn_on:
          service: switch.turn_on
          entity_id: switch.sonoff_bathroom
        turn_off:
          service: switch.turn_off
          entity_id: switch.sonoff_bathroom


automation:
  - alias: Sync state of bathroom mirror light with bathroom light (ON)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.bathroom_light
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.bathroom_mirror

  - alias: Sync state of bathroom mirror light with bathroom light (OFF)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.bathroom_light
        to: 'off'
    action:
      service: light.turn_off
      entity_id: light.bathroom_mirror

# vim: set filetype=yaml et sw=2 ts=2 :
