tts:
  - platform: google
    cache_dir: /tmp/tts.cache
    time_memory: 900
    language: 'fr'

  - platform: voicerss
    api_key: !secret voicerss_api_key
    language: 'fr-fr'
    codec: mp3
    format: 8khz_8bit_mono


script:
  reset_tts_volume:
    sequence:
      - service: media_player.volume_mute
        data:
          entity_id: media_player.sony_office_speaker
          is_volume_muted: False
      - service: media_player.volume_set
        data:
          entity_id: media_player.sony_office_speaker
          volume_level: 0.4
      - service: media_player.volume_mute
        data:
          entity_id: media_player.sony_living_room_speaker
          is_volume_muted: False
      - service: media_player.volume_set
        data:
          entity_id: media_player.sony_living_room_speaker
          volume_level: 0.4

  tts_say:
    sequence:
      # - service: media_player.turn_on
      #   data:
      #     entity_id: media_player.home_group
      - service: script.reset_tts_volume
      - service: tts.google_say
        data_template:
          entity_id: media_player.home_group
          message: '{{ message }}'

# vim: set filetype=yaml et sw=2 ts=2 :
