sensor:
  - platform: command_line
    name: UPS Pico battery level
    command: !secret cmd_upspico_battery_level
    unit_of_measurement: '%'
    scan_interval: 120

  - platform: command_line
    name: UPS Pico power state
    command: !secret cmd_upspico_power_state
    unit_of_measurement: '%'
    scan_interval: 300


homeassistant:
  customize:
    sensor.ups_pico_battery_level:
      battery_device: true
      friendly_battery_device: UPS Pico

# vim: set filetype=yaml et sw=2 ts=2 :
