wemo:
  static:
    - wemo-insight-01.lan  # nasteanas
    - wemo-insight-02.lan  # washing machine


binary_sensor:
  - platform: template
    sensors:
      washing_machine:
        friendly_name: 'Washing Machine'
        delay_off:
          minutes: 2
        device_class: power
        value_template: '{{ states.switch.wemo_insight__washing_machine.attributes.state_detail == "on" }}'
        entity_id: switch.wemo_insight__washing_machine


sensor:
  - platform: template
    sensors:
      power_consumption_washing_machine:
        friendly_name: Washing Machine Power Consumption
        unit_of_measurement: W
        value_template: '{{ states.switch.wemo_insight__washing_machine.attributes.current_power_w }}'
  - platform: template
    sensors:
      power_consumption_nasteanas:
        friendly_name: NAS Power Consumption
        unit_of_measurement: W
        value_template: '{{ states.switch.wemo_insight__nasteanas.attributes.current_power_w }}'


automation:
  - alias: Notify when the washing machine has finished
    trigger:
      platform: state
      entity_id: binary_sensor.washing_machine
      from: "on"
      to: "off"
    action:
      service: notify.html5
      data:
        message: "The Washing Machine has finished its cycle"


homeassistant:
  customize:
    binary_sensor.washing_machine:
      icon: mdi:washing-machine
    switch.wemo_insight__nasteanas:
      icon: mdi:server-network
    switch.wemo_insight__washing_machine:
      icon: mdi:washing-machine

# vim: set filetype=yaml et sw=2 ts=2 :
