zabbix:
  host: monitor.comreset.io
  path: /
  ssl: true
  username: !secret zabbix_username
  password: !secret zabbix_password


sensor:
  - platform: zabbix
    triggers:
      name: rastapi
      hostids: [10135]
      individual: true

# vim: set filetype=yaml et sw=2 ts=2 :
