binary_sensor:
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor
    state_topic: "hassistant/states/binary_sensor/fibaro_system_fgsd002_smoke_sensor_sensor/state"
    payload_on: "on"
    payload_off: "off"


sensor:
  - platform: mqtt
    name: fibaro_system_fgsd002_alarm_level
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_alarm_level/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_alarm_type
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_alarm_type/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_burglar
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_burglar/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_general
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_general/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_heat
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_heat/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_heat_2
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_heat_2/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_power_management
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_power_management/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_smoke
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_smoke/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_smoke_2
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_smoke_2/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_sourcenodeid
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_sourcenodeid/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_system
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_system/state"
  - platform: mqtt
    name: fibaro_system_fgsd002_smoke_sensor_temperature
    state_topic: "hassistant/states/sensor/fibaro_system_fgsd002_smoke_sensor_temperature/state"

# vim: set filetype=yaml et sw=2 ts=2 :
