alarm_code: 0
base_url: travis_secret_16
cam_octopi_password: travis_secret_16
cam_octopi_username: travis_secret_16
cam_rfpi_password: travis_secret_16
cam_rfpi_username: travis_secret_16
cam_winpi_password: travis_secret_16
cam_winpi_username: travis_secret_16
cmd_shutdown_mushu: travis_secret_16
darksky_api_key: travis_secret_16
db_url: travis_secret_16
emby_api_key: travis_secret_16
fb_her_phone_number: 0
fb_my_phone_number: 0
fb_page_token: travis_secret_16
fcm_sender_id: 0
fcm_server_key: travis_secret_16
flic_button_black_1: travis_secret_16
flic_button_black_2: travis_secret_16
flic_button_message_1: travis_secret_16
flic_button_message_2: travis_secret_16
flic_button_message_3: travis_secret_16
flic_button_white_1: travis_secret_16
flic_button_white_2: travis_secret_16
foscam_c1_hostname: travis_secret_16
foscam_c1_password: travis_secret_16
foscam_c1_username: travis_secret_16
foscam_c2_hostname: travis_secret_16
foscam_c2_password: travis_secret_16
foscam_c2_username: travis_secret_16
google_maps_api_key: travis_secret_16
harmony_hub_device_altec_lansing_amp: 0
harmony_hub_device_living_room_tv: 0
harmony_hub_device_nvidia_shield_tv: 0
harmony_hub_device_orange_livebox_play_tv: 0
harmony_hub_device_sony_ps3: 0
home_elevation: 0
home_latitude: 0.0
home_longitude: 0.0
http_password: travis_secret_16
hue_sensor_bathroom_lux: travis_secret_16
hue_sensor_bathroom_presence: travis_secret_16
hue_sensor_bathroom_temp: travis_secret_16
hue_sensor_hallway_lux: travis_secret_16
hue_sensor_hallway_presence: travis_secret_16
hue_sensor_hallway_temp: travis_secret_16
hue_sensor_kitchen_lux: travis_secret_16
hue_sensor_kitchen_presence: travis_secret_16
hue_sensor_kitchen_temp: travis_secret_16
hue_sensor_toilet_lux: travis_secret_16
hue_sensor_toilet_presence: travis_secret_16
hue_sensor_toilet_temp: travis_secret_16
ifttt_key: travis_secret_16
kleenex_message: travis_secret_16
lan_ipv4_addr: travis_secret_16
lannouncer_hostname: travis_secret_16
lg_tv_mac_addr: 00:01:02:03:04:05
livebox_play_tv_setup_routing: travis_secret_16
mi_gw_api_key: travis_secret_16
mi_gw_mac: 00:01:02:03:04:05
mqtt_broker: travis_secret_16
mqtt_cert: ./config/hass/.travis/file
mqtt_password: travis_secret_16
mqtt_username: travis_secret_16
nello_password: travis_secret_16
nello_username: travis_secret_16
notify_free_key: travis_secret_16
notify_free_username: 0
notify_pushbullet_api_key: travis_secret_16
notify_pushover_api_key: travis_secret_16
notify_pushover_user_key: travis_secret_16
nuki_bridge: travis_secret_16
nuki_lock_id: 0
nuki_lock_url: travis_secret_16
nuki_lockngo_url: travis_secret_16
nuki_state_url: travis_secret_16
nuki_token: travis_secret_16
nuki_unlock_url: travis_secret_16
openweathermap_api_key: travis_secret_16
owrt_password: travis_secret_16
owrt_username: travis_secret_16
player_kodi_password: travis_secret_16
player_kodi_username: travis_secret_16
roomba_hostname: travis_secret_16
roomba_password: travis_secret_16
roomba_username: 0
shell_cmd_setup_routing: travis_secret_16
snap_public_url: travis_secret_16
snap_rdelete: travis_secret_16
snap_upload: travis_secret_16
twitter_access_token: travis_secret_16
twitter_access_token_secret: travis_secret_16
twitter_consumer_key: travis_secret_16
twitter_consumer_secret: travis_secret_16
voicerss_api_key: travis_secret_16
work_elevation: 0
work_latitude: 0.0
work_longitude: 0.0
zabbix_password: travis_secret_16
zabbix_username: travis_secret_16
zm_password: travis_secret_16
zm_username: travis_secret_16
