# HASS
base_url: travis_secret
db_url: travis_secret
http_password: travis_secret
ssl_crt_path: travis_secret
ssl_key_path: travis_secret

# Zones
google_maps_api_key: travis_secret
home_elevation: travis_secret
home_latitude: travis_secret
home_longitude: travis_secret
work_elevation: travis_secret
work_latitude: travis_secret
work_longitude: travis_secret

# Weather
openweathermap_api_key: travis_secret
darksky_api_key: travis_secret

# Misc
alarm_code: travis_secret
ifttt_key: travis_secret
mqtt_broker: travis_secret
mqtt_cert: travis_secret
mqtt_username: travis_secret
mqtt_password: travis_secret
voicerss_api_key: travis_secret

# Hue
hue_username: travis_secret
hue_sensor_bathroom_lux: travis_secret
hue_sensor_bathroom_presence: travis_secret
hue_sensor_bathroom_temp: travis_secret
hue_sensor_hallway_lux: travis_secret
hue_sensor_hallway_presence: travis_secret
hue_sensor_hallway_temp: travis_secret
hue_sensor_kitchen_lux: travis_secret
hue_sensor_kitchen_presence: travis_secret
hue_sensor_kitchen_temp: travis_secret
hue_sensor_toilet_lux: travis_secret
hue_sensor_toilet_presence: travis_secret
hue_sensor_toilet_temp: travis_secret

# Device trackers
owrt_username: travis_secret
owrt_password: travis_secret

# Cameras
android_cam_z3c_hostname: travis_secret
android_cam_z3c_password: travis_secret
android_cam_z3c_username: travis_secret
cam_octopi_password: travis_secret
cam_octopi_username: travis_secret
cam_rfpi_password: travis_secret
cam_rfpi_username: travis_secret
cam_winpi_password: travis_secret
cam_winpi_username: travis_secret
foscam_c1_hostname: travis_secret
foscam_c1_password: travis_secret
foscam_c1_username: travis_secret
foscam_c2_hostname: travis_secret
foscam_c2_password: travis_secret
foscam_c2_username: travis_secret
snap_public_url: travis_secret
snap_rdelete: travis_secret
snap_upload: travis_secret
zm_password: travis_secret
zm_username: travis_secret

# Media Players
harmony_hub_device_altec_lansing_amp: travis_secret
harmony_hub_device_living_room_tv: travis_secret
harmony_hub_device_nvidia_shield_tv: travis_secret
harmony_hub_device_orange_livebox_play_tv: travis_secret
harmony_hub_device_sony_ps3: travis_secret
lg_tv_mac_addr: travis_secret
livebox_play_tv_setup_routing: travis_secret
player_kodi_password: travis_secret
player_kodi_username: travis_secret

# Notifiers
fb_her_phone_number: travis_secret
fb_my_phone_number: travis_secret
fb_page_token: travis_secret
fcm_sender_id: travis_secret
fcm_server_key: travis_secret
lannouncer_hostname: travis_secret
notify_free_key: travis_secret
notify_free_username: travis_secret
notify_pushbullet_api_key: travis_secret
notify_pushover_api_key: travis_secret
notify_pushover_user_key: travis_secret
twitter_access_token: travis_secret
twitter_access_token_secret: travis_secret
twitter_consumer_key: travis_secret
twitter_consumer_secret: travis_secret

# Messages
kleenex_message: travis_secret
flic_button_message_1: travis_secret
flic_button_message_2: travis_secret
flic_button_message_3: travis_secret

# Lock
nello_username: travis_secret
nello_password: travis_secret
nuki_bridge: travis_secret
nuki_token: travis_secret
nuki_unlock_url: travis_secret
nuki_lock_url: travis_secret
nuki_lockngo_url: travis_secret
nuki_state_url: travis_secret
nuki_lock_id: travis_secret

# Flic
flic_button_black_1: travis_secret
flic_button_black_2: travis_secret
flic_button_white_1: travis_secret
flic_button_white_2: travis_secret

# Zabbix
zabbix_username: travis_secret
zabbix_password: travis_secret

# Roomba
roomba_hostname: travis_secret
roomba_username: travis_secret
roomba_password: travis_secret

# vim: set filetype=yaml et sw=2 ts=2 :
