binary_sensor:
  - platform: ping
    name: win81-gpu
    host: win81-gpu.lan


rest_command:
  kvm_restart_win81_gpu:
    url: http://nasteanas.lan:8993/kvm/win81-gpu/restart
  kvm_start_win81_gpu:
    url: http://nasteanas.lan:8993/kvm/win81-gpu/start
  kvm_stop_win81_gpu:
    url: http://nasteanas.lan:8993/kvm/win81-gpu/stop


script:
  turn_on_dolphin_emu:
    alias: "Turn on dolphin-emu host"
    sequence:
      - service: rest_command.kvm_start_win81_gpu

  turn_off_dolphin_emu:
    alias: "Turn off dolphin-emu host"
    sequence:
      # Stop VM
      - service: rest_command.kvm_stop_win81_gpu

  restart_dolphin_emu:
    alias: "Restart dolphin-emu"
    sequence:
      # Restart VM
      - service: rest_command.kvm_restart_win81_gpu

# vim: set filetype=yaml et sw=2 ts=2 :
