remote:
  - platform: harmony
    name: Harmony Hub
    host: harmonyhub.lan
    activity: "Watch TV"
    scan_interval: 30


sensor:
  - platform: template
    sensors:
      harmony_hub:
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
        friendly_name: 'Harmony Hub'


script:
  # Harmony Hub Activities
  harmony_activity_watch_tv:
    alias: "Harmony Hub: Activity -> Watch TV"
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Watch TV

  harmony_activity_play_ps3:
    alias: "Harmony Hub: Activity -> Play PS3"
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Play PS3

  harmony_power_off:
    alias: "Harmony Hub: Stop current activity"
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: PowerOff

  # Harmony Hub: Living Room TV
  harmony_turn_on_living_room_tv:
    alias: "Harmony Hub: Turn on the Living Room TV"
    sequence:
      service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: !secret harmony_hub_device_living_room_tv
        command: PowerOn

  harmony_turn_off_living_room_tv:
    alias: "Harmony Hub: Turn off the Living Room TV"
    sequence:
      service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: !secret harmony_hub_device_living_room_tv
        command: PowerOff

  harmony_set_living_room_tv_input:
    alias: "Harmony Hub: Set the input on the living room TV"
    sequence:
      - service: remote.send_command
        data_template:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_living_room_tv
          command: >
            {%- if source == "Nvidia Shield TV" -%}
              InputHdmi1
            {%- elif source == "Kinivo HDMI Splitter" -%}
              InputHdmi2
            {%- elif source == "Orange Livebox Play" -%}
              InputHdmi3
            {%- elif source == "Sony Playstation 3" -%}
              InputHdmi4
            {%- endif -%}

  tv_volume_mute:
    alias: Mute TV
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_living_room_tv
          command: Mute

  tv_volume_down:
    alias: Lower TV volume
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_living_room_tv
          command: VolumeDown

  tv_volume_up:
    alias: Increase TV volume
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_living_room_tv
          command: VolumeUp

  # Harmony Hub: Altec Lansing Amp
  amp_toggle:
    alias: Toggle the amp
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_altec_lansing_amp
          command: PowerToggle

  # Harmony Hub: Nvidia Shield TV
  harmony_turn_on_nvidia_shield_tv:
    alias: "Harmony Hub: Turn on Nvidia Shield TV"
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_nvidia_shield_tv
          command: PowerOn

  harmony_turn_off_nvidia_shield_tv:
    alias: "Harmony Hub: Turn off the Nvidia Shield TV"
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_nvidia_shield_tv
          command: PowerOff

  # Harmony Hub: Orange Livebox Play TV
  harmony_livebox_play_tv_send_power_key:
    alias: "Harmony Hub: Send Power key to Livebox Play TV"
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_orange_livebox_play_tv
          command: PowerToggle

  harmony_livebox_play_tv_send_return_key:
    alias: "Harmony Hub: Send Return key to Livebox Play TV"
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_orange_livebox_play_tv
          command: Return

  # Harmony Hub: Sony Playstation 3
  harmony_turn_on_sony_ps3:
    alias: "Harmony Hub: Turn on the Sony PS3"
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_sony_ps3
          command: PowerOn

  harmony_turn_off_sony_ps3:
    alias: "Harmony Hub: Turn off the Sony PS3"
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: !secret harmony_hub_device_sony_ps3
          command: PowerOff


homeassistant:
  customize:
    # Sensors
    sensor.harmony_hub:
      icon: mdi:remote
    # Scripts
    script.amp_toggle:
      icon: mdi:amplifier
    script.harmony_power_off:
      icon: mdi:stop-circle
    script.wake_nvidia_shield:
      icon: mdi:alarm
    script.tv_activity_watch_tv:
      icon: mdi:television
    script.tv_activity_shield_tv:
      icon: mdi:television-guide
    script.tv_activity_kodi:
      icon: mdi:kodi
    script.tv_activity_ps3:
      icon: mdi:gamepad-variant
    script.tv_activity_dolphin_emu:
      icon: mdi:fish

# vim: set filetype=yaml et sw=2 ts=2 :
