binary_sensor:
  - platform: ping
    name: brightcast
    host: chromecast.lan


script:
  turn_on_office_tv:
    alias: "Turn on the office TV"
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.office_tv

  turn_off_office_tv:
    alias: "Turn off the office TV"
    sequence:
      - service: switch.turn_off
        data:
          entity_id: switch.office_tv

  toggle_office_tv:
    alias: "Toggle the office TV"
    sequence:
      service: switch.toggle
      data:
        entity_id: switch.office_tv

# vim: set filetype=yaml et sw=2 ts=2 :
