media_player:
  - platform: sonyavr
    host: sony-living-room-speaker.lan
    name: Sony Living Room Speaker

  - platform: sonyavr
    host: sony-office-speaker.lan
    name: Sony Office Speaker


script:
  set_office_speaker_to_aux:
    sequence:
      service: media_player.select_source
      data:
        entity_id: media_player.sony_office_speaker
        source: "Audio In"

# vim: set filetype=yaml et sw=2 ts=2 :
