homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  base_url: !secret base_url
  server_port: 8123
  api_password: !secret http_password
  ssl_certificate: !secret ssl_crt_path
  ssl_key: !secret ssl_key_path
  ip_ban_enabled: False
  login_attempts_threshold: 5
  trusted_networks: !include trusted_networks.yaml

config:
conversation:
discovery:
  # DIRTY to avoid having a dupplicate Sony player
  # ignore:
  #   - google_cast

history:
logbook:
updater:
automation: !include_dir_merge_list automations
downloader: !include downloader.yaml
group: !include_dir_merge_named groups
ifttt: !include ifttt.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
pilight: !include pilight.yaml
prometheus:
recorder:
  purge_days: 3
  db_url: !secret db_url
script: !include_dir_merge_named scripts
sensor: !include sensor.yaml
shell_command: !include shell_command.yaml
sun:
switch: !include switch.yaml
zone: !include zone.yaml

# DIRTYFIX: Why can't apiai be in the package dir?
apiai:
intent_script: !include intent_script.yaml

# vim: set filetype=yaml et sw=2 ts=2 :
