homeassistant:
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  base_url: !secret base_url
  server_port: 8123
  api_password: !secret http_password
  login_attempts_threshold: 5
  use_x_forwarded_for: True

automation: !include_dir_merge_list automations
config:
conversation:
discovery:
downloader: !include downloader.yaml
group: !include_dir_merge_named groups
history:
ifttt: !include ifttt.yaml
logbook:
prometheus:
recorder:
  purge_interval: 3
  purge_keep_days: 5
  db_url: !secret db_url
sensor: !include sensor.yaml
sun:
updater:

# DIRTYFIX: Why can't apiai be in the package dir?
apiai:
intent_script: !include intent_script.yaml

# vim: set filetype=yaml et sw=2 ts=2 :
