# Sensors
sensor.transmission_down_speed:
  icon: mdi:download

# Scripts
script.all_off:
  icon: mdi:nuke
script.turn_off_media_players:
  icon: mdi:laptop-off
script.im_home:
  icon: mdi:home-map-marker
script.she_is_home:
  icon: mdi:home-map-marker
script.tell_my_wife_i_love_her:
  icon: mdi:heart

# Switches
switch.tv:
  icon: mdi:power-plug
  assumed_state: true

# vim: set filetype=yaml et sw=2 ts=2
