switch.wemo_insight__washing_machine:
  platform: wemo
  unique_id: 221517K1200027
switch.wemo_insight__nasteanas:
  platform: wemo
  unique_id: 221623K1200499
media_player.emby__dlna__shield_android_tves1070241:
  platform: emby
  unique_id: uuid:11dbdbf7-e4af-7676-0000-000038b27980.DLNA
media_player.emby__dlna__living_room_speaker:
  platform: emby
  unique_id: uuid:00000000-0000-1010-8000-8c579b3def7f.DLNA
media_player.emby__dlna__office_speaker:
  platform: emby
  unique_id: uuid:00000000-0000-1010-8000-8c579b4d09fc.DLNA
media_player.emby__emby_for_android_mobile__nexus_7:
  platform: emby
  unique_id: 69091b9de168a2.Emby for Android Mobile
binary_sensor.fibaro_system_fgsd002_smoke_sensor_sensor:
  platform: zwave
  unique_id: 8-72057594177126400
sensor.fibaro_system_fgsd002_smoke_sensor_temperature:
  platform: zwave
  unique_id: 8-72057594177142802
sensor.fibaro_system_fgsd002_smoke_sensor_alarm_type:
  platform: zwave
  unique_id: 8-72057594178191361
sensor.fibaro_system_fgsd002_smoke_sensor_alarm_level:
  platform: zwave
  unique_id: 8-72057594178191377
sensor.fibaro_system_fgsd002_smoke_sensor_sourcenodeid:
  platform: zwave
  unique_id: 8-72057594178191393
sensor.fibaro_system_fgsd002_smoke_sensor_smoke:
  platform: zwave
  unique_id: 8-72057594178191425
sensor.fibaro_system_fgsd002_smoke_sensor_heat:
  platform: zwave
  unique_id: 8-72057594178191473
sensor.fibaro_system_fgsd002_smoke_sensor_burglar:
  platform: zwave
  unique_id: 8-72057594178191521
sensor.fibaro_system_fgsd002_smoke_sensor_power_management:
  platform: zwave
  unique_id: 8-72057594178191537
sensor.fibaro_system_fgsd002_smoke_sensor_system:
  platform: zwave
  unique_id: 8-72057594178191553
sensor.fibaro_system_fgsd002_smoke_sensor_general:
  platform: zwave
  unique_id: 8-72057594178895873
sensor.fibaro_system_fgsd002_smoke_sensor_smoke_2:
  platform: zwave
  unique_id: 8-72057594178895889
sensor.fibaro_system_fgsd002_smoke_sensor_heat_2:
  platform: zwave
  unique_id: 8-72057594178895937
light.toilet_light:
  platform: hue
  unique_id: 00:17:88:01:10:3c:cc:eb-0b
light.office_light:
  platform: hue
  unique_id: 00:17:88:01:10:55:61:4c-0b
light.bathroom_light:
  platform: hue
  unique_id: 00:17:88:01:10:31:6b:66-0b
light.hallway_light:
  platform: hue
  unique_id: 00:17:88:01:10:31:6d:22-0b
light.terrace_light:
  platform: hue
  unique_id: 00:17:88:01:00:ee:cc:52-0b
light.kitchen_light:
  platform: hue
  unique_id: 00:17:88:01:10:4d:19:cc-0b
light.front_door_light:
  platform: hue
  unique_id: 00:17:88:01:10:47:17:d9-0b
light.living_room_tv_light:
  platform: hue
  unique_id: 00:17:88:01:00:d8:f2:08-0b
light.bedroom_light:
  platform: hue
  unique_id: 00:17:88:01:10:55:37:50-0b
light.living_room_table_light:
  platform: hue
  unique_id: 00:17:88:01:00:ec:a1:39-0b
media_player.emby__dlna__lg_webos_tv_oled55b6v:
  platform: emby
  unique_id: uuid:29fdfaee-3874-fddf-3ae6-233b97de7229.DLNA
media_player.emby__android__moto_g_play:
  platform: emby
  unique_id: acb13a928ee387a8.Android
media_player.emby__emby_for_android_mobile__moto_g_play:
  platform: emby
  unique_id: acb13a928ee387a8.Emby for Android Mobile
media_player.emby__emby_mobile__chrome:
  platform: emby
  unique_id: 315ef9cc091715ada1b8d2c4cffa445ec3a7bba0.Emby Mobile
media_player.emby__emby_for_chromecast__nvidia_shield_tv:
  platform: emby
  unique_id: 3e53ffff2c6ae6550fb3530803332b146b066d25.Emby for Chromecast
