switch.wemo_insight__washing_machine:
  name:
  platform: wemo
  unique_id: 221517K1200027
switch.wemo_insight__nasteanas:
  name:
  platform: wemo
  unique_id: 221623K1200499
media_player.emby__dlna__shield_android_tves1070241:
  name:
  platform: emby
  unique_id: uuid:11dbdbf7-e4af-7676-0000-000038b27980.DLNA
media_player.emby__dlna__living_room_speaker:
  name:
  platform: emby
  unique_id: uuid:00000000-0000-1010-8000-8c579b3def7f.DLNA
media_player.emby__dlna__office_speaker:
  name:
  platform: emby
  unique_id: uuid:00000000-0000-1010-8000-8c579b4d09fc.DLNA
media_player.emby__emby_for_android_mobile__nexus_7:
  name:
  platform: emby
  unique_id: 69091b9de168a2.Emby for Android Mobile
light.hue_toilet:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:3c:cc:eb-0b
light.hue_office:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:55:61:4c-0b
light.hue_bathroom:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:31:6b:66-0b
light.hue_hallway:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:31:6d:22-0b
light.hue_terrace:
  name:
  platform: hue
  unique_id: 00:17:88:01:00:ee:cc:52-0b
light.hue_kitchen:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:4d:19:cc-0b
light.hue_front_door:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:47:17:d9-0b
light.hue_living_room_tv:
  name:
  platform: hue
  unique_id: 00:17:88:01:00:d8:f2:08-0b
light.hue_bedroom:
  name:
  platform: hue
  unique_id: 00:17:88:01:10:55:37:50-0b
light.hue_living_room_table:
  name:
  platform: hue
  unique_id: 00:17:88:01:00:ec:a1:39-0b
media_player.emby__dlna__lg_webos_tv_oled55b6v:
  name:
  platform: emby
  unique_id: uuid:29fdfaee-3874-fddf-3ae6-233b97de7229.DLNA
media_player.emby__android__moto_g_play:
  name:
  platform: emby
  unique_id: acb13a928ee387a8.Android
media_player.emby__emby_for_android_mobile__moto_g_play:
  name:
  platform: emby
  unique_id: acb13a928ee387a8.Emby for Android Mobile
media_player.emby__emby_mobile__chrome:
  name:
  platform: emby
  unique_id: 315ef9cc091715ada1b8d2c4cffa445ec3a7bba0.Emby Mobile
media_player.emby__emby_for_chromecast__nvidia_shield_tv:
  name:
  platform: emby
  unique_id: 3e53ffff2c6ae6550fb3530803332b146b066d25.Emby for Chromecast
media_player.emby__emby_mobile__chrome_2:
  name:
  platform: emby
  unique_id: 90dc8dab531c69d61954dadc9f8319b742a6d829.Emby Mobile
media_player.emby__emby_for_chromecast__office_tv:
  name:
  platform: emby
  unique_id: 583d4306d0aa1dad157235e77ac5e66725f97efc.Emby for Chromecast
media_player.emby__emby_mobile__chrome_android:
  name:
  platform: emby
  unique_id: b834ea37502fe02e396b7307fc72bc4d46583a83.Emby Mobile
media_player.emby__dlna__shield_android_tves1070241_2:
  name:
  platform: emby
  unique_id: uuid:d000cbcf-72ff-0f07-0000-000038b27980.DLNA
binary_sensor.door_window_sensor_terrace_door:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001a1ec56
binary_sensor.door_window_sensor_office_window_large:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001de7941
binary_sensor.door_window_sensor_kitchen_window:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001de8c01
binary_sensor.motion_sensor_front_door:
  name:
  platform: xiaomi_aqara
  unique_id: status158d000224f5b8
binary_sensor.door_window_sensor_bedroom_terrace_door:
  name:
  platform: xiaomi_aqara
  unique_id: status158d00016572aa
binary_sensor.wall_switch_bedroom_both:
  name:
  platform: xiaomi_aqara
  unique_id: dual_channel158d00016404f4
binary_sensor.door_window_sensor_office_window_small:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001de8caa
binary_sensor.water_leak_sensor_bathroom_sink:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001d7668e
binary_sensor.wall_switch_office_both:
  name:
  platform: xiaomi_aqara
  unique_id: dual_channel158d0001e0f920
binary_sensor.door_window_sensor_bedroom_window:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001de639e
binary_sensor.water_leak_sensor_kitchen_sink:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001df1cc3
binary_sensor.wall_switch_office_left:
  name:
  platform: xiaomi_aqara
  unique_id: channel_0158d0001e0f920
binary_sensor.wall_switch_bedroom_right:
  name:
  platform: xiaomi_aqara
  unique_id: channel_1158d00016404f4
binary_sensor.wall_switch_bedroom_left:
  name:
  platform: xiaomi_aqara
  unique_id: channel_0158d00016404f4
binary_sensor.door_window_sensor_living_room_window:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001de8cb8
binary_sensor.bedroom_switch:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0002132e08
binary_sensor.door_window_sensor_fridge_door:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001a1eb5b
binary_sensor.wall_switch_office_right:
  name:
  platform: xiaomi_aqara
  unique_id: channel_1158d0001e0f920
binary_sensor.door_window_sensor_front_door:
  name:
  platform: xiaomi_aqara
  unique_id: status158d00016d7083
sensor.illumination_gateway:
  name:
  platform: xiaomi_aqara
  unique_id: illumination34ce008d7aba
sensor.motion_sensor_illumination_front_door:
  name:
  platform: xiaomi_aqara
  unique_id: lux158d000224f5b8
sensor.temperature_freezer:
  name:
  platform: xiaomi_aqara
  unique_id: temperature158d0001d6f4e5
sensor.humidity_freezer:
  name:
  platform: xiaomi_aqara
  unique_id: humidity158d0001d6f4e5
sensor.pressure_freezer:
  name:
  platform: xiaomi_aqara
  unique_id: pressure158d0001d6f4e5
sensor.temperature_fridge:
  name:
  platform: xiaomi_aqara
  unique_id: temperature158d0001d6f4da
sensor.humidity_fridge:
  name:
  platform: xiaomi_aqara
  unique_id: humidity158d0001d6f4da
sensor.pressure_fridge:
  name:
  platform: xiaomi_aqara
  unique_id: pressure158d0001d6f4da
media_player.cast_office_tv:
  name:
  platform: cast
  unique_id: 87bcfe24-ecf7-0376-d1c5-fb67d3eda623
media_player.cast_office_speaker:
  name:
  platform: cast
  unique_id: 896d643e-90cf-c1f7-e37b-11cd5b6efba2
media_player.cast_nvidia_shield_tv:
  name:
  platform: cast
  unique_id: 648bc1b3-4172-fe95-41dc-3c9bd6ce128e
media_player.cast_living_room_speaker:
  name:
  platform: cast
  unique_id: f6d1e511-8e5e-d1ab-a485-6fb7b7c01ad9
media_player.cast_home_group:
  name:
  platform: cast
  unique_id: 3409096f-da2a-420f-a423-9bf807389881
light.gateway_light_gateway:
  name:
  platform: xiaomi_aqara
  unique_id: rgb34ce008d7aba
media_player.emby__dlna__shield_android_tves1070241_3:
  name:
  platform: emby
  unique_id: uuid:72907f47-b824-b6c8-0000-000038b27980.DLNA
media_player.emby__dlna__shield_android_tves1070241_4:
  name:
  platform: emby
  unique_id: uuid:65a643f8-6f80-61c4-0000-000038b27980.DLNA
media_player.emby__dlna__shield_android_tves1070241_5:
  name:
  platform: emby
  unique_id: uuid:697d655f-51f9-edf4-0000-000038b27980.DLNA
media_player.emby__dlna__shield_android_tves1070241_6:
  name:
  platform: emby
  unique_id: uuid:ea8af96e-4d9f-2b86-0000-000038b27980.DLNA
media_player.emby__dlna__shield_android_tves1070241_7:
  name:
  platform: emby
  unique_id: uuid:73cd0762-b525-b9b8-0000-000038b27980.DLNA
media_player.emby__dlna__shield_android_tves1070241_8:
  name:
  platform: emby
  unique_id: uuid:7b32bbd0-add1-5501-0000-000038b27980.DLNA
media_player.emby__emby_mobile__chrome_3:
  name:
  platform: emby
  unique_id: 8e51e6e679839dbd2c32617272d61aefd17cd368.Emby Mobile
media_player.office_speaker:
  name:
  platform: songpal
  unique_id: 10-4f-a8-ac-46-76
media_player.living_room_speaker:
  name:
  platform: songpal
  unique_id: 10-4f-a8-81-4b-1d
media_player.emby__emby_for_chromecast__nvidia_shield_tv_2:
  name:
  platform: emby
  unique_id: TnZpZGlhIFNoaWVsZCBUVg==.Emby for Chromecast
media_player.emby__androidtv__nvidia_shield_android_tv:
  name:
  platform: emby
  unique_id: ec6d495b495d9c9a.AndroidTv
media_player.emby__dlna__shield_android_tves1070241_9:
  name:
  platform: emby
  unique_id: uuid:5302a122-422a-0e76-0000-000038b27980.DLNA
media_player.emby__emby_for_chromecast__living_room_tv:
  name:
  platform: emby
  unique_id: TGl2aW5nIFJvb20gVFY=.Emby for Chromecast
media_player.emby__dlna__shield_android_tves1070241_10:
  name:
  platform: emby
  unique_id: uuid:be1589c8-bccc-4ee5-0000-000038b27980.DLNA
sensor.temperature_terrace:
  name:
  platform: xiaomi_aqara
  unique_id: temperature158d00022cbbf0
sensor.humidity_terrace:
  name:
  platform: xiaomi_aqara
  unique_id: humidity158d00022cbbf0
sensor.pressure_terrace:
  name:
  platform: xiaomi_aqara
  unique_id: pressure158d00022cbbf0
binary_sensor.water_leak_sensor_bathtub:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001c32be7
binary_sensor.motion_sensor_terrace:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001a92ad8
sensor.temperature_living_room:
  name:
  platform: xiaomi_aqara
  unique_id: temperature158d00022cbbc8
sensor.humidity_living_room:
  name:
  platform: xiaomi_aqara
  unique_id: humidity158d00022cbbc8
sensor.pressure_living_room:
  name:
  platform: xiaomi_aqara
  unique_id: pressure158d00022cbbc8
binary_sensor.motion_sensor_living_room:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001a92ccf
sensor.temperature_bedroom:
  name:
  platform: xiaomi_aqara
  unique_id: temperature158d00022cbbbb
sensor.humidity_bedroom:
  name:
  platform: xiaomi_aqara
  unique_id: humidity158d00022cbbbb
sensor.pressure_bedroom:
  name:
  platform: xiaomi_aqara
  unique_id: pressure158d00022cbbbb
binary_sensor.motion_sensor_office:
  name:
  platform: xiaomi_aqara
  unique_id: status158d0001a915ca
switch.wall_switch_bathroom_left:
  name:
  platform: xiaomi_aqara
  unique_id: channel_0158d0002238c8a
switch.wall_switch_bathroom_right:
  name:
  platform: xiaomi_aqara
  unique_id: channel_1158d0002238c8a
media_player.emby__dlna__shield_android_tves1070241_11:
  name:
  platform: emby
  unique_id: uuid:ccb0042c-1d8d-2648-0000-000038b27980.DLNA
media_player.emby__dlna__shield_android_tves1070241_12:
  name:
  platform: emby
  unique_id: uuid:00663054-313f-12fb-0000-000038b27980.DLNA
media_player.emby__emby_mobile__chrome_4:
  name:
  platform: emby
  unique_id: a725c07bcada5183bc4b362fc162aa6fa9ec6767.Emby Mobile
media_player.emby__emby_mobile__chrome_5:
  name:
  platform: emby
  unique_id: 88bc44636b3bc03a5bcca892bc1bd27c91df8098.Emby Mobile
media_player.emby__radarr__nasteanas:
  name:
  platform: emby
  unique_id: 9925a8802c374bd69ec2eb5674129f17.Radarr
media_player.emby__sonarr__nasteanas:
  name:
  platform: emby
  unique_id: 9925a8802c374bd69ec2eb5674129f17.Sonarr
media_player.emby__dlna__shield_android_tves1070241_13:
  name:
  platform: emby
  unique_id: uuid:bb5d954e-c03b-274f-0000-000038b27980.DLNA
sensor.pws_precip_1d:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,precip_1d'
sensor.pws_weather_2d_metric:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,weather_2d_metric'
sensor.pws_precip_today_metric:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,precip_today_metric'
sensor.pws_wind_string:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,wind_string'
sensor.pws_alerts:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,alerts'
sensor.pws_precip_today_string:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,precip_today_string'
sensor.pws_temp_c:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,temp_c'
sensor.pws_feelslike_c:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,feelslike_c'
sensor.pws_weather:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,weather'
sensor.pws_feelslike_string:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,feelslike_string'
sensor.pws_weather_1d_metric:
  name:
  platform: wunderground
  unique_id: '@6.172700,49.119100,weather_1d_metric'
zwave.sigma_designs_uzb_zwave_usb_adapter:
  name:
  platform: zwave
  unique_id: node-1
media_player.emby__emby_mobile__chrome_6:
  name:
  platform: emby
  unique_id: c39e762677870158c74bf39db4fd23c2b843ab39.Emby Mobile
media_player.emby__dlna__network_device:
  name:
  platform: emby
  unique_id: uuid:0c1c62de-209c-906f-0000-000038b27980.DLNA
media_player.emby__dlna__shield_android_tves1070241_14:
  name:
  platform: emby
  unique_id: uuid:1a5344e6-5c15-34fa-0000-000038b27980.DLNA
