- alias: Ensure the livebox-play is turned off when stopping it using Harmony Hub
  trigger:
    - platform: state
      entity_id: remote.harmony_hub
  condition:
    condition: template
    value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" and trigger.from_state.attributes.current_activity == "Watch TV" }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.livebox_play

- alias: Ensure the livebox-play is turned on when starting TV using Harmony Hub
  trigger:
    - platform: state
      entity_id: remote.harmony_hub
  condition:
    condition: template
    value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV" }}'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.livebox_play

# vim: set filetype=yaml et sw=2 ts=2 :
