all_off:
  alias: All off
  sequence:
    - service: notify.zanzito_tts
      data:
        message: "Brace yourself: Shutdown is coming."
    - service: script.turn_off_media_players
    - service: script.turn_off_guest_room_tv
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_lights

bedtime:
  alias: Bedtime
  sequence:
    - service: notify.zanzito_tts
      data:
        message: "Night."
    - service: scene.turn_on
      data:
        entity_id: scene.bedtime
    - service: script.lock_door
    - service: script.turn_off_guest_room_tv
    - service: light.turn_off
      data:
        entity_id: group.office_lights

# vim: set filetype=yaml et sw=2 ts=2 :
