- alias: Hauppauge remote KEY_POWER pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_power_pressed
  action:
    service: script.turn_on
    entity_id: script.watch_tv

- alias: Hauppauge remote KEY_STOP pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_stop_pressed
  action:
    service: script.turn_on
    entity_id: script.all_off

- alias: Hauppauge remote KEY_EPG pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_epg_pressed
  action:
    service: script.turn_on
    entity_id: script.shield_tv

- alias: Hauppauge remote KEY_LIST pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_list_pressed
  action:
    service: script.turn_on
    entity_id: script.start_kodi

- alias: Hauppauge remote KEY_MUTE pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_mute_pressed
  action:
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: 40563642
        command: Mute

- alias: Hauppauge remote KEY_VOLUMEDOWN pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_volumedown_pressed
  action:
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: 40563642
        command: VolumeDown

- alias: Hauppauge remote KEY_VOLUMEUP pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_volumeup_pressed
  action:
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: 40563642
        command: VolumeUp

- alias: Hauppauge remote KEY_CHANNELDOWN pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_channeldown_pressed
  action:
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: 40565609
        command: ChannelDown

- alias: Hauppauge remote KEY_CHANNELUP pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_channelup_pressed
  action:
    - service: remote.send_command
      data:
        entity_id: remote.harmony_hub
        device: 40565609
        command: ChannelUp

- alias: Hauppauge remote KEY_0 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_0_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number0
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 0

- alias: Hauppauge remote KEY_1 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_1_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number1
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 1

- alias: Hauppauge remote KEY_2 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_2_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number2
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 2

- alias: Hauppauge remote KEY_3 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_3_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number3
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 3

- alias: Hauppauge remote KEY_4 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_4_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number4
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 4

- alias: Hauppauge remote KEY_5 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_5_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number5
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 5

- alias: Hauppauge remote KEY_6 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_6_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number6
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 6

- alias: Hauppauge remote KEY_7 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_7_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number7
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 7

- alias: Hauppauge remote KEY_8 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_8_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number8
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 8

- alias: Hauppauge remote KEY_9 pressed
  initial_state: true
  trigger:
    - platform: event
      event_type: remote_hauppauge_key_9_pressed
  action:
    # - service: remote.send_command
    #   data:
    #     entity_id: remote.harmony_hub
    #     device: 40565609
    #     command: Number9
    - service: shell_command.remote_livebox_play
      data:
        key: num_key 9

# vim: set filetype=yaml et sw=2 ts=2 :
