automation:
  - alias: Amazon Dash Button (Kleenex) pressed
    trigger:
      - platform: event
        event_type: dash_button_kleenex_pressed
    action:
      - service: script.dash_button_kleenex_pressed

  - alias: Amazon Dash Button (Durex) pressed
    trigger:
      - platform: event
        event_type: dash_button_durex_pressed
    action:
      - service: script.dash_button_durex_pressed


script:
  dash_button_kleenex_pressed:
    alias: 'Kleenex Dash button pressed'
    sequence:
      - service: logbook.log
        data:
          name: Kleenex dash button
          message: pressed
      - service: notify.dash_pressed
        data:
          message: kleenex
      - service: light.toggle
        entity_id: light.living

  dash_button_durex_pressed:
    alias: 'Durex Dash button pressed'
    sequence:
      - service: logbook.log
        data:
          name: Durex dash button
          message: pressed
      - service: notify.dash_pressed
        data:
          message: durex
      - service: script.smoke_break

# vim: set filetype=yaml et sw=2 ts=2 :
