automation:
  - alias: Amazon Dash Button (Kleenex) pressed
    trigger:
      - platform: event
        event_type: dash_button_kleenex_pressed
    action:
      - service: script.dash_button_kleenex_pressed

  - alias: Amazon Dash Button (Durex) pressed
    trigger:
      - platform: event
        event_type: dash_button_durex_pressed
    action:
      - service: script.dash_button_durex_pressed


script:
  dash_button_kleenex_pressed:
    alias: 'Kleenex Dash button pressed'
    sequence:
      - service: logbook.log
        data:
          name: Kleenex dash button
          message: pressed
      - service: notify.dash_pressed
        data:
          message: kleenex
      - service: light.toggle
        entity_id: light.living_room

  dash_button_durex_pressed:
    alias: 'Durex Dash button pressed'
    sequence:
      - service: logbook.log
        data:
          name: Durex dash button
          message: pressed
      - service: notify.dash_pressed
        data:
          message: durex
      - service: switch.toggle
        entity_id: switch.guest_room_tv


homeassistant:
  customize:
    - entity_id: script.dash_button_kleenex_pressed
      icon: mdi:arrow-up-drop-circle
    - entity_id: script.dash_button_durex_pressed
      icon: mdi:arrow-up-drop-circle-outline

# vim: set filetype=yaml et sw=2 ts=2 :
