android_ip_webcam:
  - host: z3c.lan
    name: Z3C
    username: !secret android_cam_z3c_username
    password: !secret android_cam_z3c_password
    motion_sensor: True

camera:
  # - platform: zoneminder

  - platform: foscam
    name: C1
    ip: !secret foscam_c1_hostname
    username: !secret foscam_c1_username
    password: !secret foscam_c1_password

  - platform: foscam
    name: C2
    ip: !secret foscam_c2_hostname
    username: !secret foscam_c2_username
    password: !secret foscam_c2_password

  - platform: mjpeg
    name: octopi
    mjpeg_url: http://octopi.lan:8089/?action=stream
    authentication: basic
    username: !secret cam_octopi_username
    password: !secret cam_octopi_password

  - platform: mjpeg
    name: rfpi
    mjpeg_url: http://rfpi.lan:8089/?action=stream
    authentication: basic
    username: !secret cam_rfpi_username
    password: !secret cam_rfpi_password

  - platform: mjpeg
    name: winpi
    mjpeg_url: http://winpi.lan:8089/?action=stream
    authentication: basic
    username: !secret cam_winpi_username
    password: !secret cam_winpi_password


zoneminder:
  host: nasteanas.lan:10080
  path: /zm/
  ssl: false
  # username: !secret zm_username
  # password: !secret zm_password


sensor:
  - platform: zoneminder

  - platform: command_line
    name: 'Z3C Battery'
    command: /scripts/android-cam.sh z3c battery
    unit_of_measurement: '%'


switch:
  - platform: zoneminder
    command_on: Modect
    command_off: Monitor

  - platform: command_line
    switches:
      z3c_cam:
        command_on: /scripts/android-cam.sh z3c cam on
        command_off: /scripts/android-cam.sh z3c cam off
        command_state: /scripts/android-cam.sh z3c cam state
        friendly_name: "Z3C Camera"
      c1_ir:
        command_on: /scripts/foscam.sh c1 ir on
        command_off: /scripts/foscam.sh c1 ir off
        command_state: /scripts/foscam.sh c1 ir state
        friendly_name: "C1 Night Mode"
      c2_ir:
        command_on: /scripts/foscam.sh c2 ir on
        command_off: /scripts/foscam.sh c2 ir off
        command_state: /scripts/foscam.sh c2 ir state
        friendly_name: "C2 Night Mode"
      c1_modect:
        command_on: /scripts/foscam.sh c1 modect on
        command_off: /scripts/foscam.sh c1 modect off
        command_state: /scripts/foscam.sh c1 modect state
        friendly_name: "C1 Foscam Motion Detection"
      c2_modect:
        command_on: /scripts/foscam.sh c2 modect on
        command_off: /scripts/foscam.sh c2 modect off
        command_state: /scripts/foscam.sh c2 modect state
        friendly_name: "C2 Foscam Motion Detection"
      c1_sodect:
        command_on: /scripts/foscam.sh c1 sodect on
        command_off: /scripts/foscam.sh c1 sodect off
        command_state: /scripts/foscam.sh c1 sodect state
        friendly_name: "C1 Foscam Audio Detection"
      c2_sodect:
        command_on: /scripts/foscam.sh c2 sodect on
        command_off: /scripts/foscam.sh c2 sodect off
        command_state: /scripts/foscam.sh c2 sodect state
        friendly_name: "C2 Foscam Audio Detection"


shell_command:
  cam_snap: /scripts/hass.sh snap {{ cam }} /tmp/snap_{{ cam }}.jpg
  snap_upload: !secret snap_upload
  snap_ldelete: "rm -f /tmp/snap_*.jpg"
  snap_rdelete: !secret snap_rdelete


script:
  z3c_restart:
    alias: Reboot Z3C
    sequence:
      - event: LOGBOOK_ENTRY
        event_data:
          name: Sony Z3C
          message: rebooted
          domain: camera
      - service: shell_command.z3c_restart

  snap_c1:
    alias: Grab a picture from C1
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: c1

  snap_c2:
    alias: Grab a picture from C2
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: c2

  snap_octopi:
    alias: Grab a picture from octopi
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: octopi

  snap_rfpi:
    alias: Grab a picture from rfpi
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: rfpi

  snap_winpi:
    alias: Grab a picture from winpi
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: winpi

  snap_z3c:
    alias: Grab a picture from z3c
    sequence:
      - service: shell_command.cam_snap
        data:
          cam: z3c

  snap_delete:
    alias: Delete snapshot
    sequence:
      - delay:
          minutes: 2
      - service: shell_command.snap_ldelete
        data_template:
          cam: "{{ cam }}"
      - service: shell_command.snap_rdelete
        data_template:
          cam: "{{ cam }}"

  snap_send:
    alias: Send a CCTV picture
    sequence:
      # Disable ev. deletion job
      - service: script.turn_off
        data:
          entity_id: script.snap_delete
      - service_template: "script.snap_{{ cam }}"
      - service: shell_command.snap_upload
        data_template:
          cam: "{{ cam }}"
      - service: notify.facebook_me
        data_template:
          message: Camera image
          data:
            attachment:
              type: image
              payload:
                url: !secret snap_public_url
      - service: script.snap_delete
        data_template:
          cam: "{{ cam }}"


automation:
  - alias: Z3C Battery saver
    trigger:
      - platform: numeric_state
        entity_id: sensor.z3c_battery
        below: 25
    action:
      - service: homeassistant.turn_off
        entity_id: switch.z3c_cam
      - service: notify.pushover
        data:
          message: "Z3C battery below 25%. Let's stop the camera for a while."

  - alias: Z3C Camera enabler
    trigger:
      - platform: numeric_state
        entity_id: sensor.z3c_battery
        above: 80
    action:
      - service: homeassistant.turn_on
        entity_id: switch.z3c_cam
      - service: notify.pushover
        data:
          message: "Z3C battery above 80%. Starting the camera app..!"

  - alias: Daily reboot of the Z3C
    trigger:
      - platform: time
        hours: 4
        minutes: 0
        seconds: 0
    action:
      service: script.z3c_restart


group:
  cctv:
    name: CCTV
    view: yes
    icon: mdi:camera-enhance
    entities:
      - binary_sensor.bathroom_presence
      - binary_sensor.hallway_presence
      - binary_sensor.kitchen_presence
      - binary_sensor.toilet_presence
      - group.c1
      - group.c2
      - group.z3c
      - group.raspicam_octopi
      - group.raspicam_rfpi
      - group.raspicam_winpi
      - group.modect

  cameras:
    name: Cameras
    entities:
      - camera.c1
      - camera.octopi
      - camera.rfpi
      - camera.winpi
      - camera.c2
      - camera.z3c

  c1:
    name: Foscam C1
    control: hidden
    entities:
      - camera.c1
      - switch.c1_ir
      - switch.c1_modect
      - switch.c1_sodect
      - switch.c1_state
      - sensor.c1_events
      - sensor.c1_status

  c2:
    name: Foscam C2
    control: hidden
    entities:
      - camera.c2
      - switch.c2_ir
      - switch.c2_modect
      - switch.c2_sodect
      - switch.c2_state
      - sensor.c2_events
      - sensor.c2_status

  z3c:
    name: Sony Z3C
    control: hidden
    entities:
      - sensor.z3c_battery
      - camera.z3c
      - switch.z3c_cam
      - switch.z3c_cam_front
      - switch.z3c_torch
      - sensor.z3c_events
      - switch.z3c_state
      - sensor.z3c_status
      - script.z3c_restart
      - sensor.z3c_video_connections
      - sensor.z3c_audio_connections
      - switch.z3c_focus
      - switch.z3c_frontfacing_camera
      - switch.z3c_gps_active
      - switch.z3c_night_vision
      - switch.z3c_overlay
      - switch.z3c_video_recording
      - switch.z3c_white_balance_lock

  modect:
    name: Motion detection
    entities:
      - binary_sensor.bathroom_presence
      - binary_sensor.hallway_presence
      - binary_sensor.kitchen_presence
      - binary_sensor.toilet_presence
      - switch.z3c_cam
      - switch.c1_state
      - switch.c2_state
      - switch.z3c_state
      - switch.octopi_state
      - switch.rfpi_state
      - switch.winpi_state
      - switch.c1_modect
      - switch.c2_modect
      - switch.c1_sodect
      - switch.c2_sodect

  raspicam_octopi:
    name: Raspberry Pi Camera (octopi)
    control: hidden
    entities:
      - camera.octopi
      - switch.octopi_state
      - sensor.octopi_status
      - sensor.octopi_events

  raspicam_rfpi:
    name: Raspberry Pi Camera (rfpi)
    control: hidden
    entities:
      - camera.rfpi
      - switch.rfpi_state
      - sensor.rfpi_status
      - sensor.rfpi_events

  raspicam_winpi:
    name: Raspberry Pi Camera (winpi)
    control: hidden
    entities:
      - camera.winpi
      - switch.winpi_state
      - sensor.winpi_status
      - sensor.winpi_events


homeassistant:
  customize:
    # Automation
    automation.z3c_battery_saver:
      hidden: true
    automation.z3c_camera_enabler:
      hidden: true
    # Switches
    switch.z3c_cam:
      icon: mdi:camera
    switch.z3c_cam_front:
      icon: mdi:camera-front
    switch.z3c_torch:
      icon: mdi:flashlight
    switch.c1_ir:
      icon: mdi:weather-night
    switch.c2_ir:
      icon: mdi:weather-night
    switch.c1_modect:
      icon: mdi:run
    switch.c2_modect:
      icon: mdi:run
    switch.c1_sodect:
      icon: mdi:surround-sound
    switch.c2_sodect:
      icon: mdi:surround-sound
    # Sensors
    sensor.z3c_battery:
      icon: mdi:battery
    # Scripts
    script.z3c_restart:
      icon: mdi:power
    script.smoke_break:
      icon: mdi:smoking
    script.smoke_break_timer_off:
      hidden: true

# vim: set filetype=yaml et sw=2 ts=2 :
