binary_sensor:
  - platform: flic
    host: rastapi.lan
    port: 5551
    discovery: false

  - platform: flic
    host: rfpi.lan
    port: 5551
    discovery: false


automation:
  - alias: Start a smoke break when the flic button is pressed and the outdoor light is off
    trigger:
      - platform: event
        event_type: flic_click
        event_data:
          button_name: !secret flic_button_white_1
          click_type: single
    condition:
      - condition: state
        entity_id: light.terrace_light
        state: 'off'
    action:
      - service: script.smoke_break

  - alias: Turn off the outdoor light if it is on
    trigger:
      - platform: event
        event_type: flic_click
        event_data:
          button_name: !secret flic_button_white_1
          click_type: single
    condition:
      - condition: state
        entity_id: light.terrace_light
        state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.terrace_light
      - service: script.turn_off
        data:
          entity_id: script.smoke_break_timer_off

  - alias: Display a caring message on the TV
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_black_1
        click_type: single
    action:
      - service: notify.livingroom_tv
        data:
          message: !secret flic_button_message_1

  - alias: Display a somewhat less caring message on the TV
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_black_1
        click_type: double
    action:
      - service: notify.livingroom_tv
        data:
          message: !secret flic_button_message_2

  - alias: Toggle the livebox play socket
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_black_1
        click_type: hold
    action:
      service: switch.toggle
      data:
        entity_id: switch.livebox_play_socket

  # - alias: Watch TV when single click flick button
  #   trigger:
  #     platform: event
  #     event_type: flic_click
  #     event_data:
  #       button_name: !secret flic_button_black_2
  #       click_type: single
  #   action:
  #     - service: script.watch_tv
  #
  # - alias: Switch to kodi on double click flick button
  #   trigger:
  #     platform: event
  #     event_type: flic_click
  #     event_data:
  #       button_name: !secret flic_button_black_2
  #       click_type: double
  #   action:
  #     - service: script.start_kodi
  #
  # - alias: Stop activity when holding
  #   trigger:
  #     platform: event
  #     event_type: flic_click
  #     event_data:
  #       button_name: !secret flic_button_black_2
  #       click_type: hold
  #   action:
  #     - service: script.power_off

  - alias: Toggle guest room TV when flic button is pressed
    trigger:
      platform: event
      event_type: flic_click
      event_data:
        button_name: !secret flic_button_white_2
        click_type: single
    action:
      - service: switch.toggle
        entity_id: switch.guest_room_tv

  # - alias: Turn on guest TV and light when button is double pressed
  #   trigger:
  #     platform: event
  #     event_type: flic_click
  #     event_data:
  #       button_name: !secret flic_button_white_2
  #       click_type: double
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.guest_room_light
  #     - service: switch.turn_on
  #       entity_id: switch.guest_room_tv

  - alias: Start bedtime script on single button press
    trigger:
      - platform: event
        event_type: flic_click
        event_data:
          button_name: !secret flic_button_black_2
          click_type: single
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.bedtime
      - service: script.lock_door

  - alias: Turn off all on long button press
    trigger:
      - platform: event
        event_type: flic_click
        event_data:
          button_name: !secret flic_button_black_2
          click_type: hold
    action:
      - service: script.all_off
      - service: script.lock_door

# vim: set filetype=yaml et sw=2 ts=2 :
