group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.shortcuts
      - group.roomba
      - group.tracked_devices
      - group.weather_shortcut
      - group.misc
      - group.cameras
      - group.light_groups

  shortcuts:
    name: Shortcuts
    control: hidden
    view: no
    entities:
      - alarm_control_panel.ha_alarm
      - sensor.ip_location_short
      - lock.home
      - script.all_off
      - script.smoke_break
      - script.lock_n_go
      - scene.living_room_dim
      - scene.bedtime


homeassistant:
  customize:
    group.shortcuts:
      order: 1
    group.living_room:
      order: 1
    group.terrace_kitchen:
      order: 2
    group.bedrooms:
      order: 4
    group.media_players:
      order: 5
    group.cctv:
      order: 6
    group.zwave:
      order: 7

# vim: set filetype=yaml et sw=2 ts=2 :
