remote:
  - platform: harmony
    name: Harmony Hub
    host: harmonyhub.lan
    scan_interval: 30


# automation:
#   - alias: Ensure the livebox-play is turned off when stopping it using Harmony Hub
#     trigger:
#       - platform: state
#         entity_id: remote.harmony_hub
#     condition:
#       condition: template
#       value_template: '{{ trigger.from_state.attributes.current_activity == "Watch TV" }}'
#     action:
#       - service: media_player.turn_off
#         entity_id: media_player.livebox_play
#
#   - alias: Ensure the livebox-play is turned on when starting TV using Harmony Hub
#     trigger:
#       - platform: state
#         entity_id: remote.harmony_hub
#     condition:
#       condition: template
#       value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV" }}'
#     action:
#       - service: media_player.turn_on
#         entity_id: media_player.livebox_play


rest_command:
  shield_kodi:
    url: http://nasteanas.lan:8993/shield/kodi
  kvm_start_win81_gpu:
    url: http://nasteanas.lan:8993/kvm/win81-gpu/start
  kvm_stop_win81_gpu:
    url: http://nasteanas.lan:8993/kvm/win81-gpu/stop


sensor:
  - platform: template
    sensors:
      harmony_hub:
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
        friendly_name: 'Harmony Hub'


script:
  turn_on_tv:
    alias: Turn on the living room TV
    sequence:
      # Try via the built in component
      - service: media_player.turn_on
        data:
          entity_id: media_player.tv
      # Use harmony hub if that did not work
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 42046341
          command: PowerOn

  select_tv_source:
    alias: Set the living room TV source
    sequence:
      - delay:
          seconds: 2
      - service: media_player.select_source
        data_template:
          entity_id: media_player.living_room_tv
          source: '{{ source }}'
      # Harmony Hub fallback
      - service: remote.send_command
        data_template:
          entity_id: remote.harmony_hub
          device: 42046341
          command: >
            {%- if source == "Nvidia Shield TV" -%}
              InputHdmi1
            {%- elif source == "Kinivo HDMI Splitter" -%}
              InputHdmi2
            {%- elif source == "Orange Livebox Play" -%}
              InputHdmi3
            {%- elif source == "Sony Playstation 3" -%}
              InputHdmi4
            {%- endif -%}

  tv_volume_mute:
    alias: Mute TV
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 42046341
          command: Mute

  tv_volume_down:
    alias: Lower TV volume
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 42046341
          command: VolumeDown

  tv_volume_up:
    alias: Increase TV volume
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 42046341
          command: VolumeUp

  amp_toggle:
    alias: Toggle the amp
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 40566636
          command: PowerToggle

  watch_tv:
    alias: Watch TV
    sequence:
      - service: script.turn_on_tv
      - service: script.turn_on_livebox_play
      - service: script.select_tv_source
        data:
          source: 'Orange Livebox Play'
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 40565609
          command: Return
      - service: media_player.select_source
        entity_id: media_player.livebox_play
        data:
          source: "BFM TV"

  harmony_watch_tv:
    alias: Watch TV
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.livebox_play_socket
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Watch TV

  shield_tv:
    alias: Shield TV
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 40563742
          command: PowerOn
      - service: script.turn_on_tv
      - service: script.select_tv_source
        data:
          source: 'Nvidia Shield TV'

  start_kodi:
    alias: Kodi@Shield
    sequence:
      - service: script.shield_tv
      - service: rest_command.shield_kodi

  turn_off_nvidia_shield_tv:
    alias: Turn off Nvidia Shield TV
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 40563742
          command: PowerOff

  play_ps3:
    alias: Play PS3
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 40567705
          command: PowerOn
      - service: script.turn_on_tv
      - service: script.select_tv_source
        data:
          source: 'Sony Playstation 3'

  harmony_play_ps3:
    alias: Launch Play PS3 Activity
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Play PS3

  turn_off_ps3:
    alias: Turn off PS3
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 40567705
          command: PowerOff

  start_dolphin:
    alias: Start dolphin-emu
    sequence:
      # Start VM
      - service: rest_command.kvm_start_win81_gpu
      # Make sure the TV is on
      - service: script.turn_on_tv
      # Switch source
      - service: script.select_tv_source
        data:
          source: Kinivo HDMI Splitter

  turn_off_dolphin:
    alias: Turn off dolphin-emu host
    sequence:
      # Stop VM
      - service: rest_command.kvm_stop_win81_gpu

  harmony_power_off:
    alias: Stop current activity
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: PowerOff


homeassistant:
  customize:
    # Sensors
    - entity_id: sensor.harmony_hub
      icon: mdi:remote
    # Scripts
    - entity_id: script.amp_toggle
      icon: mdi:amplifier
    - entity_id: script.play_ps3
      icon: mdi:gamepad-variant
    - entity_id: script.start_kodi
      icon: mdi:kodi
    - entity_id: script.power_off
      icon: mdi:stop-circle
    - entity_id: script.wake_nvidia_shield
      icon: mdi:alarm
    - entity_id: script.watch_tv
      icon: mdi:television
    - entity_id: script.shield_tv
      icon: mdi:television-guide
    - entity_id: script.start_dolphin
      icon: mdi:fish

# vim: set filetype=yaml et sw=2 ts=2 :
