remote:
  - platform: harmony
    name: Harmony Hub
    host: harmonyhub.lan
    scan_interval: 30


automation:
  - alias: Ensure the livebox-play is turned off when stopping it using Harmony Hub
    trigger:
      - platform: state
        entity_id: remote.harmony_hub
    condition:
      condition: template
      value_template: '{{ trigger.from_state.attributes.current_activity == "Watch TV" }}'
    action:
      - service: media_player.turn_off
        entity_id: media_player.livebox_play

  - alias: Ensure the livebox-play is turned on when starting TV using Harmony Hub
    trigger:
      - platform: state
        entity_id: remote.harmony_hub
    condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "Watch TV" }}'
    action:
      - service: media_player.turn_on
        entity_id: media_player.livebox_play


rest_command:
  shield_kodi:
    method: get
    url: http://nasteanas.lan:8993/shield/kodi


sensor:
  - platform: template
    sensors:
      harmony_hub:
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
        friendly_name: 'Harmony Hub'


script:
  amp_toggle:
    alias: Toggle the amp
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 40566636
          command: PowerToggle

  watch_tv:
    alias: Watch TV
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.livebox_play_socket
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Watch TV

  shield_tv:
    alias: Shield TV
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Shield

  start_kodi:
    alias: Kodi@Shield
    sequence:
      - service: script.turn_on
        data:
          entity_id: script.shield_tv
      - service: rest_command.shield_kodi

  play_ps3:
    alias: PS3
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Play PS3

  power_off:
    alias: Stop current activity
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: PowerOff

  tv_volume_mute:
    alias: Mute TV
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 42046341
          command: Mute

  tv_volume_down:
    alias: Lower TV volume
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 42046341
          command: VolumeDown

  tv_volume_up:
    alias: Increase TV volume
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 42046341
          command: VolumeUp


homeassistant:
  customize:
    # Sensors
    - entity_id: sensor.harmony_hub
      icon: mdi:remote
    # Scripts
    - entity_id: script.amp_toggle
      icon: mdi:amplifier
    - entity_id: script.play_ps3
      icon: mdi:gamepad-variant
    - entity_id: script.start_kodi
      icon: mdi:kodi
    - entity_id: script.power_off
      icon: mdi:stop-circle
    - entity_id: script.wake_nvidia_shield
      icon: mdi:alarm
    - entity_id: script.watch_tv
      icon: mdi:television
    - entity_id: script.shield_tv
      icon: mdi:television-guide

# vim: set filetype=yaml et sw=2 ts=2 :
