automation:
  - alias: Notify when HA starts
    trigger:
      - platform: event
        event_type: homeassistant_start
    action:
      service: notify.html5
      data:
        message: "Home Assistant has (re)started"
        data:
          priority: -1

  - alias: Start disabled automations (cause they are annoying as fuck)
    trigger:
      - platform: event
        event_type: homeassistant_start
    action:
      - delay: 00:05:00
      - service: notify.html5
      - service: automation.turn_on
        entity_id: automation.react_to_my_homecoming
      - service: automation.turn_on
        entity_id: automation.talk_to_my_wife_when_she_gets_home

  - alias: Update notifications
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.html5
      data_template:
        message: "Home Assistant {{ states.updater.updater.state }} is now available."


rest_command:
  ha_restart:
    method: get
    url: http://nasteanas.lan:8993/ha/restart


script:
  ha_restart:
    alias: 'Restart HASS'
    sequence:
      - service: rest_command.ha_restart

  ha_reload_config:
    alias: 'Reload core config'
    sequence:
      - service: homeassistant.reload_core_config

# vim: set filetype=yaml et sw=2 ts=2 :

