light:
  - platform: hue
    host: philips-hue.lan
    allow_unreachable: true


automation:
  - alias: Hue Master Switch ON pressed
    trigger:
      - platform: event
        event_type: zhue_switch_master_button_INITIAL_PRESSED_4
      - platform: event
        event_type: zhue_switch_master_button_SHORT_RELEASED_4
    action:
      - service: script.hue_master_switch_off

  - alias: Hue Master Switch OFF pressed
    trigger:
      - platform: event
        event_type: zhue_switch_master_button_INITIAL_PRESSED_1
      - platform: event
        event_type: zhue_switch_master_button_SHORT_RELEASED_1
    action:
      - service: script.hue_master_switch_on


group:
  light_groups:
    name: Lights
    view: no
    entities:
      - light.front_door
      - light.living_room
      - light.terrace
      - light.guest_room
      - light.bedroom
      - light.toilet
      - light.kitchen
      - light.hallway

  light_bulbs:
    name: Light bulbs
    view: no
    entities:
      - light.front_door_light
      - light.living_room_light_tv
      - light.living_room_light_table
      - light.terrace_light
      - light.guest_room_light
      - light.bedroom_light
      - light.toilet_light
      - light.kitchen_light
      - light.hallway_light


scene:
  - name: Living Room Normal
    entities:
      light.living_room:
        state: on
        transition: 3
        brightness: 150
        xy_color: [ 0.4448, 0.4066 ]

  - name: Living Room Dim
    entities:
      light.living_room:
        state: on
        transition: 3
        brightness: 75
        xy_color: [ 0.5926, 0.3814 ]
      light.entrance:
        state: off
        transition: 1
      light.terrace:
        state: off
        transition: 1
      light.kitchen:
        state: off
        transition: 1

  - name: Flash Living Room Lights
    entities:
      light.living_room:
        state: on
        flash: long

  - name: Bedtime
    entities:
      light.terrace:
        state: off
      light.hallway:
        state: off
      light.toilet:
        state: off
      light.bathroom:
        state: off
      light.guest_room:
        state: off
      light.bedroom:
        state: off


sensor:
  - platform: command_line
    name: 'Toilet Lux'
    command: /scripts/zhue.sh lux toilet
    value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
    unit_of_measurement: klx

  - platform: command_line
    name: 'Toilet Temperature'
    command: /scripts/zhue.sh temperature toilet
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: 째C

  - platform: command_line
    name: 'Toilet Presence'
    command: /scripts/zhue.sh presence toilet
    value_template: '{{ value_json.state.presence }}'

  - platform: command_line
    name: 'Hallway Lux'
    command: /scripts/zhue.sh lux hallway
    value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
    unit_of_measurement: klx

  - platform: command_line
    name: 'Hallway Temperature'
    command: /scripts/zhue.sh temperature hallway
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: 째C

  - platform: command_line
    name: 'Hallway Presence'
    command: /scripts/zhue.sh presence hallway
    value_template: '{{ value_json.state.presence }}'

  - platform: command_line
    name: 'Kitchen Lux'
    command: /scripts/zhue.sh lux kitchen
    value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
    unit_of_measurement: klx

  - platform: command_line
    name: 'Kitchen Temperature'
    command: /scripts/zhue.sh temperature kitchen
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: 째C

  - platform: command_line
    name: 'Kitchen Presence'
    command: /scripts/zhue.sh presence kitchen
    value_template: '{{ value_json.state.presence }}'

  - platform: command_line
    name: 'Bathroom Lux'
    command: /scripts/zhue.sh lux bathroom
    value_template: '{{ value_json.state.lightlevel | float / 1000 }}'
    unit_of_measurement: klx

  - platform: command_line
    name: 'Bathroom Temperature'
    command: /scripts/zhue.sh temperature bathroom
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: 째C

  - platform: command_line
    name: 'Bathroom Presence'
    command: /scripts/zhue.sh presence bathroom
    value_template: '{{ value_json.state.presence }}'


script:
  hue_master_switch_on:
    alias: 'Hue Master Dimmer Switch ON pressed'
    sequence:
      - service: script.turn_on
        data:
          entity_id: script.watch_tv

  hue_master_switch_off:
    alias: 'Hue Master Dimmer Switch OFF pressed'
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: PowerOff
      - service: switch.turn_off
        data:
          entity_id: switch.guest_room_tv

  flash_living_room_lights:
    alias: Flash Living Room Lights
    sequence:
      - service: scene.turn_on
        entity_id: scene.flash_living_room_lights

  smoke_break:
    alias: "Smoke break"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
          entity_id: script.smoke_break_timer_off
      - service_template: >
          light.{% if is_state('light.terrace', 'on') %}turn_off{% else %}turn_on{% endif %}
        data:
          entity_id: light.terrace
          color_name: white
          brightness: 217 # 85%
          # {% if is_state('light.terrace', 'on') %}
          # color_name: white
          # brightness: 217 # 85%
          # {% endif %}
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.smoke_break_timer_off

  smoke_break_timer_off:
    alias: "Smoke break: Turn off lamp after 5 minutes"
    sequence:
      - delay:
          minutes: 5
      - service: light.turn_off
        data:
          entity_id: light.terrace

# vim: set filetype=yaml et sw=2 ts=2 :
