media_player:
  - platform: liveboxplaytv
    name: Livebox Play
    host: livebox-play.lan


binary_sensor:
  - platform: command_line
    name: Livebox Play TV
    sensor_class: power
    command: nmap -p 8080 -oG - --open livebox-play.lan 2>/dev/null | awk '!/^#/' | grep -q open && echo open || echo closed
    payload_on: open
    payload_off: closed


automation:
  - alias: Setup routing for livebox-play
    trigger:
      - platform: event
        event_type: homeassistant_start
    action:
      service: shell_command.livebox_play_tv_setup_routing
  - alias: Daily reboot of the Livebox Play TV
    trigger:
      - platform: time
        hours: 4
        minutes: 35
        seconds: 12
    action:
      - service: script.reboot_livebox_play


shell_command:
  livebox_play_tv_setup_routing: !secret livebox_play_tv_setup_routing
  livebox_play_tv_turn_on: liveboxplaytv -H livebox-play.lan on
  livebox_play_tv_turn_off: liveboxplaytv -H livebox-play.lan off


script:
  turn_off_livebox_play_tv:
    alias: Turn off the livebox play
    sequence:
      - service: media_player.turn_off
        data:
          entity_id: media_player.livebox_play
      # Turn the socket off
      - service: script.pilight_turn_off_livebox_play_tv

  reboot_livebox_play:
    alias: Reboot Livebox Play TV via pilight
    sequence:
      - service: switch.turn_off
        data:
          entity_id: switch.virt_livebox_play
      - delay:
          minutes: 10
      - service: switch.turn_on
        data:
          entity_id: switch.virt_livebox_play
      - delay:
          minutes: 5
      - service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 40565609
          command: PowerToggle
      - service: media_player.turn_off
        data:
          entity_id: media_player.livebox_play

  turn_on_livebox_play:
    alias: Force turning on the Livebox Play TV
    sequence:
      # Turn the socket on
      - service: script.pilight_turn_on_livebox_play_tv
      # Try to use the built-in component
      - service: media_player.turn_on
        data:
          entity_id: media_player.livebox_play
      # Resort to external script
      - service: shell_command.livebox_play_tv_turn_on

  pilight_turn_on_livebox_play_tv:
    alias: "Send 3 turn on RF commands"
    sequence:
      # Turn on socket
      - service: homeassistant.turn_on
        data:
          entity_id: switch.livebox_play_socket
      # Turn on socket (2)
      - service: homeassistant.turn_on
        data:
          entity_id: switch.livebox_play_socket
      # Turn on socket (3)
      - service: homeassistant.turn_on
        data:
          entity_id: switch.livebox_play_socket

  pilight_turn_off_livebox_play_tv:
    alias: "Send 3 turn off RF commands"
    sequence:
      # Turn off socket
      - service: homeassistant.turn_off
        data:
          entity_id: switch.livebox_play_socket
      # Turn off socket (2)
      - service: homeassistant.turn_off
        data:
          entity_id: switch.livebox_play_socket
      # Turn off socket (3)
      - service: homeassistant.turn_off
        data:
          entity_id: switch.livebox_play_socket


switch:
  - platform: pilight
    switches:
      Livebox Play Socket:
        on_code:
          protocol: pollin
          systemcode: 1
          unitcode: 4
          'on': 1
        off_code:
          protocol: pollin
          systemcode: 1
          unitcode: 4
          'off': 1

  - platform: template
    switches:
      virt_livebox_play:
        friendly_name: Livebox Play
        value_template: "{{ is_state('binary_sensor.livebox_play_tv', 'on' ) }}"
        turn_on:
          service: script.pilight_turn_on_livebox_play_tv
        turn_off:
          service: script.pilight_turn_off_livebox_play_tv


# vim: set filetype=yaml et sw=2 ts=2 :
