group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.info
      - group.shortcuts
      - group.weather_shortcut
      - camera.c1
      - camera.winpi
      - group.light_groups

  info:
    name: Info
    control: hidden
    view: no
    entities:
      - device_tracker.her_phone
      - device_tracker.n5x
      - sensor.ip_location_short
      - sensor.exchange_rate_1_btc

  shortcuts:
    name: Shortcuts
    control: hidden
    view: no
    entities:
      - alarm_control_panel.ha_alarm
      - lock.home
      - script.all_off
      - script.smoke_break
      - scene.living_room_dim
      - scene.bedtime


homeassistant:
  customize:
    group.info:
      order: 1
    group.shortcuts:
      order: 2
    group.living_room:
      order: 1
    group.terrace_kitchen:
      order: 2
    group.bedrooms:
      order: 4
    group.media_players:
      order: 5
    group.cctv:
      order: 6
    group.zwave:
      order: 7

# vim: set filetype=yaml et sw=2 ts=2 :
