media_player:
  - platform: kodi
    name: Kodi
    host: shield.lan
    port: 8080
    username: !secret player_kodi_username
    password: !secret player_kodi_password

  - platform: webostv
    host: lgwebostv.lan
    mac: !secret lg_tv_mac_addr
    name: Living Room TV

  - platform: cast
    host: chromecast-audio.lan
    name: BlindCast

  - platform: cast
    host: chromecast.lan
    name: BrightCast

  - platform: universal
    name: TV
    children:
      - media_player.kodi
      - media_player.nvidia_shield_tv
      - media_player.livebox_play
      - media_player.living_room_tv
    commands:
      turn_on:
        service: remote.send_command
        data:
          entity_id: remote.harmony_hub
          device: 42046341
          command: PowerOn
        # service: media_player.turn_on
        # data:
        #   entity_id: media_player.living_room_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.living_room_tv
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.living_room_tv
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.living_room_tv
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.living_room_tv
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.living_room_tv
          source: '{{ source }}'
    attributes:
      is_volume_muted: media_player.living_room_tv|is_volume_muted
      state: media_player.living_room_tv
      volume_level: media_player.living_room_tv|volume_level
      source: media_player.living_room_tv|source
      source_list: media_player.living_room_tv|source_list

group:
  media_players:
    name: Media Players
    view: yes
    icon: mdi:music-circle
    entities:
      - media_player.living_room_tv
      - media_player.kodi
      - media_player.livebox_play
      - media_player.blindcast
      - media_player.brightcast
      - media_player.nvidia_shield_tv


automation:
  - alias: Turn off TV appliances if the TV is off for an hour
    trigger:
      platform: state
      entity_id: media_player.living_room_tv
      state: 'off'
      for:
        hours: 1
    action:
      - service: script.turn_off_media_players

  - alias: 'Shut down livebox-play when TV is on and not displaying livebox-play'
    initial_state: false
    trigger:
      - platform: template
        value_template: "{{ is_state('media_player.living_room_tv', 'playing') and not is_state_attr('media_player.living_room_tv', 'source', 'Orange Livebox Play') }}"
        # for:
        #   seconds: 30
    action:
      - service: service.turn_off_livebox_play

  - alias: 'Watching Téva'
    initial_state: false
    trigger:
      - platform: template
        value_template: >
          "{{ is_state_attr('media_player.living_room_tv', 'source', 'Orange Livebox Play') and is_state_attr('media_player.livebox_play', 'source', 'Téva') }}"
    action:
      - service: notify.html5
        data:
          message: 'Marine is watching Téva again!'
      - service: notify.livingroom_tv
        data:
          message: 'Mimine! Tu regardes encore Téva! :)'

  - alias: 'Playing PS3'
    initial_state: false
    trigger:
      - platform: template
        value_template: "{{ is_state_attr('media_player.living_room_tv', 'source', 'Sony Playstation 3') }}"
    action:
      - service: notify.livingroom_tv
        data:
          message: 'Oh non, Mimine. Pas Skyrim ! PAS ENCORE !'

#   - alias: Turn off the livebox_play is it not currently displayed
#     trigger:
#       - platform: template
#     condition:
#       condition: template
#       value_template: '{{ trigger.from_state.attributes.current_activity == "Watch TV" }}'
#     action:
#       - service: media_player.turn_off
#         entity_id: media_player.livebox_play

# vim: set filetype=yaml et sw=2 ts=2 :
