lock:
  - platform: nuki
    host: !secret nuki_bridge
    token: !secret nuki_token


script:
  lock_door:
    alias: Lock door
    sequence:
      - service: lock.lock
        data:
          entity_id: lock.home

  unlock_door:
    alias: Unlock door
    sequence:
      - service: lock.unlock
        data:
          entity_id: lock.home

  lock_n_go:
    alias: Lock'n'go
    sequence:
      - delay:
          seconds: 15
      - service: script.lock_door


automation:
  - alias: Lock door if everybody is home
    trigger:
      - platform: state
        entity_id: device_tracker.n5x  #group.main_devices
        state: 'home'
        for:
          seconds: 10
    condition:
      condition: state
      entity_id: lock.home
      state: 'unlocked'
    action:
      - service: notify.html5
        data:
          message: "You've been home for a while. Maybe it is time to lock the door."
          data:
            tag: 'lock-door-query'
            actions:
              - action: lock_door
                icon: https://materialdesignicons.com/api/download/icon/png/D711AFDE-2B8D-4932-82AC-A04E7B2810AE/48
                title: Lock the door

  - alias: HTML5 push notification action button clicked
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: lock_door
    action:
      - service: script.lock_door

  - alias: Door has been locked
    trigger:
      - platform: state
        entity_id: lock.home
        to: 'locked'
    action:
      - service: notify.html5
        data:
          message: "Front door has been locked"
          renotify: True

  - alias: Door has been unlocked
    trigger:
      - platform: state
        entity_id: lock.home
        to: 'unlocked'
    action:
      - service: notify.html5
        data:
          message: "Front door has been unlocked"
          renotify: True

# vim: set filetype=yaml et sw=2 ts=2 :
