automation:
  - alias: Train reminder
    trigger:
      - platform: time
        hours: 16
        minutes: 25
        seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.zanzito_n5x
        state: work
    action:
      service: script.train_reminder

  - alias: Train reminder postpone requested
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: postpone_train_reminder
    action:
      - delay: 01:00:00
      - service: script.train_reminder

  - alias: Time to go to bed
    trigger:
      - platform: time
        hours: 21
        minutes: 50
        seconds: 0
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.n5x
          state: home
        - condition: time
          after: '21:00:00'
          weekday:
            - mon
            - tue
            - wed
            - thu
            - sun
    action:
      - service: tts.google_say
        entity_id: media_player.blindcast
        data:
          message: "C'est l'heure!"
      - service: scene.turn_on
        entity_id: scene.flash_living_room_lights

  # - alias: 'Bruh your phone is dying'
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: sensor.nexus_5x_battery
  #       below: 30
  #   action:
  #     service: notify.pushover
  #     data:

script:
  train_reminder:
    sequence:
      service: notify.html5
      data:
        message: 'Time to leave for your train'
        data:
          tag: "train-reminder"
          actions:
            - action: postpone_train_reminder
              icon: https://materialdesignicons.com/api/download/28F85724-265B-4C24-9975-DDDF788A99E5/000000/1/FFFFFF/0/48
              title: Postpone

# vim: set filetype=yaml et sw=2 ts=2 :
