sensor:
  - platform: yr
    monitored_conditions:
      - symbol

  - platform: darksky
    api_key: !secret darksky_api_key
    update_interval: '00:03:00'
    forecast:
      - 1
      - 2
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max


group:
  weather:
    name: Weather
    entities:
      - group.weather_indoor
      - group.weather_outdoor

  weather_shortcut:
    name: Weather
    entities:
      - sensor.dark_sky_temperature
      - sensor.yr_symbol
      - sensor.dark_sky_rain
      - sensor.bathroom_temperature
      - sensor.hallway_temperature
      - sensor.kitchen_temperature
      - sensor.toilet_temperature

  weather_indoor:
    name: Weather
    entities:
      - sensor.bathroom_temperature
      - sensor.hallway_temperature
      - sensor.kitchen_temperature
      - sensor.toilet_temperature
      - sensor.fibaro_system_fgsd002_smoke_sensor_temperature

  weather_outdoor:
    name: Weather
    entities:
      - sensor.yr_symbol
      - sensor.owm_temperature
      - sensor.owm_rain


homeassistant:
  customize:
    sensor.owm_rain:
      icon: mdi:weather-rainy
    sensor.own_rain:
      icon: mdi:weather-rainy

# vim: set filetype=yaml et sw=2 ts=2 :
