wemo:
  static:
    - wemo-insight-01.lan
    - wemo-insight-02.lan

homeassistant:
  customize:
    switch.wemo_insight__nasteanas:
      icon: mdi:server-network

# vim: set filetype=yaml et sw=2 ts=2
